"""Abu Simbel temples — sub-sites."""

ABU_SIMBEL_CHILDREN = [
    {
        "slug": "abu_simbel_great_temple",
        "name": "Great Temple of Ramesses II",
        "name_ar": "المعبد الكبير لرمسيس الثاني",
        "category": "Pharaonic",
        "subcategory": "Tombs & Temples",
        "region": "Aswan",
        "parent_slug": "abu_simbel",
        "period": "New Kingdom (19th Dynasty, c. 1264 BC)",
        "featured": True,
        "description": "The larger of the two Abu Simbel temples, fronted by four colossal 20-meter statues of Ramesses II. Cut entirely into the rock cliff above the Nile. The interior extends 56 meters into the mountain with a Great Hall of eight Osiride pillars, battle reliefs of Kadesh, and the famous 'Sun Festival' sanctuary — twice a year (Feb 22, Oct 22) sunlight penetrates 60 meters to illuminate three of the four statues in the inner sanctum.",
        "has_image": True,
        "coordinates": {"lat": 22.3360, "lng": 31.6256},
        "tags": ["must-visit", "iconic", "UNESCO", "photography"],
        "related_sites": ["abu_simbel", "abu_simbel_small_temple"],
        "images": [],
        "sections": [
            {"title": "The Sun Festival", "content": "On February 22 and October 22 each year, sunlight enters the temple and illuminates three of the four statues in the inner sanctum — Amun-Ra, Ra-Horakhty, and Ramesses II. Ptah, god of the underworld, remains in shadow."},
            {"title": "The UNESCO Rescue (1964–1968)", "content": "To save the temples from Lake Nasser's rising waters after the Aswan High Dam, UNESCO cut the entire complex into 20-ton blocks and reassembled it 65 meters higher. A triumph of 20th-century engineering to match the ancient achievement."},
            {"title": "Battle of Kadesh Reliefs", "content": "The north wall of the Great Hall depicts Ramesses II's self-proclaimed victory at Kadesh (1274 BC) against the Hittites — the earliest illustrated battle narrative in history, though the battle was likely a draw."},
        ],
    },
    {
        "slug": "abu_simbel_small_temple",
        "name": "Small Temple of Nefertari",
        "name_ar": "معبد نفرتاري الصغير",
        "category": "Pharaonic",
        "subcategory": "Tombs & Temples",
        "region": "Aswan",
        "parent_slug": "abu_simbel",
        "period": "New Kingdom (19th Dynasty, c. 1264 BC)",
        "featured": True,
        "description": "Dedicated to the goddess Hathor and to Ramesses II's favorite queen, Nefertari — the only Egyptian temple where a queen's statue is the same height as the king's on the facade. Six 10-meter standing figures (two Nefertari, four Ramesses) frame the entrance. Inside, Hathor-headed columns support the hypostyle hall and reliefs show Nefertari offering to the gods as an equal to Ramesses.",
        "has_image": True,
        "coordinates": {"lat": 22.3370, "lng": 31.6248},
        "tags": ["must-visit", "iconic", "UNESCO"],
        "related_sites": ["abu_simbel", "abu_simbel_great_temple"],
        "images": [],
        "sections": [],
    },
]
