"""Cairo Citadel (Saladin's Citadel) — sub-sites."""

CITADEL_CHILDREN = [
    {
        "slug": "citadel_muhammad_ali_mosque",
        "name": "Mosque of Muhammad Ali",
        "name_ar": "مسجد محمد علي",
        "category": "Islamic",
        "subcategory": "Mosque",
        "region": "Cairo",
        "parent_slug": "cairo_citadel",
        "period": "Ottoman (1830–1848)",
        "featured": True,
        "description": "The landmark Ottoman-style mosque dominating Cairo's skyline, built by Muhammad Ali Pasha between 1830 and 1848. Its twin minarets rise 82 meters and its massive central dome spans 21 meters. The interior is lavishly decorated with alabaster panels (earning it the name 'Alabaster Mosque'), ornate chandeliers, and gilded calligraphy. A clock tower gifted by French King Louis-Philippe stands in the courtyard — given in exchange for the Luxor Obelisk now in Paris.",
        "has_image": True,
        "coordinates": {"lat": 30.0289, "lng": 31.2599},
        "tags": ["must-visit", "iconic", "architecture"],
        "related_sites": ["sultan_hassan_mosque", "al_rifai_mosque"],
        "images": [],
        "sections": [
            {"title": "The Alabaster Interior", "content": "The walls up to 11 meters are clad in fine alabaster, while the upper sections and dome are painted with elaborate Ottoman decorative motifs. Massive chandeliers illuminate the prayer hall."},
            {"title": "The French Clock", "content": "An ornamental clock in the courtyard, a gift from Louis-Philippe of France in 1845, exchanged for the 3,300-year-old Luxor Obelisk now standing in Place de la Concorde, Paris. The clock has never worked — some say it arrived broken."},
        ],
    },
    {
        "slug": "citadel_nasir_muhammad_mosque",
        "name": "Al-Nasir Muhammad Mosque",
        "name_ar": "مسجد الناصر محمد",
        "category": "Islamic",
        "subcategory": "Mosque",
        "region": "Cairo",
        "parent_slug": "cairo_citadel",
        "period": "Mamluk (1318–1335)",
        "featured": False,
        "description": "The oldest surviving mosque within the Citadel, built by Sultan al-Nasir Muhammad ibn Qalawun and serving as the royal mosque of the Mamluk sultans. Distinguished by its two unique minarets — one covered in glazed faience tiles, the other with a distinctive bulbous top in a style influenced by Mongol architecture. The hypostyle prayer hall features a forest of repurposed pharaonic and Roman columns.",
        "has_image": True,
        "coordinates": {"lat": 30.0289, "lng": 31.2599},
        "tags": ["historic", "architecture"],
        "related_sites": ["qalawun_complex"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "citadel_military_museum",
        "name": "National Military Museum",
        "name_ar": "المتحف الحربي القومي",
        "category": "Museum",
        "subcategory": "Specialized Museums",
        "region": "Cairo",
        "parent_slug": "cairo_citadel",
        "period": "Modern (in Harim Palace, built 1827)",
        "featured": False,
        "description": "Housed in the former Harim Palace of Muhammad Ali, this museum traces Egypt's military history from pharaonic times through the October War of 1973. Displays include pharaonic chariots and weapons, medieval Islamic arms and armor, Ottoman military equipment, and modern warfare exhibits with dioramas of key battles.",
        "has_image": True,
        "coordinates": {"lat": 30.0289, "lng": 31.2599},
        "tags": ["indoor", "historic"],
        "related_sites": [],
        "images": [],
        "sections": [],
    },
    {
        "slug": "citadel_gawhara_palace",
        "name": "Gawhara Palace (Bijou Palace)",
        "name_ar": "قصر الجوهرة",
        "category": "Modern",
        "subcategory": "Palace",
        "region": "Cairo",
        "parent_slug": "cairo_citadel",
        "period": "Ottoman (1814)",
        "featured": False,
        "description": "An elegant palace built by Muhammad Ali in 1814, named after his last wife Gawhara Hanim. Features French-style interiors with gilded furniture, crystal chandeliers, painted ceilings, and a throne room. The palace offers panoramic views over Cairo and was the site of the infamous 1811 massacre of the Mamluks.",
        "has_image": True,
        "coordinates": {"lat": 30.0289, "lng": 31.2599},
        "tags": ["historic", "off-the-beaten-path"],
        "related_sites": ["abdeen_palace", "manial_palace"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "citadel_sulayman_pasha_mosque",
        "name": "Mosque of Sulayman Pasha",
        "name_ar": "مسجد سليمان باشا",
        "category": "Islamic",
        "subcategory": "Mosque",
        "region": "Cairo",
        "parent_slug": "cairo_citadel",
        "period": "Ottoman (1528)",
        "featured": False,
        "description": "The first Ottoman-style mosque built in Egypt (1528), marking the transition from Mamluk to Ottoman architectural styles. Its intimate painted dome and delicate Iznik-influenced decoration make it one of Cairo's most beautiful small mosques. Also known as Sariyat al-Gabal (the mosque on the mountain).",
        "has_image": True,
        "coordinates": {"lat": 30.0289, "lng": 31.2599},
        "tags": ["architecture", "off-the-beaten-path"],
        "related_sites": [],
        "images": [],
        "sections": [],
    },
    {
        "slug": "citadel_police_museum",
        "name": "Police Museum",
        "name_ar": "متحف الشرطة",
        "category": "Museum",
        "subcategory": "Specialized Museums",
        "region": "Cairo",
        "parent_slug": "cairo_citadel",
        "period": "Modern",
        "featured": False,
        "description": "A museum tracing the history of Egyptian law enforcement and famous criminal cases. Located in the former prison tower with views over Islamic Cairo. Exhibits include uniforms, weaponry, and displays on notable incidents. The terrace offers one of the best panoramic views of Cairo, the Pyramids, and Mohamed Ali Mosque.",
        "has_image": True,
        "coordinates": {"lat": 30.0289, "lng": 31.2599},
        "tags": ["indoor", "viewpoint"],
        "related_sites": [],
        "images": [],
        "sections": [],
    },
]
