# Coptic & Early Christian Heritage
SITES = [
    {"slug": "coptic_cairo", "name": "Coptic Cairo (Old Cairo)", "name_ar": "القاهرة القبطية (مصر القديمة)",
     "category": "Coptic", "subcategory": "Historic Districts", "region": "Cairo",
     "period": "Roman – Early Islamic (1st century BC onward)",
     "description": "A historic enclave in Old Cairo (Masr el-Qadima) built around the Roman Babylon Fortress. Home to some of the oldest churches in Egypt, the Coptic Museum, a synagogue, and a mosque — a living tapestry of Egyptian religious coexistence spanning 2,000 years.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0057, "lng": 31.2305},
     "tags": ["must-visit", "UNESCO", "religious", "architecture"], "related_sites": ["hanging_church", "coptic_museum", "saints_sergius_and_bacchus_church"]},

    {"slug": "hanging_church", "name": "Hanging Church (Al-Muallaqah)", "name_ar": "الكنيسة المعلقة",
     "category": "Coptic", "subcategory": "Churches", "region": "Cairo",
     "period": "3rd-4th Century AD",
     "description": "One of the oldest churches in Egypt, built atop the gatehouse of Babylon Fortress. Named for its nave suspended above the passage, with stunning icon collections.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0058, "lng": 31.2303},
     "tags": ["must-visit"], "related_sites": ["saints_sergius_and_bacchus_church", "coptic_museum"]},

    {"slug": "saints_sergius_and_bacchus_church", "name": "Church of St. Sergius and Bacchus", "name_ar": "كنيسة أبو سرجة",
     "category": "Coptic", "subcategory": "Churches", "region": "Cairo",
     "period": "4th-5th Century AD",
     "description": "One of the oldest churches in Cairo, built over a cave where the Holy Family is believed to have sheltered during their flight into Egypt.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0055, "lng": 31.2300},
     "tags": ["architecture", "must-visit", "religious"], "related_sites": ["hanging_church", "coptic_museum"]},

    {"slug": "coptic_museum", "name": "Coptic Museum", "name_ar": "المتحف القبطي",
     "category": "Coptic", "subcategory": "Museums", "region": "Cairo",
     "period": "Founded 1908",
     "description": "Houses the world's largest collection of Coptic art and artifacts spanning 2,000 years of Egyptian Christian heritage, including Gnostic Nag Hammadi texts.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0061, "lng": 31.2294},
     "tags": ["must-visit"], "related_sites": ["hanging_church", "babylon_fortress"]},

    {"slug": "saint_catherine_monastery", "name": "St. Catherine's Monastery", "name_ar": "دير سانت كاترين",
     "category": "Coptic", "subcategory": "Monasteries", "region": "South Sinai",
     "period": "6th Century AD (527-565 AD)",
     "description": "The world's oldest continuously operating Christian monastery, nestled at the foot of Mount Sinai. Holds an unrivaled collection of ancient manuscripts and icons.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 28.5561, "lng": 33.9758},
     "tags": ["UNESCO", "must-visit"], "related_sites": ["mount_sinai", "saint_catherine_area"]},

    {"slug": "saint_catherine_area", "name": "St. Catherine Area", "name_ar": "منطقة سانت كاترين",
     "category": "Coptic", "subcategory": "Monasteries", "region": "South Sinai",
     "period": "Various",
     "description": "A UNESCO World Heritage area encompassing the monastery, Mount Sinai, and surrounding sacred landscape revered by Judaism, Christianity, and Islam alike.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 28.5500, "lng": 33.9700},
     "tags": ["UNESCO"], "related_sites": ["saint_catherine_monastery", "mount_sinai"]},

    {"slug": "wadi_el_natrun", "name": "Wadi El Natrun Monasteries", "name_ar": "أديرة وادي النطرون",
     "category": "Coptic", "subcategory": "Monasteries", "region": "Beheira",
     "period": "4th Century AD onwards",
     "description": "Four ancient monasteries in the desert valley where Christian monasticism was born. The spiritual heart of the Coptic Orthodox Church.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.4000, "lng": 30.3500},
     "tags": ["historic", "off-the-beaten-path", "religious"], "related_sites": ["monastery_of_saint_anthony"]},

    {"slug": "monastery_of_saint_anthony", "name": "Monastery of St. Anthony", "name_ar": "دير الأنبا أنطونيوس",
     "category": "Coptic", "subcategory": "Monasteries", "region": "Red Sea",
     "period": "4th Century AD",
     "description": "The oldest Christian monastery in the world, founded at the cave where St. Anthony the Great lived as a hermit. Features 6th-century wall paintings.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 28.9222, "lng": 32.3444},
     "tags": ["historic", "must-visit", "religious"], "related_sites": ["monastery_of_saint_paul"]},

    {"slug": "monastery_of_saint_paul", "name": "Monastery of St. Paul", "name_ar": "دير الأنبا بولا",
     "category": "Coptic", "subcategory": "Monasteries", "region": "Red Sea",
     "period": "5th Century AD",
     "description": "A remote desert monastery near the Red Sea mountains, built over the cave where St. Paul of Thebes lived as the first known Christian hermit.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 28.8700, "lng": 32.4400},
     "tags": ["historic", "must-visit", "off-the-beaten-path", "religious"], "related_sites": ["monastery_of_saint_anthony"]},

    {"slug": "red_monastery", "name": "Red Monastery", "name_ar": "الدير الأحمر",
     "category": "Coptic", "subcategory": "Monasteries", "region": "Sohag",
     "period": "5th Century AD",
     "description": "A 5th-century monastery with recently restored interior paintings that are among the finest late antique artworks discovered anywhere in the world.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 26.5100, "lng": 31.6700},
     "tags": ["historic", "must-visit", "off-the-beaten-path", "religious"], "related_sites": ["white_monastery"]},

    {"slug": "white_monastery", "name": "White Monastery", "name_ar": "الدير الأبيض",
     "category": "Coptic", "subcategory": "Monasteries", "region": "Sohag",
     "period": "5th Century AD",
     "description": "Founded by Saint Shenouda the Great, built from white limestone blocks reused from a nearby pharaonic temple, blending ancient Egyptian and Christian architecture.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 26.5000, "lng": 31.6600},
     "tags": ["historic", "must-visit", "off-the-beaten-path", "religious"], "related_sites": ["red_monastery"]},

    {"slug": "ben_ezra_synagogue", "name": "Ben Ezra Synagogue", "name_ar": "معبد بن عزرا",
     "category": "Coptic", "subcategory": "Churches", "region": "Cairo",
     "period": "9th Century AD (rebuilt 1115)",
     "description": "The oldest synagogue in Cairo, famous for the Cairo Geniza — a treasure trove of 300,000 manuscript fragments spanning a millennium of Jewish life in Egypt.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0056, "lng": 31.2297},
     "tags": ["architecture", "must-visit", "religious"], "related_sites": ["hanging_church", "coptic_museum"]},
]
