"""Coptic Cairo — sub-sites."""

COPTIC_CAIRO_CHILDREN = [
    {
        "slug": "coptic_cairo_hanging_church",
        "name": "The Hanging Church (Al-Mu'allaqa)",
        "name_ar": "الكنيسة المعلقة",
        "category": "Coptic",
        "subcategory": "Churches & Monasteries",
        "region": "Cairo",
        "parent_slug": "coptic_cairo",
        "period": "3rd–7th century CE",
        "featured": True,
        "description": "Cairo's most beautiful church, 'suspended' above the gatehouse of the Roman Babylon Fortress on 15 stone pillars. Dedicated to the Virgin Mary, its nave features 110 ivory-inlaid icons, a 13th-century marble pulpit resting on 13 columns (representing Christ and the 12 apostles), and a 7th-century wooden roof shaped like Noah's Ark.",
        "has_image": True,
        "coordinates": {"lat": 30.0057, "lng": 31.2303},
        "tags": ["must-visit", "iconic", "religious", "architecture"],
        "related_sites": ["coptic_cairo", "coptic_museum"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "coptic_cairo_church_of_st_sergius",
        "name": "Church of Saints Sergius and Bacchus (Abu Serga)",
        "name_ar": "كنيسة أبو سرجة",
        "category": "Coptic",
        "subcategory": "Churches & Monasteries",
        "region": "Cairo",
        "parent_slug": "coptic_cairo",
        "period": "5th century CE",
        "featured": True,
        "description": "One of the oldest churches in Egypt, built over the crypt where the Holy Family is believed to have sheltered during their flight to Egypt. The underground crypt (accessible when not flooded) is a pilgrimage site. The basilica plan with 12 columns (one of dark granite, representing Judas) is typical of early Coptic architecture.",
        "has_image": True,
        "coordinates": {"lat": 30.0053, "lng": 31.2307},
        "tags": ["religious", "pilgrimage", "underground"],
        "related_sites": ["coptic_cairo", "coptic_cairo_hanging_church"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "coptic_cairo_ben_ezra_synagogue",
        "name": "Ben Ezra Synagogue",
        "name_ar": "معبد بن عزرا اليهودي",
        "category": "Coptic",
        "subcategory": "Historic Sites",
        "region": "Cairo",
        "parent_slug": "coptic_cairo",
        "period": "9th century CE (current form 19th c.)",
        "featured": False,
        "description": "The oldest synagogue in Cairo, located within the Coptic compound. Famous for the Cairo Geniza — a storeroom where 300,000 manuscript fragments spanning a millennium were discovered in the 19th century, now one of the most important documentary sources for medieval Middle Eastern history. Tradition associates the site with the place where baby Moses was found.",
        "has_image": True,
        "coordinates": {"lat": 30.0055, "lng": 31.2310},
        "tags": ["religious", "off-the-beaten-path"],
        "related_sites": ["coptic_cairo"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "coptic_cairo_fortress_of_babylon",
        "name": "Fortress of Babylon",
        "name_ar": "حصن بابليون",
        "category": "Greco-Roman",
        "subcategory": "Greco-Roman Sites",
        "region": "Cairo",
        "parent_slug": "coptic_cairo",
        "period": "Roman (c. 30 BC – 3rd century CE)",
        "featured": False,
        "description": "The massive Roman fortress whose remains form the foundation of Coptic Cairo. Two round towers (each 30 meters in diameter) flanked the original river gate — one is visible in the Coptic Museum, the other supports the Hanging Church. The fortress walls were 2 meters thick and enclosed the entire Coptic quarter.",
        "has_image": True,
        "coordinates": {"lat": 30.0060, "lng": 31.2300},
        "tags": ["archaeological", "architecture"],
        "related_sites": ["coptic_cairo", "coptic_cairo_hanging_church"],
        "images": [],
        "sections": [],
    },
]
