"""NMEC, Bibliotheca Alexandrina, Khan El Khalili — sub-sites."""

NMEC_CHILDREN = [
    {
        "slug": "nmec_royal_mummies_hall",
        "name": "Royal Mummies Hall",
        "name_ar": "قاعة المومياوات الملكية",
        "category": "Museum",
        "subcategory": "Gallery",
        "region": "Cairo",
        "parent_slug": "nmec",
        "period": "New Kingdom",
        "featured": True,
        "description": "The solemn underground gallery housing 22 royal mummies transferred from the Egyptian Museum in a spectacular televised 'Pharaohs Golden Parade' on April 3, 2021, with 18 kings and 4 queens carried in nitrogen-filled capsules through Cairo. Includes Ramesses II, Hatshepsut, Seti I, Thutmose III, Ahmose I, and Merenptah. Each mummy is displayed in an individual climate-controlled case with biographical information and CT scan results.",
        "has_image": True,
        "coordinates": {"lat": 30.0058, "lng": 31.2461},
        "tags": ["must-visit", "iconic"],
        "related_sites": ["egyptian_museum", "valley_of_the_kings"],
        "images": [],
        "sections": [
            {"title": "Pharaohs Golden Parade", "content": "On April 3, 2021, 22 royal mummies were transported from the Egyptian Museum to NMEC in a spectacular parade through Cairo, each in a custom nitrogen-filled capsule on a decorated chariot-style vehicle, accompanied by a 21-gun salute."},
            {"title": "Ramesses II", "content": "The mummy of Ramesses the Great (r. 1279–1213 BC), one of Egypt's most powerful pharaohs, showing he lived to approximately 90 years. His well-preserved remains reveal a tall man with red hair."},
            {"title": "Queen Hatshepsut", "content": "Egypt's most successful female pharaoh, identified through DNA testing and a matching tooth found in a canopic jar. She ruled for 21 years during the 18th Dynasty."},
        ],
    },
    {
        "slug": "nmec_main_exhibition",
        "name": "Main Exhibition Halls",
        "name_ar": "قاعات العرض الرئيسية",
        "category": "Museum",
        "subcategory": "Gallery",
        "region": "Cairo",
        "parent_slug": "nmec",
        "period": "Prehistoric to Modern",
        "featured": False,
        "description": "Spanning all of Egyptian civilization from prehistory to the present day — not just the pharaonic era but Coptic, Islamic, and modern Egypt too. The chronological galleries trace 50,000+ years of culture through artifacts, multimedia displays, and interactive installations. Highlights include prehistoric tools, Roman-era Fayoum mummy portraits, Coptic textiles, Islamic calligraphy, and modern Egyptian art.",
        "has_image": True,
        "coordinates": {"lat": 30.0058, "lng": 31.2461},
        "tags": ["indoor"],
        "related_sites": ["egyptian_museum"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "nmec_textile_gallery",
        "name": "Textile Gallery",
        "name_ar": "قاعة المنسوجات",
        "category": "Museum",
        "subcategory": "Gallery",
        "region": "Cairo",
        "parent_slug": "nmec",
        "period": "Various periods",
        "featured": False,
        "description": "A specialized gallery showcasing Egypt's remarkable textile heritage — from ancient linen wrappings and Coptic tapestries (some of the finest surviving late-antique textiles) to Islamic embroidery and modern weaving traditions. The collection demonstrates how textile art evolved continuously through every era of Egyptian civilization.",
        "has_image": True,
        "coordinates": {"lat": 30.0058, "lng": 31.2461},
        "tags": ["art", "off-the-beaten-path"],
        "related_sites": [],
        "images": [],
        "sections": [],
    },
]


BIBLIOTHECA_CHILDREN = [
    {
        "slug": "bibliotheca_main_library",
        "name": "Main Reading Hall",
        "name_ar": "قاعة القراءة الرئيسية",
        "category": "Modern",
        "subcategory": "Library",
        "region": "Alexandria",
        "parent_slug": "bibliotheca_alexandrina",
        "period": "Opened 2002",
        "featured": True,
        "description": "The centerpiece of the Bibliotheca — a spectacular 11-story cascading reading room tilted toward the Mediterranean, covering 70,000 square meters with space for 8 million books and 2,000 readers. The circular design references the ancient Egyptian sun disk descending into the sea. The exterior granite wall is carved with characters from 120 different human scripts — a monument to human knowledge. Designed by Norwegian architecture firm Snohetta, it is one of the most striking modern buildings in the Middle East.",
        "has_image": True,
        "coordinates": {"lat": 31.2089, "lng": 29.9092},
        "tags": ["must-visit", "architecture", "iconic"],
        "related_sites": [],
        "images": [],
        "sections": [
            {"title": "The Cascading Design", "content": "The reading room cascades across 11 levels beneath a massive 160-meter-diameter glass-paneled roof, tilted toward the Mediterranean — symbolizing the ancient sun disk Ra descending into the sea, representing knowledge enlightening the world."},
            {"title": "The Script Wall", "content": "The exterior Aswan granite wall is engraved with characters from 120 different writing systems from around the world — from Egyptian hieroglyphs to modern scripts — celebrating the universality of human knowledge."},
        ],
    },
    {
        "slug": "bibliotheca_planetarium",
        "name": "Planetarium Science Center",
        "name_ar": "القبة السماوية ومركز العلوم",
        "category": "Modern",
        "subcategory": "Science",
        "region": "Alexandria",
        "parent_slug": "bibliotheca_alexandrina",
        "period": "Opened 2002",
        "featured": False,
        "description": "A state-of-the-art planetarium and science center with an IMAX theater, connecting to the ancient Alexandrian tradition of astronomy and scientific inquiry. Features shows on the cosmos, ancient Egyptian astronomy, and interactive science exhibits. The tilted spherical dome is a striking architectural element reflecting the library's commitment to continuing Alexandria's scientific heritage.",
        "has_image": True,
        "coordinates": {"lat": 31.2089, "lng": 29.9092},
        "tags": ["family-friendly", "science"],
        "related_sites": [],
        "images": [],
        "sections": [],
    },
    {
        "slug": "bibliotheca_antiquities_museum",
        "name": "Antiquities Museum",
        "name_ar": "متحف الآثار",
        "category": "Museum",
        "subcategory": "Specialized Museums",
        "region": "Alexandria",
        "parent_slug": "bibliotheca_alexandrina",
        "period": "Various periods",
        "featured": False,
        "description": "A museum within the library complex housing artifacts recovered from underwater excavations in Alexandria's Eastern Harbor and from archaeological sites across Egypt. Highlights include Ptolemaic-era sculptures, ancient coins, Greco-Roman glassware, and pieces from the submerged palace of Cleopatra. Connects visitors to Alexandria's role as the Hellenistic world's cultural capital.",
        "has_image": True,
        "coordinates": {"lat": 31.2089, "lng": 29.9092},
        "tags": ["indoor"],
        "related_sites": ["catacombs_of_kom_el_shoqafa", "alexandria_national_museum"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "bibliotheca_manuscripts_museum",
        "name": "Manuscripts Museum",
        "name_ar": "متحف المخطوطات",
        "category": "Museum",
        "subcategory": "Specialized Museums",
        "region": "Alexandria",
        "parent_slug": "bibliotheca_alexandrina",
        "period": "Islamic & Medieval",
        "featured": False,
        "description": "A museum preserving rare Arabic and Islamic manuscripts, maps, and historical documents. The collection includes beautifully illuminated Quran manuscripts, medieval scientific treatises, historical maps of Egypt, and documents tracing the intellectual heritage of the Islamic world. Connects to the library's mission of preserving knowledge across civilizations.",
        "has_image": True,
        "coordinates": {"lat": 31.2089, "lng": 29.9092},
        "tags": ["off-the-beaten-path", "art"],
        "related_sites": ["museum_of_islamic_art"],
        "images": [],
        "sections": [],
    },
]


KHAN_EL_KHALILI_CHILDREN = [
    {
        "slug": "khan_el_khalili_bazaar",
        "name": "Historic Bazaar & Souqs",
        "name_ar": "البازار التاريخي والأسواق",
        "category": "Islamic",
        "subcategory": "Market",
        "region": "Cairo",
        "parent_slug": "khan_el_khalili",
        "period": "Mamluk (established 1382)",
        "featured": True,
        "description": "One of the oldest and largest bazaars in the Middle East, founded by Mamluk Emir Djaharks el-Khalili in 1382. A labyrinth of narrow alleys packed with shops selling gold and silver jewelry, brass and copperware, spices, perfumes, papyrus, alabaster, leather goods, and traditional handicrafts. The architecture preserves Mamluk-era caravanserais (merchants' inns) and wakalahs (trade buildings). Bargaining is expected and part of the experience.",
        "has_image": True,
        "coordinates": {"lat": 30.0477, "lng": 31.2626},
        "tags": ["must-visit", "shopping", "cultural"],
        "related_sites": ["al_muizz_street"],
        "images": [],
        "sections": [
            {"title": "Gold & Silver Souq", "content": "A dedicated alley of goldsmiths and jewelers selling exquisite handcrafted pieces — from traditional Egyptian cartouche pendants to modern designs. Gold is sold by weight plus craftsmanship."},
            {"title": "Spice Souq", "content": "Aromatic stalls piled high with saffron, cumin, hibiscus, dried roses, and Egyptian-blend spice mixes. Many shops also sell traditional herbal remedies and Egyptian perfume oils."},
        ],
    },
    {
        "slug": "khan_el_khalili_fishawi",
        "name": "El Fishawi Coffee House",
        "name_ar": "مقهى الفيشاوي",
        "category": "Islamic",
        "subcategory": "Historic Café",
        "region": "Cairo",
        "parent_slug": "khan_el_khalili",
        "period": "Ottoman (established 1797)",
        "featured": False,
        "description": "The most famous coffeehouse in Cairo, operating continuously since 1797 — over 225 years. Located in the heart of Khan El Khalili, it has hosted writers, artists, politicians, and tourists including Nobel laureate Naguib Mahfouz, who used it as a setting in his Cairo Trilogy. Ornate mirrors, brass tables, and traditional shisha pipes create an atmosphere unchanged for centuries. Open 24 hours.",
        "has_image": True,
        "coordinates": {"lat": 30.0477, "lng": 31.2626},
        "tags": ["cultural", "unique"],
        "related_sites": [],
        "images": [],
        "sections": [],
    },
]


"""Abydos Temple & St. Catherine's Monastery — sub-sites."""

ABYDOS_CHILDREN = [
    {
        "slug": "abydos_king_list",
        "name": "King List Hall (Gallery of Lists)",
        "name_ar": "قاعة قائمة الملوك",
        "category": "Pharaonic",
        "subcategory": "Temples",
        "region": "Sohag",
        "parent_slug": "abydos_temple",
        "period": "New Kingdom (19th Dynasty, c. 1280 BC)",
        "featured": True,
        "description": "One of the most historically important rooms in all of Egypt — a corridor containing the 'Abydos King List', a chronological list of 76 cartouches naming every pharaoh from Menes (first pharaoh, c. 3100 BC) to Seti I, carved in raised relief. Seti I and his young son (the future Ramesses II) are shown making offerings to their royal ancestors. Notably omits controversial rulers like Hatshepsut, Akhenaten, and Tutankhamun. This was a crucial tool for Egyptologists reconstructing the sequence of pharaohs.",
        "has_image": True,
        "coordinates": {"lat": 26.1850, "lng": 31.9190},
        "tags": ["must-visit", "iconic", "historic"],
        "related_sites": ["karnak_temple", "egyptian_museum"],
        "images": [],
        "sections": [
            {"title": "76 Royal Cartouches", "content": "The king list names pharaohs from Menes to Seti I in careful sequence. Originally a religious offering list, it became an invaluable historical document. The omission of Hatshepsut, Akhenaten, and the Amarna kings reveals ancient political editing of history."},
            {"title": "Seti I & Ramesses II", "content": "A touching relief shows Seti I with his young son (future Ramesses the Great) reading the names of their ancestors — making this both a religious ritual and a father-son teaching moment immortalized in stone."},
        ],
    },
    {
        "slug": "abydos_osireion",
        "name": "The Osireion",
        "name_ar": "الأوسريون",
        "category": "Pharaonic",
        "subcategory": "Temples",
        "region": "Sohag",
        "parent_slug": "abydos_temple",
        "period": "New Kingdom (19th Dynasty)",
        "featured": True,
        "description": "A mysterious subterranean structure behind the main temple, built to resemble an Old Kingdom valley temple but dating to Seti I's reign. Constructed from massive granite and sandstone blocks, its central island hall once surrounded by water — symbolizing the primeval mound of creation and the mythological tomb of Osiris. Contains the only known complete copy of the 'Book of Gates' and 'Book of the Dead' astronomical texts on its walls.",
        "has_image": True,
        "coordinates": {"lat": 26.1850, "lng": 31.9190},
        "tags": ["unique", "mysterious"],
        "related_sites": [],
        "images": [],
        "sections": [],
    },
    {
        "slug": "abydos_seven_chapels",
        "name": "Seven Chapels of the Gods",
        "name_ar": "المعابد السبعة",
        "category": "Pharaonic",
        "subcategory": "Temples",
        "region": "Sohag",
        "parent_slug": "abydos_temple",
        "period": "New Kingdom (19th Dynasty)",
        "featured": False,
        "description": "Seven vaulted chapels at the rear of the temple, each dedicated to a different deity or deified pharaoh: Horus, Isis, Osiris, Amun-Ra, Ra-Horakhty, Ptah, and the deified Seti I himself. The Osiris chapel leads to a further suite of rooms dedicated to the Osiris mysteries. The reliefs here are among the finest in all of Egyptian art — delicately carved in low relief with exquisite detail, many still retaining original pigment.",
        "has_image": True,
        "coordinates": {"lat": 26.1850, "lng": 31.9190},
        "tags": ["art"],
        "related_sites": ["karnak_temple"],
        "images": [],
        "sections": [],
    },
]


ST_CATHERINE_CHILDREN = [
    {
        "slug": "st_catherine_basilica",
        "name": "Basilica of the Transfiguration",
        "name_ar": "كاتدرائية التجلي",
        "category": "Coptic",
        "subcategory": "Church",
        "region": "South Sinai",
        "parent_slug": "saint_catherine_monastery",
        "period": "Byzantine (built 548–565 AD)",
        "featured": True,
        "description": "The main church of the monastery, built by order of Emperor Justinian I between 548 and 565 AD, making it one of the oldest continuously functioning churches in the world. Contains stunning 6th-century mosaic of the Transfiguration of Christ in the apse — one of the finest surviving Byzantine mosaics. The carved wooden doors and marble columns are original from the 6th century. Houses an extraordinary collection of icons spanning 1,500 years.",
        "has_image": True,
        "coordinates": {"lat": 28.5563, "lng": 33.9748},
        "tags": ["must-visit", "iconic", "art"],
        "related_sites": ["mount_sinai"],
        "images": [],
        "sections": [
            {"title": "Transfiguration Mosaic", "content": "The stunning 6th-century apse mosaic depicting Christ's Transfiguration on Mount Tabor — one of the oldest and finest Byzantine mosaics surviving anywhere in the world, with vivid gold, blue, and green tesserae."},
            {"title": "Icon Collection", "content": "The monastery holds the world's finest collection of early Christian icons, including rare encaustic (wax-painted) icons from the 6th century that survived the Byzantine Iconoclasm because the monastery's remote location placed it beyond the emperor's reach."},
        ],
    },
    {
        "slug": "st_catherine_burning_bush",
        "name": "Chapel of the Burning Bush",
        "name_ar": "كنيسة العليقة المشتعلة",
        "category": "Coptic",
        "subcategory": "Church",
        "region": "South Sinai",
        "parent_slug": "saint_catherine_monastery",
        "period": "Byzantine (4th century origin)",
        "featured": True,
        "description": "Located behind the apse of the main church, this small chapel is built over the spot where tradition holds the Burning Bush stood — from which God spoke to Moses. A living bush (Rubus sanctus) still grows beside the chapel and is venerated by visitors. The chapel floor has a silver plaque marking the sacred spot, and visitors must remove their shoes, recalling God's command to Moses. The site is sacred to Christians, Jews, and Muslims.",
        "has_image": True,
        "coordinates": {"lat": 28.5563, "lng": 33.9748},
        "tags": ["must-visit", "sacred"],
        "related_sites": ["mount_sinai"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "st_catherine_library",
        "name": "Sacred Library",
        "name_ar": "المكتبة المقدسة",
        "category": "Coptic",
        "subcategory": "Library",
        "region": "South Sinai",
        "parent_slug": "saint_catherine_monastery",
        "period": "Various (4th century onwards)",
        "featured": False,
        "description": "The second most important collection of early manuscripts in the world after the Vatican Library. Contains over 3,300 manuscripts in Greek, Arabic, Syriac, Georgian, Ethiopic, and other languages. The most famous manuscript found here was the Codex Sinaiticus (4th century) — one of the oldest nearly complete copies of the Bible, now in the British Library. The Syriac Sinaiticus palimpsest and the Ashtiname of Muhammad (letter of protection) are among its treasures.",
        "has_image": True,
        "coordinates": {"lat": 28.5563, "lng": 33.9748},
        "tags": ["historic", "unique"],
        "related_sites": ["bibliotheca_alexandrina"],
        "images": [],
        "sections": [
            {"title": "Codex Sinaiticus", "content": "A 4th-century Greek manuscript of the Bible — one of the four great uncial codices, discovered in the monastery in 1844 by Tischendorf. The original is now split between the British Library, Leipzig University, and the monastery itself."},
            {"title": "The Ashtiname of Muhammad", "content": "A letter attributed to Prophet Muhammad granting protection to the monastery and its monks. Whether authentic or not, it was honored by successive Muslim rulers and ensured the monastery's survival for over 1,400 years."},
        ],
    },
    {
        "slug": "st_catherine_charnel_house",
        "name": "Charnel House (Ossuary)",
        "name_ar": "بيت العظام",
        "category": "Coptic",
        "subcategory": "Historic Site",
        "region": "South Sinai",
        "parent_slug": "saint_catherine_monastery",
        "period": "Various periods",
        "featured": False,
        "description": "Due to limited burial space, the monks' bones are exhumed after a period and placed in this ossuary. Skulls and bones are neatly stacked in separate chambers. At the entrance sits the fully robed skeleton of Stephanos, a 6th-century guardian of the path to Mount Sinai. A sobering and unique aspect of monastic life in this remote desert setting.",
        "has_image": True,
        "coordinates": {"lat": 28.5563, "lng": 33.9748},
        "tags": ["unique", "off-the-beaten-path"],
        "related_sites": [],
        "images": [],
        "sections": [],
    },
]
