"""Dahshur & Memphis — sub-sites."""

DAHSHUR_CHILDREN = [
    {
        "slug": "dahshur_bent_pyramid",
        "name": "Bent Pyramid of Sneferu",
        "name_ar": "الهرم المنحني لسنفرو",
        "category": "Pharaonic",
        "subcategory": "Pyramids & Necropolises",
        "region": "Giza",
        "parent_slug": "dahshur_necropolis",
        "period": "Old Kingdom (4th Dynasty, c. 2600 BC)",
        "featured": True,
        "description": "The world's best-preserved pyramid, still retaining most of its original Tura limestone casing. Its distinctive shape — the angle changes from 54° to 43° partway up — reveals a mid-construction crisis when engineers feared collapse. This 'mistake' created one of Egypt's most recognizable silhouettes and provides crucial evidence of pyramid-building evolution.",
        "has_image": True,
        "coordinates": {"lat": 29.7903, "lng": 31.2094},
        "tags": ["must-visit", "iconic", "UNESCO", "off-the-beaten-path"],
        "related_sites": ["dahshur", "dahshur_red_pyramid"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "dahshur_red_pyramid",
        "name": "Red Pyramid of Sneferu",
        "name_ar": "الهرم الأحمر لسنفرو",
        "category": "Pharaonic",
        "subcategory": "Pyramids & Necropolises",
        "region": "Giza",
        "parent_slug": "dahshur_necropolis",
        "period": "Old Kingdom (4th Dynasty, c. 2590 BC)",
        "featured": True,
        "description": "Egypt's first successful true pyramid and the third-largest ever built (105 meters). Named for the reddish hue of its limestone core blocks. Visitors can descend a 63-meter passage (at a steep angle) to reach three impressive corbelled chambers deep inside. Often empty of other tourists — an intimate pyramid experience impossible at Giza.",
        "has_image": True,
        "coordinates": {"lat": 29.8092, "lng": 31.2061},
        "tags": ["must-visit", "underground", "off-the-beaten-path"],
        "related_sites": ["dahshur", "dahshur_bent_pyramid"],
        "images": [],
        "sections": [],
    },
]


MEMPHIS_CHILDREN = [
    {
        "slug": "memphis_colossus_ramesses",
        "name": "Colossus of Ramesses II",
        "name_ar": "تمثال رمسيس الثاني العملاق",
        "category": "Pharaonic",
        "subcategory": "Monuments & Statues",
        "region": "Giza",
        "parent_slug": "memphis_ruins",
        "period": "New Kingdom (19th Dynasty)",
        "featured": True,
        "description": "A 10-meter limestone statue of Ramesses II lying in a purpose-built indoor museum. Originally 13 meters tall (the lower legs are missing), it was found in 1820 by Giovanni Caviglia. Visitors view it from a raised gallery, appreciating the extraordinary detail — from the pharaoh's nemes headdress to individual fingers. A twin statue once stood here; it's now in front of the Grand Egyptian Museum.",
        "has_image": True,
        "coordinates": {"lat": 29.8488, "lng": 31.2552},
        "tags": ["must-visit", "iconic"],
        "related_sites": ["memphis_open_air_museum", "grand_egyptian_museum"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "memphis_alabaster_sphinx",
        "name": "Alabaster Sphinx",
        "name_ar": "أبو الهول المرمري",
        "category": "Pharaonic",
        "subcategory": "Monuments & Statues",
        "region": "Giza",
        "parent_slug": "memphis_ruins",
        "period": "New Kingdom (18th Dynasty, c. 1400 BC)",
        "featured": False,
        "description": "An 8-meter, 80-ton calcite alabaster sphinx — the largest alabaster statue ever found in Egypt. Believed to represent Hatshepsut or Amenhotep II. Unlike its Giza counterpart, this sphinx is unweathered and beautifully preserved, gleaming white in the sun at the Memphis open-air museum.",
        "has_image": True,
        "coordinates": {"lat": 29.8490, "lng": 31.2548},
        "tags": ["photography"],
        "related_sites": ["memphis_open_air_museum"],
        "images": [],
        "sections": [],
    },
]
