"""Egyptian Museum (Tahrir) — sub-sites and sections.

The original Egyptian Museum on Tahrir Square, opened in 1902. Though many
artifacts have been transferred to GEM and NMEC, it still houses thousands
of important pieces and remains a major attraction.
"""

EGYPTIAN_MUSEUM_CHILDREN = [
    {
        "slug": "em_tutankhamun_room",
        "name": "Tutankhamun Room (Historical Display)",
        "name_ar": "قاعة توت عنخ آمون",
        "category": "Museum",
        "subcategory": "Gallery",
        "region": "Cairo",
        "parent_slug": "egyptian_museum",
        "period": "New Kingdom",
        "featured": True,
        "description": "The museum's most famous room historically displayed the golden mask and treasures of Tutankhamun for nearly a century. While the main collection has transferred to the GEM, select pieces and the room's historical significance remain. Archival displays tell the story of Howard Carter's 1922 discovery.",
        "has_image": True,
        "coordinates": {"lat": 30.0478, "lng": 31.2336},
        "tags": ["historic", "iconic"],
        "related_sites": ["gem_tutankhamun_galleries", "tomb_of_tutankhamun"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "em_amarna_gallery",
        "name": "Amarna Gallery",
        "name_ar": "قاعة العمارنة",
        "category": "Museum",
        "subcategory": "Gallery",
        "region": "Cairo",
        "parent_slug": "egyptian_museum",
        "period": "New Kingdom (18th Dynasty, Amarna Period)",
        "featured": False,
        "description": "Art from the revolutionary Amarna Period of Akhenaten — including colossal statues of the 'heretic pharaoh' with his distinctive elongated features, boundary stelae from Tell el-Amarna, and examples of the naturalistic Amarna art style that broke 2,000 years of artistic convention.",
        "has_image": True,
        "coordinates": {"lat": 30.0478, "lng": 31.2336},
        "tags": ["art", "historic"],
        "related_sites": ["tell_el_amarna"],
        "images": [],
        "sections": [
            {"title": "Colossal Akhenaten", "content": "Massive sandstone statues from Karnak showing Akhenaten's distinctive features — elongated face, full lips, narrow eyes — reflecting the new religious art of the Aten."},
            {"title": "Nefertiti Pieces", "content": "Although the famous bust is in Berlin, unfinished sculptor's models and reliefs of Nefertiti remain, showing her iconic beauty."},
        ],
    },
    {
        "slug": "em_narmer_palette",
        "name": "Narmer Palette & Early Dynastic",
        "name_ar": "لوحة نارمر والأسرات المبكرة",
        "category": "Museum",
        "subcategory": "Gallery",
        "region": "Cairo",
        "parent_slug": "egyptian_museum",
        "period": "Early Dynastic (c. 3100 BC)",
        "featured": True,
        "description": "Home to the Narmer Palette — one of the oldest historical documents in the world, depicting the unification of Upper & Lower Egypt around 3100 BC. Also includes the Scorpion Macehead, ivory knife handles from Abydos, and other Pre-Dynastic artifacts that mark the birth of pharaonic civilization.",
        "has_image": True,
        "coordinates": {"lat": 30.0478, "lng": 31.2336},
        "tags": ["must-visit", "historic", "iconic"],
        "related_sites": ["abydos_temple"],
        "images": [],
        "sections": [
            {"title": "The Narmer Palette", "content": "A 64 cm ceremonial slate palette showing King Narmer wearing both the White Crown of Upper Egypt and Red Crown of Lower Egypt — symbolizing the first unification around 3100 BC."},
            {"title": "Scorpion Macehead", "content": "A limestone macehead depicting King Scorpion performing an irrigation ceremony, pre-dating the unification."},
        ],
    },
    {
        "slug": "em_animal_mummies",
        "name": "Animal Mummies Gallery",
        "name_ar": "قاعة مومياوات الحيوانات",
        "category": "Museum",
        "subcategory": "Gallery",
        "region": "Cairo",
        "parent_slug": "egyptian_museum",
        "period": "Various periods",
        "featured": False,
        "description": "A fascinating collection of mummified sacred animals — cats, ibises, crocodiles, baboons, rams, and falcons. Ancient Egyptians mummified millions of animals as votive offerings to their gods. The gallery explains the intersection of religion, veterinary science, and the massive temple animal-breeding industry.",
        "has_image": True,
        "coordinates": {"lat": 30.0478, "lng": 31.2336},
        "tags": ["unique", "family-friendly"],
        "related_sites": ["bubastis", "serapeum_of_saqqara"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "em_royal_jewelry",
        "name": "Middle Kingdom Jewelry",
        "name_ar": "مجوهرات الدولة الوسطى",
        "category": "Museum",
        "subcategory": "Gallery",
        "region": "Cairo",
        "parent_slug": "egyptian_museum",
        "period": "Middle Kingdom (2055–1650 BC)",
        "featured": False,
        "description": "Exquisite royal jewelry from Middle Kingdom princesses, particularly the Dahshur and Lahun treasures — including golden diadems, broad collars inlaid with turquoise and carnelian, and pectoral ornaments with falcon and scarab motifs. Widely considered the finest jewelry of the ancient world.",
        "has_image": True,
        "coordinates": {"lat": 30.0478, "lng": 31.2336},
        "tags": ["gold", "art"],
        "related_sites": ["lahun_pyramid", "dahshur_necropolis"],
        "images": [],
        "sections": [],
    },
]
