# Egyptian Experiences & Activities
SITES = [
    {"slug": "nile_cruise", "name": "Nile Cruise (Luxor to Aswan)", "name_ar": "رحلة نيلية",
     "category": "Modern", "subcategory": "Experiences", "region": "Upper Egypt",
     "period": "",
     "description": "The quintessential Egyptian experience — a multi-day cruise along the Nile between Luxor and Aswan (or vice versa), tracing the route of pharaohs and Victorian-era explorers. Most cruises span 3-7 nights, stopping at Edfu Temple, Kom Ombo Temple, and the Esna Lock along the way. Passengers wake to ever-changing riverscapes of palm-fringed banks, feluccas gliding past, and ancient temples emerging from the horizon. Options range from luxurious 5-star floating hotels to traditional dahabiyas (wooden sailing boats). The journey offers a unique perspective on rural Egyptian life along the fertile Nile Valley.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 25.2000, "lng": 32.9000},
     "tags": ["must-visit", "unique", "scenic", "photography"], "related_sites": ["luxor_temple", "edfu_temple", "kom_ombo_temple"]},

    {"slug": "hot_air_balloon_luxor", "name": "Hot Air Balloon over Luxor", "name_ar": "منطاد الأقصر",
     "category": "Modern", "subcategory": "Experiences", "region": "Luxor",
     "period": "",
     "description": "One of the world's most breathtaking aerial experiences — floating over the Valley of the Kings, Temple of Hatshepsut, Medinet Habu, the Ramesseum, and the Colossi of Memnon at sunrise. Balloons launch from the west bank of the Nile at dawn, rising to 300-500 meters for panoramic views of the patchwork of green sugarcane fields, desert mountains, and 3,500-year-old temples bathed in golden morning light. The contrast between the lush Nile Valley and the barren Theban Hills is unforgettable. Approximately 30 balloons operate daily in season, carrying thousands of visitors each year.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 25.7280, "lng": 32.6003},
     "tags": ["must-visit", "unique", "photography", "scenic"], "related_sites": ["valley_of_the_kings", "temple_of_hatshepsut", "medinet_habu"]},

    {"slug": "sound_and_light_pyramids", "name": "Sound & Light Show at Giza Pyramids", "name_ar": "عرض الصوت والضوء بالأهرامات",
     "category": "Modern", "subcategory": "Experiences", "region": "Giza",
     "period": "Running since 1961",
     "description": "A spectacular nighttime show at the foot of the Great Pyramids and Sphinx, where dramatic laser projections, colored lights, and narration bring 5,000 years of history to life. The Sphinx itself serves as the narrator, telling the story of the pharaohs who built the pyramids. The show runs in multiple languages and lasts about 45 minutes. Sitting in the desert darkness as the pyramids are illuminated in shifting colors against the night sky is a magical experience that has captivated audiences since 1961.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.9753, "lng": 31.1376},
     "tags": ["must-visit", "family-friendly", "night"], "related_sites": ["great_pyramids_of_giza", "great_sphinx_of_giza"]},

    {"slug": "sound_and_light_karnak", "name": "Sound & Light Show at Karnak", "name_ar": "عرض الصوت والضوء بالكرنك",
     "category": "Modern", "subcategory": "Experiences", "region": "Luxor",
     "period": "",
     "description": "An immersive nighttime spectacle walking through the illuminated Karnak Temple complex. Unlike the seated Giza show, Karnak's Sound & Light leads visitors on a guided walking tour through the dramatically lit colonnades, obelisks, and the Great Hypostyle Hall before gathering at the Sacred Lake for the finale. Ancient Egyptian gods and pharaohs speak through powerful narration as light transforms the massive stone columns into a living tapestry of history. The reflections on the Sacred Lake create an especially atmospheric ending.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 25.7188, "lng": 32.6573},
     "tags": ["family-friendly", "night", "unique"], "related_sites": ["karnak_temple", "luxor_temple"]},

    {"slug": "nubian_village", "name": "Nubian Village (Aswan)", "name_ar": "القرية النوبية",
     "category": "Modern", "subcategory": "Experiences", "region": "Aswan",
     "period": "",
     "description": "Colorful Nubian villages on the west bank of the Nile and Elephantine Island near Aswan, where visitors can experience the vibrant culture of the Nubian people. The villages feature vividly painted houses in blues, yellows, and oranges adorned with Nubian symbols, friendly crocodile pets, traditional handicrafts, and warm hospitality. Visitors enjoy henna painting, Nubian tea and cuisine, traditional music, and shopping for handmade jewelry and crafts. The boat ride along the Nile to reach the villages is part of the experience, offering views of sand dunes, palm groves, and ancient rock inscriptions.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 24.0917, "lng": 32.8833},
     "tags": ["must-visit", "unique", "cultural", "photography"], "related_sites": ["elephantine_island", "nubia_museum"]},

    {"slug": "felucca_ride_aswan", "name": "Felucca Ride (Aswan)", "name_ar": "ركوب الفلوكة",
     "category": "Modern", "subcategory": "Experiences", "region": "Aswan",
     "period": "",
     "description": "A traditional wooden sailboat ride on the Nile at Aswan — one of Egypt's most peaceful and scenic experiences. Feluccas have sailed the Nile for thousands of years, and riding one at sunset around Elephantine Island, Kitchener's Botanical Garden, and past the Aga Khan Mausoleum with the sand dunes as backdrop is quintessentially Egyptian. The gentle wind, lapping water, and calls of birds create a timeless atmosphere. Multi-day felucca journeys from Aswan to Edfu (2-3 days) are popular for adventure travelers, sleeping on the boat deck under the stars.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 24.0889, "lng": 32.8997},
     "tags": ["must-visit", "scenic", "unique", "photography"], "related_sites": ["elephantine_island", "kitchener_island_aswan", "aga_khan_mausoleum"]},
]
