"""Grand Egyptian Museum (GEM) — sub-sites and sections.

Inaugurated November 1, 2025 near the Pyramids of Giza. The world's largest
archaeological museum dedicated to a single civilization, housing 100,000+
artifacts across 500,000 m² at a cost of $1.2 billion. Designed by Heneghan
Peng Architects (Ireland). Received 18,000 visitors on its first public day.
"""

GEM_CHILDREN = [
    {
        "slug": "gem_grand_hall",
        "name": "Grand Hall (Atrium)",
        "name_ar": "القاعة الكبرى",
        "category": "Museum",
        "subcategory": "Gallery",
        "region": "Giza",
        "parent_slug": "grand_egyptian_museum",
        "period": "Various periods",
        "featured": True,
        "description": "The spectacular main entrance hall spanning 10,000 square meters with a glass roof and transparent facade offering views of the Giza Pyramids from inside. Dominated by the 11-meter, 83-ton red granite colossus of Ramesses II — moved from Memphis via Ramses Square in 2006 — alongside 20-30 monumental artifacts from different eras serving as an introductory exhibition to pharaonic civilization.",
        "has_image": True,
        "coordinates": {"lat": 29.9950, "lng": 31.1193},
        "tags": ["must-visit", "iconic", "architecture"],
        "related_sites": ["memphis_ruins", "great_pyramids_of_giza"],
        "images": [],
        "sections": [
            {"title": "Ramesses II Colossus", "content": "This 83-ton, 11-meter red granite statue was discovered in 1820 at Mit Rahina (ancient Memphis). It stood in Ramses Square, Cairo for decades before careful relocation to the GEM in 2006, where it was placed in the Grand Hall in 2018."},
            {"title": "Glass Facade & Pyramid Views", "content": "The building's design by Heneghan Peng Architects creates a chamfered triangle shape, with north and south walls aligned directly to the Great Pyramid of Khufu and the Pyramid of Menkaure. The translucent alabaster stone facade is decorated with cartouches bearing hieroglyphic names of kings and queens."},
            {"title": "Monumental Artifacts", "content": "The atrium displays 20-30 large-scale artifacts from different eras, creating a chronological introduction to Egyptian civilization for visitors before they enter the main galleries."},
        ],
    },
    {
        "slug": "gem_grand_staircase",
        "name": "Grand Staircase",
        "name_ar": "الدرج الكبير",
        "category": "Museum",
        "subcategory": "Gallery",
        "region": "Giza",
        "parent_slug": "grand_egyptian_museum",
        "period": "Various periods",
        "featured": True,
        "description": "A monumental transitional gallery spanning 6,000 square meters and six stories (approximately 50 meters high), connecting the main atrium to the 12 exhibition halls via the upper terrace. Displays over 60 artifacts arranged in four thematic sections — Royal Image, Divine Houses, Gods & Kings, and Funerary — creating a chronological journey through pharaonic civilization with another stunning view of the Giza Pyramids.",
        "has_image": True,
        "coordinates": {"lat": 29.9950, "lng": 31.1193},
        "tags": ["must-visit", "iconic"],
        "related_sites": ["gem_grand_hall", "gem_main_galleries"],
        "images": [],
        "sections": [
            {"title": "Royal Image", "content": "The first thematic section focuses on how and why pharaohs portrayed themselves, featuring royal statues spanning all periods of Egyptian history."},
            {"title": "Divine Houses", "content": "Explores temples and the relationship between gods and pharaohs, with religious artwork and architectural fragments from major temple complexes."},
            {"title": "Gods & Kings", "content": "Examines ancient Egyptian deities and their association with rulers, including divine statuary and votive objects."},
            {"title": "Funerary Section", "content": "Displays stone coffins and sarcophagi from various eras, including a pyramid-shaped capstone (pyramidion) from the 13th Dynasty, illustrating evolving burial practices."},
        ],
    },
    {
        "slug": "gem_tutankhamun_galleries",
        "name": "Tutankhamun Galleries",
        "name_ar": "قاعات توت عنخ آمون",
        "category": "Museum",
        "subcategory": "Gallery",
        "region": "Giza",
        "parent_slug": "grand_egyptian_museum",
        "period": "New Kingdom (18th Dynasty)",
        "featured": True,
        "description": "The crown jewel of the GEM — two dedicated halls covering 7,000 square meters housing the complete 5,398-piece Tutankhamun collection, displayed together for the first time ever. Previously only a fraction was shown at the Egyptian Museum in Tahrir. The halls are designed to evoke the original tomb in the Valley of the Kings, with environmental controls protecting sensitive gold, wood, and fabric pieces.",
        "has_image": True,
        "coordinates": {"lat": 29.9950, "lng": 31.1193},
        "tags": ["must-visit", "iconic", "gold"],
        "related_sites": ["tomb_of_tutankhamun", "egyptian_museum", "valley_of_the_kings"],
        "images": [],
        "sections": [
            {"title": "The Golden Mask", "content": "The iconic 11 kg solid gold death mask, inlaid with lapis lazuli, turquoise, and carnelian. Discovered by Howard Carter in 1925 within the innermost coffin. The central piece of the entire museum."},
            {"title": "The Nested Coffins", "content": "Three anthropoid coffins — the innermost made of 110 kg of solid gold, the two outer ones of gold-plated wood. The craftsmanship represents the peak of New Kingdom goldsmithing. Note: Tutankhamun's mummy itself remains in the Valley of the Kings."},
            {"title": "The Golden Throne", "content": "An ornate wooden throne overlaid with gold and silver, depicting Tutankhamun with his wife Ankhesenamun in the intimate Amarna art style inherited from Akhenaten's revolutionary period."},
            {"title": "Canopic Shrine & Jars", "content": "The elaborate gilded canopic shrine containing four miniature gold coffins that held the king's preserved organs, each guarded by a protective goddess."},
            {"title": "Royal Chariots & Weapons", "content": "Six chariots including ceremonial and military designs, plus daggers (one of meteoritic iron), bows, and other weapons — the first complete ancient Egyptian chariot collection ever discovered."},
            {"title": "Daily Life Objects", "content": "Furniture including beds and chairs, dining utensils, board games, and over 400 ushabti figurines meant to serve the king in the afterlife. These objects reveal intimate details of royal daily life 3,300 years ago."},
        ],
    },
    {
        "slug": "gem_main_galleries",
        "name": "Main Exhibition Galleries (12 Halls)",
        "name_ar": "قاعات العرض الرئيسية",
        "category": "Museum",
        "subcategory": "Gallery",
        "region": "Giza",
        "parent_slug": "grand_egyptian_museum",
        "period": "Prehistoric – Greco-Roman (c. 3100 BCE – 400 CE)",
        "featured": False,
        "description": "Twelve permanent galleries arranged chronologically, displaying over 24,000 artifacts spanning from prehistoric Egypt to the Greco-Roman period. Halls 1-3 cover the Prehistoric, Predynastic, Early Dynastic, and Old Kingdom eras. Halls 4-6 cover the Middle Kingdom and Second Intermediate Period. Halls 7-9 address the New Kingdom. Halls 10-12 cover the Third Intermediate Period, Late Period, and Greco-Roman era. Artifacts were relocated from museums in Cairo, Luxor, Minya, Sohag, Assiut, Beni Suef, Fayoum, the Nile Delta, and Alexandria.",
        "has_image": True,
        "coordinates": {"lat": 29.9950, "lng": 31.1193},
        "tags": ["historic"],
        "related_sites": ["egyptian_museum", "luxor_museum"],
        "images": [],
        "sections": [
            {"title": "Halls 1-3: Dawn of Civilization", "content": "Covering the Prehistoric, Predynastic, Early Dynastic, and Old Kingdom periods — including the Narmer Palette era, pyramid-builders' artifacts, the Diorite Statue of Khafre protected by Horus, and the Triad of Menkaure."},
            {"title": "Halls 4-6: Middle Kingdom", "content": "The Middle Kingdom and Second Intermediate Period, featuring literature, art, and material culture from Egypt's 'Classical Age' — elegant jewelry, coffin texts, and Middle Kingdom statuary."},
            {"title": "Halls 7-9: New Kingdom", "content": "Egypt's imperial golden age including Hatshepsut, Thutmose III, Akhenaten's Amarna revolution, and the Ramesside era — monumental statuary, temple reliefs, and everyday objects."},
            {"title": "Halls 10-12: Late & Greco-Roman", "content": "The Third Intermediate Period through Ptolemaic and Roman Egypt — featuring the blending of Egyptian and Hellenistic cultures, Fayoum portraits, and late temple art."},
        ],
    },
    {
        "slug": "gem_khufu_ships",
        "name": "Khufu Ships Museum",
        "name_ar": "متحف مراكب خوفو",
        "category": "Museum",
        "subcategory": "Gallery",
        "region": "Giza",
        "parent_slug": "grand_egyptian_museum",
        "period": "Old Kingdom (4th Dynasty)",
        "featured": False,
        "description": "A dedicated hall displaying the two 4,600-year-old solar boats of King Khufu — among the oldest wooden ships ever discovered. The first boat (43.6 meters, reconstructed from 1,224 cedar wood pieces found in a sealed pit at the Great Pyramid base in 1954) was transferred from its original museum at Giza in August 2021. Interactive displays explain their proposed purposes — perhaps to transport the king through the afterlife or for ritual journeys with the sun god Ra.",
        "has_image": True,
        "coordinates": {"lat": 29.9950, "lng": 31.1193},
        "tags": ["historic", "unique"],
        "related_sites": ["great_pyramids_of_giza"],
        "images": [],
        "sections": [
            {"title": "The First Solar Boat", "content": "Discovered in 1954 in a sealed limestone pit south of the Great Pyramid, this 43.6-meter cedar wood vessel was reassembled from 1,224 meticulously numbered pieces. It is one of the oldest, largest, and best-preserved vessels from antiquity."},
            {"title": "The Second Boat", "content": "A second disassembled boat discovered in an adjacent pit, excavated and conserved by a Japanese-Egyptian team. Both boats are now displayed together at the GEM for the first time."},
        ],
    },
    {
        "slug": "gem_childrens_museum",
        "name": "Children's Museum",
        "name_ar": "متحف الأطفال",
        "category": "Museum",
        "subcategory": "Gallery",
        "region": "Giza",
        "parent_slug": "grand_egyptian_museum",
        "period": "Modern",
        "featured": False,
        "description": "An interactive 5,000-square-meter space designed for children aged 6 to 12, emphasizing learning through play rather than traditional exhibits. Features interactive screens, augmented reality (AR) experiences, hands-on games, visual exhibits, and guided programs that bring ancient Egyptian history to life. Partially open since August 2024.",
        "has_image": True,
        "coordinates": {"lat": 29.9950, "lng": 31.1193},
        "tags": ["family-friendly"],
        "related_sites": [],
        "images": [],
        "sections": [],
    },
    {
        "slug": "gem_conservation_center",
        "name": "Conservation Center",
        "name_ar": "مركز الترميم",
        "category": "Museum",
        "subcategory": "Gallery",
        "region": "Giza",
        "parent_slug": "grand_egyptian_museum",
        "period": "Modern (established 2006, opened 2010)",
        "featured": False,
        "description": "One of the world's largest conservation and restoration centers and the largest center for the restoration of antiquities in the Middle East. Located west of the museum and connected via a 200-meter tunnel, it houses 19 specialized laboratories including those for the restoration of mummies, wood, stone, wall paintings, and metals, as well as preventive conservation and scientific documentation labs. Six climate-controlled storage rooms preserve artifacts under optimal conditions.",
        "has_image": True,
        "coordinates": {"lat": 29.9950, "lng": 31.1193},
        "tags": ["science", "off-the-beaten-path"],
        "related_sites": [],
        "images": [],
        "sections": [
            {"title": "19 Specialized Laboratories", "content": "Labs for mummy restoration, wood conservation, stone repair, wall painting restoration, metal conservation, preventive conservation, and scientific documentation — each with specialized equipment and climate control."},
            {"title": "Storage Facilities", "content": "Six storage rooms maintain artifacts in controlled environmental conditions — temperature, humidity, and light carefully regulated to preserve pieces spanning thousands of years."},
        ],
    },
    {
        "slug": "gem_temporary_exhibitions",
        "name": "Temporary Exhibition Halls",
        "name_ar": "قاعات المعارض المؤقتة",
        "category": "Museum",
        "subcategory": "Gallery",
        "region": "Giza",
        "parent_slug": "grand_egyptian_museum",
        "period": "Modern",
        "featured": False,
        "description": "Four dedicated halls covering 5,000 square meters for rotating temporary exhibitions and international loans, part of 32,000 square meters of non-permanent display space. These halls host special thematic exhibitions, traveling international collections, and temporary displays that complement the permanent galleries.",
        "has_image": True,
        "coordinates": {"lat": 29.9950, "lng": 31.1193},
        "tags": ["indoor"],
        "related_sites": [],
        "images": [],
        "sections": [],
    },
    {
        "slug": "gem_conference_center",
        "name": "Conference Center & 3D Theater",
        "name_ar": "مركز المؤتمرات والمسرح ثلاثي الأبعاد",
        "category": "Museum",
        "subcategory": "Gallery",
        "region": "Giza",
        "parent_slug": "grand_egyptian_museum",
        "period": "Modern",
        "featured": False,
        "description": "A 40,000-square-meter international hub for museums and cultural institutions, designed to host conferences, seminars, and educational events related to ancient Egyptian civilization. Features a 1,000-seat main auditorium, three 250-seat seminar halls, exhibition spaces, meeting rooms, a business center, press room, and a 250-seat 3D theater. The design is inspired by ancient pharaonic sites.",
        "has_image": True,
        "coordinates": {"lat": 29.9950, "lng": 31.1193},
        "tags": ["modern", "architecture"],
        "related_sites": [],
        "images": [],
        "sections": [],
    },
    {
        "slug": "gem_jewelry_collection",
        "name": "Royal Jewelry Collection",
        "name_ar": "مجموعة المجوهرات الملكية",
        "category": "Museum",
        "subcategory": "Gallery",
        "region": "Giza",
        "parent_slug": "grand_egyptian_museum",
        "period": "Various periods",
        "featured": False,
        "description": "Dazzling collection of royal and elite jewelry spanning all periods — golden pectorals of Tutankhamun, the Lahun treasure of Princess Sithathoryunet, diadems, amulets, necklaces, and bracelets demonstrating the extraordinary goldsmithing skills of ancient Egyptian artisans.",
        "has_image": True,
        "coordinates": {"lat": 29.9950, "lng": 31.1193},
        "tags": ["gold", "art"],
        "related_sites": ["lahun_pyramid"],
        "images": [],
        "sections": [],
    },
]
