"""Pyramids of Giza complex — sub-sites."""

GIZA_CHILDREN = [
    {
        "slug": "giza_great_pyramid",
        "name": "Great Pyramid of Khufu (Cheops)",
        "name_ar": "هرم خوفو الأكبر",
        "category": "Pharaonic",
        "subcategory": "Pyramids & Necropolises",
        "region": "Giza",
        "parent_slug": "great_pyramids_of_giza",
        "period": "Old Kingdom (4th Dynasty, c. 2560 BC)",
        "featured": True,
        "description": "The oldest and only surviving Wonder of the Ancient World. Originally 146.6 meters tall (now 138.5m), built from 2.3 million limestone blocks averaging 2.5 tons each. The internal King's Chamber contains a red granite sarcophagus. The precision of construction — sides aligned to true north within 3/60th of a degree — remains astonishing.",
        "has_image": True,
        "coordinates": {"lat": 29.9792, "lng": 31.1342},
        "tags": ["must-visit", "iconic", "Seven Wonders", "UNESCO"],
        "related_sites": ["great_pyramids_of_giza", "great_sphinx_of_giza"],
        "images": [],
        "sections": [
            {"title": "King's Chamber", "content": "The main burial chamber, constructed entirely of red granite from Aswan. Contains a lidless granite sarcophagus. Five 'relieving chambers' above distribute the immense weight."},
            {"title": "Queen's Chamber", "content": "A misnomer — likely a serdab (statue chamber). Features a corbelled niche in the east wall and two mysterious 'air shafts' that don't reach the exterior."},
            {"title": "Grand Gallery", "content": "A stunning 47-meter ascending corbelled passage, 8.6 meters high. Its precise construction and purpose — perhaps a counterweight mechanism — continues to be debated."},
        ],
    },
    {
        "slug": "giza_sphinx",
        "name": "Great Sphinx of Giza",
        "name_ar": "أبو الهول",
        "category": "Pharaonic",
        "subcategory": "Monuments & Statues",
        "region": "Giza",
        "parent_slug": "great_pyramids_of_giza",
        "period": "Old Kingdom (4th Dynasty, c. 2500 BC)",
        "featured": True,
        "description": "The largest monolithic statue in the world — a lion's body with a human head, carved directly from the limestone bedrock of the Giza plateau. Measures 73 meters long, 20 meters high, and 19 meters wide. Believed to represent Pharaoh Khafre, it has guarded the Giza necropolis for 4,500 years. The 'Dream Stele' between its paws tells of Thutmose IV's vision.",
        "has_image": True,
        "coordinates": {"lat": 29.9753, "lng": 31.1376},
        "tags": ["must-visit", "iconic"],
        "related_sites": ["great_pyramids_of_giza", "pyramid_of_khafre"],
        "images": [],
        "sections": [
            {"title": "The Missing Nose", "content": "Contrary to popular myth, Napoleon did not shoot off the Sphinx's nose. Historical evidence points to Muhammad Sa'im al-Dahr, a Sufi Muslim, who vandalized it in 1378 CE."},
            {"title": "Dream Stele", "content": "A granite stele erected between the Sphinx's paws by Thutmose IV (1401 BC), recording his dream that the Sphinx promised him the throne if he cleared the sand."},
        ],
    },
    {
        "slug": "giza_workers_village",
        "name": "Pyramid Builders' Village",
        "name_ar": "قرية بناة الأهرامات",
        "category": "Pharaonic",
        "subcategory": "Ancient Cities",
        "region": "Giza",
        "parent_slug": "great_pyramids_of_giza",
        "period": "Old Kingdom (4th Dynasty)",
        "featured": False,
        "description": "Discovered by Egyptologist Mark Lehner in 1999, this archaeological site south of the Sphinx reveals the lives of the pyramid builders — permanent workers (not slaves) who lived in organized barracks, ate well (cattle, fish, bread), and received medical care. Bakeries, breweries, and copper workshops have been excavated.",
        "has_image": True,
        "coordinates": {"lat": 29.9720, "lng": 31.1340},
        "tags": ["archaeological", "off-the-beaten-path"],
        "related_sites": ["great_pyramids_of_giza"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "giza_eastern_cemetery",
        "name": "Eastern Cemetery (Queens' Pyramids)",
        "name_ar": "الجبانة الشرقية (أهرامات الملكات)",
        "category": "Pharaonic",
        "subcategory": "Pyramids & Necropolises",
        "region": "Giza",
        "parent_slug": "great_pyramids_of_giza",
        "period": "Old Kingdom",
        "featured": False,
        "description": "A field of small satellite pyramids and mastaba tombs east of the Great Pyramid. Includes three queens' pyramids (Hetepheres I, Meritites I, Henutsen) and mastabas of royal family members and officials. The recently opened Tomb of Meresankh III contains remarkably preserved painted reliefs and rock-cut statues.",
        "has_image": True,
        "coordinates": {"lat": 29.9785, "lng": 31.1365},
        "tags": ["off-the-beaten-path", "underground"],
        "related_sites": ["great_pyramids_of_giza", "giza_great_pyramid"],
        "images": [],
        "sections": [],
    },
]
