# Greco-Roman Heritage
SITES = [
    {"slug": "bibliotheca_alexandrina", "name": "Bibliotheca Alexandrina", "name_ar": "مكتبة الإسكندرية",
     "category": "Greco-Roman", "subcategory": "Libraries & Learning", "region": "Alexandria",
     "period": "Modern (2002), on site of ancient Library",
     "description": "A modern revival of the ancient Library of Alexandria, featuring a stunning tilted-disc design and holding millions of books, museums, and planetarium.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 31.2089, "lng": 29.9092},
     "tags": ["must-visit"], "related_sites": ["citadel_of_qaitbay", "roman_amphitheatre_alexandria"]},

    {"slug": "catacombs_of_kom_el_shoqafa", "name": "Catacombs of Kom el-Shoqafa", "name_ar": "سراديب الموتى كوم الشقافة",
     "category": "Greco-Roman", "subcategory": "Tombs & Burial", "region": "Alexandria",
     "period": "Roman (1st-2nd Century AD)",
     "description": "A unique multi-level underground necropolis blending Egyptian, Greek, and Roman funerary art. One of the Seven Wonders of the Medieval World.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 31.1792, "lng": 29.8925},
     "tags": ["must-visit"], "related_sites": ["pompeys_pillar"]},

    {"slug": "pompeys_pillar", "name": "Pompey's Pillar", "name_ar": "عمود السواري",
     "category": "Greco-Roman", "subcategory": "Monuments", "region": "Alexandria",
     "period": "Roman (297 AD)",
     "description": "The tallest ancient monolithic column in the world (26.85m), erected for Emperor Diocletian on the ruins of the Serapeum of Alexandria.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 31.1797, "lng": 29.8931},
     "tags": ["must-visit"], "related_sites": ["catacombs_of_kom_el_shoqafa"]},

    {"slug": "roman_amphitheatre_alexandria", "name": "Roman Amphitheatre (Kom el-Dikka)", "name_ar": "المسرح الروماني",
     "category": "Greco-Roman", "subcategory": "Theaters", "region": "Alexandria",
     "period": "Roman (2nd Century AD)",
     "description": "The only Roman amphitheatre discovered in Egypt, with well-preserved marble seating, mosaic floors, and lecture halls of an ancient university.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 31.1939, "lng": 29.9014},
     "tags": ["cultural", "off-the-beaten-path"], "related_sites": ["bibliotheca_alexandrina"]},

    {"slug": "greco_roman_museum", "name": "Graeco-Roman Museum", "name_ar": "المتحف اليوناني الروماني",
     "category": "Greco-Roman", "subcategory": "Museums", "region": "Alexandria",
     "period": "Founded 1892",
     "description": "A museum housing 40,000+ artifacts from the Greco-Roman period in Egypt, including coins, statuary, and mummies, currently undergoing extensive renovation.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 31.1998, "lng": 29.9047},
     "tags": ["off-the-beaten-path"], "related_sites": ["bibliotheca_alexandrina"]},

    {"slug": "royal_jewelry_museum", "name": "Royal Jewelry Museum", "name_ar": "متحف المجوهرات الملكية",
     "category": "Greco-Roman", "subcategory": "Museums", "region": "Alexandria",
     "period": "Founded 1986 (palace from 1919)",
     "description": "Housed in a beautiful palace, displaying dazzling royal jewelry collection of Egypt's Mohamed Ali dynasty from the 19th and 20th centuries.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 31.2422, "lng": 29.9614},
     "tags": ["off-the-beaten-path"], "related_sites": ["bibliotheca_alexandrina"]},

    {"slug": "montaza_palace", "name": "Montaza Palace and Gardens", "name_ar": "قصر وحدائق المنتزه",
     "category": "Greco-Roman", "subcategory": "Palaces", "region": "Alexandria",
     "period": "Modern (1892)",
     "description": "A royal palace complex set in 370 acres of manicured gardens overlooking the Mediterranean, blending Turkish and Florentine architectural styles.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 31.2856, "lng": 30.0164},
     "tags": ["architecture", "historic", "must-visit", "photography"], "related_sites": ["bibliotheca_alexandrina"]},

    {"slug": "ras_el_tin_palace", "name": "Ras el-Tin Palace", "name_ar": "قصر رأس التين",
     "category": "Greco-Roman", "subcategory": "Palaces", "region": "Alexandria",
     "period": "Modern (1847)",
     "description": "One of Egypt's oldest surviving royal palaces, built by Muhammad Ali Pasha in 1847 on the tip of the peninsula where the Pharos Lighthouse once stood. The palace witnessed some of Egypt's most dramatic moments — it was here that King Farouk signed the abdication papers ending the Egyptian monarchy in 1952 before sailing into exile. The grand Ottoman-European architecture overlooks the Eastern Harbour of Alexandria and serves as an official presidential residence and Egyptian Navy headquarters.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 31.2133, "lng": 29.8717},
     "tags": ["architecture", "historic"], "related_sites": ["montaza_palace", "citadel_of_qaitbay"]},

    {"slug": "abu_mena", "name": "Abu Mena", "name_ar": "أبو مينا",
     "category": "Greco-Roman", "subcategory": "Archaeological Sites", "region": "Alexandria",
     "period": "Early Christian (3rd-7th century AD)",
     "description": "A UNESCO World Heritage Site — the ruins of the early Christian holy city built over the grave of Saint Menas, a 3rd-century Egyptian martyr. Once one of the greatest pilgrimage centers in the early Christian world, the site includes the remains of a great basilica, a baptistery, baths, and a monastery. Pilgrims came from across the Mediterranean seeking miraculous healing from the sacred waters. The characteristic two-handled flask (ampulla) with Saint Menas praying between two camels became one of the most widely distributed devotional objects in the ancient world.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.8500, "lng": 29.6700},
     "tags": ["UNESCO", "archaeological", "off-the-beaten-path"], "related_sites": ["wadi_el_natrun"]},
]
