"""Hatshepsut Temple (Deir el-Bahari) — sub-sites."""

HATSHEPSUT_CHILDREN = [
    {
        "slug": "hatshepsut_lower_terrace",
        "name": "Lower Terrace & Colonnade",
        "name_ar": "الشرفة السفلى",
        "category": "Pharaonic",
        "subcategory": "Temples",
        "region": "Luxor",
        "parent_slug": "temple_of_hatshepsut",
        "period": "New Kingdom (18th Dynasty, c. 1479–1458 BC)",
        "featured": False,
        "description": "The first level of the mortuary temple, approached via a grand processional causeway flanked by sphinxes. Originally lined with myrrh trees from the Punt expedition and featuring T-shaped pools. The colonnade reliefs depict the transport of two massive obelisks from Aswan quarries, commissioned by Hatshepsut for Karnak Temple.",
        "has_image": True,
        "coordinates": {"lat": 25.7380, "lng": 32.6067},
        "tags": ["historic"],
        "related_sites": ["avenue_of_sphinxes"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "hatshepsut_middle_terrace",
        "name": "Middle Terrace & Punt Reliefs",
        "name_ar": "الشرفة الوسطى ونقوش بونت",
        "category": "Pharaonic",
        "subcategory": "Temples",
        "region": "Luxor",
        "parent_slug": "temple_of_hatshepsut",
        "period": "New Kingdom (18th Dynasty)",
        "featured": True,
        "description": "The second terrace features the temple's most famous reliefs — a detailed pictorial record of Hatshepsut's legendary trading expedition to the Land of Punt (modern Somalia/Eritrea), showing exotic goods, incense trees, the portly Queen of Punt, and Egyptian ships. The Birth Colonnade on the south depicts Hatshepsut's divine conception, with the god Amun visiting her mother Queen Ahmose.",
        "has_image": True,
        "coordinates": {"lat": 25.7380, "lng": 32.6067},
        "tags": ["must-visit", "art"],
        "related_sites": ["karnak_temple"],
        "images": [],
        "sections": [
            {"title": "The Punt Expedition Reliefs", "content": "The most complete ancient record of a trading expedition — showing ships loaded with myrrh trees, ivory, ebony, gold, and exotic animals. The depiction of the obese Queen of Punt (Ati) and her husband is one of the most reproduced images in Egyptology."},
            {"title": "Birth Colonnade", "content": "Political propaganda in stone — reliefs showing the god Amun visiting Queen Ahmose in the form of Thutmose I, divine conception of Hatshepsut, and the infant being blessed by gods, legitimizing her rule as pharaoh."},
        ],
    },
    {
        "slug": "hatshepsut_upper_terrace",
        "name": "Upper Terrace & Sanctuary",
        "name_ar": "الشرفة العليا والمقدس",
        "category": "Pharaonic",
        "subcategory": "Temples",
        "region": "Luxor",
        "parent_slug": "temple_of_hatshepsut",
        "period": "New Kingdom (18th Dynasty)",
        "featured": False,
        "description": "The highest and most sacred level, reached through granite doorways flanked by Osiride statues of Hatshepsut. The inner sanctuary was carved deep into the cliff face and dedicated to Amun-Ra, aligned so sunlight entered the shrine on specific dates. Many of Hatshepsut's images here were deliberately defaced by her successor Thutmose III in a damnatio memoriae.",
        "has_image": True,
        "coordinates": {"lat": 25.7380, "lng": 32.6067},
        "tags": ["historic"],
        "related_sites": ["karnak_temple"],
        "images": [],
        "sections": [
            {"title": "Osiride Statues", "content": "Monumental statues showing Hatshepsut in the wrappings of Osiris, wearing the traditional pharaonic false beard — asserting her authority as legitimate ruler of Upper and Lower Egypt."},
            {"title": "The Damnatio Memoriae", "content": "After Hatshepsut's death, Thutmose III systematically erased her images and cartouches throughout the temple — one of history's most famous attempts to erase a ruler from memory."},
        ],
    },
    {
        "slug": "hatshepsut_hathor_chapel",
        "name": "Chapel of Hathor",
        "name_ar": "معبد حتحور",
        "category": "Pharaonic",
        "subcategory": "Temples",
        "region": "Luxor",
        "parent_slug": "temple_of_hatshepsut",
        "period": "New Kingdom (18th Dynasty)",
        "featured": False,
        "description": "A chapel dedicated to the cow-goddess Hathor on the south side of the middle terrace. Features distinctive Hathor-headed columns (with the face of the goddess bearing cow ears), vibrant wall paintings showing offerings and ritual scenes, and depictions of Hatshepsut nursing from the sacred Hathor cow — symbolizing divine legitimacy.",
        "has_image": True,
        "coordinates": {"lat": 25.7380, "lng": 32.6067},
        "tags": ["art", "off-the-beaten-path"],
        "related_sites": ["dendera_temple"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "hatshepsut_anubis_chapel",
        "name": "Chapel of Anubis",
        "name_ar": "معبد أنوبيس",
        "category": "Pharaonic",
        "subcategory": "Temples",
        "region": "Luxor",
        "parent_slug": "temple_of_hatshepsut",
        "period": "New Kingdom (18th Dynasty)",
        "featured": False,
        "description": "A beautifully preserved chapel dedicated to the jackal-headed god Anubis, guardian of the dead. Located on the north side of the middle terrace, it retains some of the temple's best-preserved original color — vivid blues, reds, and golds on the walls and ceiling. The vaulted hypostyle hall leads to a series of inner chambers with offering scenes.",
        "has_image": True,
        "coordinates": {"lat": 25.7380, "lng": 32.6067},
        "tags": ["art"],
        "related_sites": ["valley_of_the_kings"],
        "images": [],
        "sections": [],
    },
]
