# Islamic Heritage
SITES = [
    # ── Historic Cairo ──
    {"slug": "historic_cairo", "name": "Historic Cairo (UNESCO)", "name_ar": "القاهرة التاريخية",
     "category": "Islamic", "subcategory": "Historic Cairo", "region": "Cairo",
     "period": "Fatimid to Ottoman (969-1800 AD)",
     "description": "One of the world's oldest Islamic cities, containing 600+ listed monuments. A UNESCO World Heritage Site encompassing mosques, madrasas, hammams, and fountains.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0459, "lng": 31.2625},
     "tags": ["UNESCO", "must-visit"], "related_sites": ["al_muizz_street", "khan_el_khalili"]},

    {"slug": "al_muizz_street", "name": "Al-Muizz Street", "name_ar": "شارع المعز",
     "category": "Islamic", "subcategory": "Historic Cairo", "region": "Cairo",
     "period": "Fatimid (969 AD onwards)",
     "description": "The spine of historic Cairo, a kilometer-long open-air museum lined with the highest concentration of medieval Islamic architecture anywhere in the world.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0497, "lng": 31.2619},
     "tags": ["must-visit", "photography"], "related_sites": ["khan_el_khalili", "bab_zuweila", "qalawun_complex"]},

    {"slug": "khan_el_khalili", "name": "Khan El-Khalili Bazaar", "name_ar": "خان الخليلي",
     "category": "Islamic", "subcategory": "Historic Cairo", "region": "Cairo",
     "period": "Mamluk (1382 AD)",
     "description": "Cairo's legendary 14th-century bazaar, a labyrinth of narrow alleys brimming with spice shops, copper goods, jewelry, and the iconic El-Fishawi café.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0477, "lng": 31.2625},
     "tags": ["must-visit"], "related_sites": ["al_muizz_street", "al_hussein_mosque"]},

    {"slug": "bab_zuweila", "name": "Bab Zuweila", "name_ar": "باب زويلة",
     "category": "Islamic", "subcategory": "Historic Cairo", "region": "Cairo",
     "period": "Fatimid (1092 AD)",
     "description": "The last remaining southern gate of Fatimid Cairo, crowned by the twin minarets of Al-Muayyad Mosque. Offers panoramic views from the top.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0436, "lng": 31.2581},
     "tags": ["architecture", "historic", "must-visit"], "related_sites": ["al_muizz_street"]},

    {"slug": "bayt_al_suhaymi", "name": "Bayt Al-Suhaymi", "name_ar": "بيت السحيمي",
     "category": "Islamic", "subcategory": "Historic Cairo", "region": "Cairo",
     "period": "Ottoman (1648 AD)",
     "description": "A perfectly preserved Ottoman-era merchant's house showcasing traditional Islamic domestic architecture with mashrabiya windows, courtyards, and fountains.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0536, "lng": 31.2617},
     "tags": ["photography"], "related_sites": ["al_muizz_street"]},

    {"slug": "wikala_al_ghuri", "name": "Wikala Al-Ghuri", "name_ar": "وكالة الغوري",
     "category": "Islamic", "subcategory": "Historic Cairo", "region": "Cairo",
     "period": "Mamluk (1504 AD)",
     "description": "A beautifully restored medieval caravanserai that now hosts traditional arts, including the famous Tanoura whirling dervish performances.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0461, "lng": 31.2588},
     "tags": ["architecture", "historic", "off-the-beaten-path"], "related_sites": ["sultan_al_ghuri_complex"]},

    {"slug": "sultan_al_ghuri_complex", "name": "Sultan Al-Ghuri Complex", "name_ar": "مجمع السلطان الغوري",
     "category": "Islamic", "subcategory": "Historic Cairo", "region": "Cairo",
     "period": "Mamluk (1503-1505 AD)",
     "description": "A majestic Mamluk complex including mosque, mausoleum, and kuttab, marking the final flowering of Mamluk architecture before Ottoman conquest.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0453, "lng": 31.2588},
     "tags": ["architecture", "historic", "off-the-beaten-path"], "related_sites": ["wikala_al_ghuri"]},

    {"slug": "city_of_the_dead", "name": "City of the Dead (Cairo Necropolis)", "name_ar": "مدينة الموتى",
     "category": "Islamic", "subcategory": "Historic Cairo", "region": "Cairo",
     "period": "Mamluk to Ottoman",
     "description": "A vast Islamic-era necropolis where ornate mausoleums and mosques mingle with a living community, creating one of Cairo's most extraordinary neighborhoods.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0400, "lng": 31.2778},
     "tags": ["architecture", "historic", "photography"], "related_sites": ["cairo_citadel"]},

    # ── Mosques ──
    {"slug": "al_azhar_mosque", "name": "Al-Azhar Mosque", "name_ar": "الجامع الأزهر",
     "category": "Islamic", "subcategory": "Mosques", "region": "Cairo",
     "period": "Fatimid (970 AD)",
     "description": "Founded in 970 AD, home to the world's second-oldest continuously operating university. A masterpiece of Fatimid architecture and the spiritual heart of Sunni Islam.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0456, "lng": 31.2625},
     "tags": ["must-visit"], "related_sites": ["khan_el_khalili", "al_hussein_mosque"]},

    {"slug": "muhammad_ali_mosque", "name": "Mosque of Muhammad Ali", "name_ar": "مسجد محمد علي",
     "category": "Islamic", "subcategory": "Mosques", "region": "Cairo",
     "period": "Ottoman (1830-1848 AD)",
     "description": "The iconic alabaster mosque crowning the Saladin Citadel, its twin minarets and massive dome dominating Cairo's skyline. Modeled on Ottoman Imperial mosques.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0288, "lng": 31.2597},
     "tags": ["must-visit"], "related_sites": ["cairo_citadel", "sultan_hassan_mosque"]},

    {"slug": "sultan_hassan_mosque", "name": "Sultan Hassan Mosque-Madrasa", "name_ar": "مسجد ومدرسة السلطان حسن",
     "category": "Islamic", "subcategory": "Mosques", "region": "Cairo",
     "period": "Mamluk (1356-1363 AD)",
     "description": "A colossal Mamluk masterpiece and one of the largest mosques in the world, with soaring 36-meter walls and an awe-inspiring central courtyard.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0319, "lng": 31.2572},
     "tags": ["must-visit", "photography"], "related_sites": ["al_rifai_mosque", "cairo_citadel"]},

    {"slug": "al_rifai_mosque", "name": "Al-Rifa'i Mosque", "name_ar": "مسجد الرفاعي",
     "category": "Islamic", "subcategory": "Mosques", "region": "Cairo",
     "period": "Modern (1869-1912 AD)",
     "description": "Built to complement Sultan Hassan Mosque opposite, this royal mosque houses the tombs of Egypt's last ruling family including King Farouk and the Shah of Iran.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0322, "lng": 31.2567},
     "tags": ["architecture", "must-visit", "religious"], "related_sites": ["sultan_hassan_mosque"]},

    {"slug": "ibn_tulun_mosque", "name": "Ibn Tulun Mosque", "name_ar": "مسجد ابن طولون",
     "category": "Islamic", "subcategory": "Mosques", "region": "Cairo",
     "period": "Abbasid (879 AD)",
     "description": "Cairo's oldest intact mosque and the largest in Egypt by area. Its unique spiral minaret and vast courtyard reflect Samarran Iraqi architectural influence.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0285, "lng": 31.2494},
     "tags": ["must-visit"], "related_sites": ["cairo_citadel"]},

    {"slug": "al_hakim_mosque", "name": "Al-Hakim Mosque", "name_ar": "جامع الحاكم بأمر الله",
     "category": "Islamic", "subcategory": "Mosques", "region": "Cairo",
     "period": "Fatimid (990-1013 AD)",
     "description": "A monumental Fatimid mosque near Bab al-Futuh gate, restored by the Dawoodi Bohra community. Named after the enigmatic Fatimid caliph Al-Hakim.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0556, "lng": 31.2622},
     "tags": ["architecture", "religious"], "related_sites": ["al_muizz_street"]},

    {"slug": "al_hussein_mosque", "name": "Al-Hussein Mosque", "name_ar": "مسجد الحسين",
     "category": "Islamic", "subcategory": "Mosques", "region": "Cairo",
     "period": "Fatimid (1154 AD)",
     "description": "One of the holiest Islamic sites in Egypt, believed to contain the head of Prophet Muhammad's grandson Hussein. A major pilgrimage destination.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0472, "lng": 31.2633},
     "tags": ["architecture", "must-visit", "religious"], "related_sites": ["khan_el_khalili", "al_azhar_mosque"]},

    {"slug": "amr_ibn_al_as_mosque", "name": "Mosque of Amr ibn al-As", "name_ar": "مسجد عمرو بن العاص",
     "category": "Islamic", "subcategory": "Mosques", "region": "Cairo",
     "period": "Early Islamic (642 AD)",
     "description": "The first mosque built in Africa and the entire Islamic world outside the Arabian Peninsula, founded by the Arab conqueror of Egypt in 642 AD.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0103, "lng": 31.2331},
     "tags": ["architecture", "off-the-beaten-path", "religious"], "related_sites": ["babylon_fortress"]},

    {"slug": "qalawun_complex", "name": "Qalawun Complex", "name_ar": "مجمع قلاوون",
     "category": "Islamic", "subcategory": "Mosques", "region": "Cairo",
     "period": "Mamluk (1284-1285 AD)",
     "description": "A magnificent Mamluk complex on Al-Muizz Street combining mosque, madrasa, and hospital (maristan). The stained-glass windows are among Cairo's finest.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0506, "lng": 31.2611},
     "tags": ["architecture", "must-visit", "religious"], "related_sites": ["al_muizz_street", "barquq_mosque"]},

    {"slug": "barquq_mosque", "name": "Mosque of Sultan Barquq", "name_ar": "مسجد السلطان برقوق",
     "category": "Islamic", "subcategory": "Mosques", "region": "Cairo",
     "period": "Mamluk (1384-1386 AD)",
     "description": "The first Circassian Mamluk monument on Al-Muizz Street, featuring an elegant marble courtyard and four iwans around a central fountain.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0503, "lng": 31.2614},
     "tags": ["architecture", "off-the-beaten-path", "religious"], "related_sites": ["qalawun_complex"]},

    {"slug": "baybars_mosque", "name": "Mosque of Sultan Baybars", "name_ar": "مسجد الظاهر بيبرس",
     "category": "Islamic", "subcategory": "Mosques", "region": "Cairo",
     "period": "Mamluk (1266-1269 AD)",
     "description": "One of Cairo's largest and earliest Mamluk mosques, built by the legendary warrior sultan who defeated the Mongols and Crusaders.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0647, "lng": 31.2534},
     "tags": ["architecture", "off-the-beaten-path", "religious"], "related_sites": ["cairo_citadel"]},

    {"slug": "madrasa_al_salih_ayyub", "name": "Madrasa of Al-Salih Ayyub", "name_ar": "مدرسة الصالح أيوب",
     "category": "Islamic", "subcategory": "Mosques", "region": "Cairo",
     "period": "Ayyubid (1242-1250 AD)",
     "description": "The first madrasa in Cairo to teach all four Sunni schools of jurisprudence, built by the last effective Ayyubid sultan.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0478, "lng": 31.2603},
     "tags": ["architecture", "off-the-beaten-path", "religious"], "related_sites": ["al_muizz_street"]},

    # ── Citadels & Fortresses ──
    {"slug": "cairo_citadel", "name": "Saladin Citadel of Cairo", "name_ar": "قلعة صلاح الدين",
     "category": "Islamic", "subcategory": "Citadels & Fortresses", "region": "Cairo",
     "period": "Ayyubid (1176 AD)",
     "description": "A medieval Islamic fortification crowning Mokattam Hill, housing mosques, museums, and palaces. The seat of Egyptian government for nearly 700 years.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0288, "lng": 31.2597},
     "tags": ["must-visit"], "related_sites": ["muhammad_ali_mosque", "sultan_hassan_mosque"]},

    {"slug": "citadel_of_qaitbay", "name": "Citadel of Qaitbay", "name_ar": "قلعة قايتباي",
     "category": "Islamic", "subcategory": "Citadels & Fortresses", "region": "Alexandria",
     "period": "Mamluk (1477 AD)",
     "description": "A stunning 15th-century Mamluk fortress built on the exact site of the ancient Lighthouse of Alexandria, one of the Seven Wonders of the Ancient World.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 31.2139, "lng": 29.8856},
     "tags": ["must-visit"], "related_sites": ["bibliotheca_alexandrina"]},

    {"slug": "babylon_fortress", "name": "Babylon Fortress", "name_ar": "حصن بابليون",
     "category": "Islamic", "subcategory": "Citadels & Fortresses", "region": "Cairo",
     "period": "Roman (30 BC onwards)",
     "description": "A Roman fortress in Old Cairo that became the foundation for Egypt's early Christian community. Houses the Coptic Museum and several ancient churches.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0058, "lng": 31.2297},
     "tags": ["architecture", "historic", "off-the-beaten-path"], "related_sites": ["hanging_church", "coptic_museum"]},

    {"slug": "islamic_cairo", "name": "Islamic Cairo District", "name_ar": "القاهرة الإسلامية",
     "category": "Islamic", "subcategory": "Historic Cairo", "region": "Cairo",
     "period": "Fatimid to Ottoman",
     "description": "A living medieval quarter representing 1,000 years of Islamic civilization, with winding alleys connecting historic mosques, madrasas, and caravanserais.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0486, "lng": 31.2617},
     "tags": ["UNESCO"], "related_sites": ["al_muizz_street", "khan_el_khalili"]},
]
