"""Islamic Cairo (Al-Muizz corridor & Citadel) — sub-sites."""

ISLAMIC_CAIRO_CHILDREN = [
    {
        "slug": "islamic_cairo_al_azhar_mosque",
        "name": "Al-Azhar Mosque & University",
        "name_ar": "الجامع الأزهر",
        "category": "Islamic",
        "subcategory": "Mosques",
        "region": "Cairo",
        "parent_slug": "islamic_cairo",
        "period": "Fatimid (970 CE)",
        "featured": True,
        "description": "The oldest university in the world (founded 970 CE) and one of Cairo's most important mosques. Built by the Fatimid general Jawhar al-Siqilli shortly after founding Cairo. The name means 'The Splendid' — a reference to Fatimah al-Zahra. Its courtyard blends Fatimid, Mamluk, and Ottoman architectural layers accumulated over a millennium.",
        "has_image": True,
        "coordinates": {"lat": 30.0459, "lng": 31.2627},
        "tags": ["must-visit", "iconic", "religious", "architecture", "UNESCO"],
        "related_sites": ["islamic_cairo", "khan_el_khalili"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "islamic_cairo_sultan_hassan",
        "name": "Mosque-Madrassa of Sultan Hassan",
        "name_ar": "مسجد ومدرسة السلطان حسن",
        "category": "Islamic",
        "subcategory": "Mosques",
        "region": "Cairo",
        "parent_slug": "islamic_cairo",
        "period": "Mamluk (1356–1363 CE)",
        "featured": True,
        "description": "A masterpiece of Mamluk architecture and one of the largest mosques in the world. The 36-meter-high entrance portal is the tallest in Cairo. The cruciform plan has four iwans around a central courtyard with an ablution fountain. The qibla iwan's 32-meter vault was the largest in Egypt. Some limestone blocks were allegedly taken from the Great Pyramid's casing.",
        "has_image": True,
        "coordinates": {"lat": 30.0328, "lng": 31.2572},
        "tags": ["must-visit", "iconic", "architecture"],
        "related_sites": ["islamic_cairo", "cairo_citadel"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "islamic_cairo_bab_zuweila",
        "name": "Bab Zuweila Gate",
        "name_ar": "باب زويلة",
        "category": "Islamic",
        "subcategory": "Historic Districts",
        "region": "Cairo",
        "parent_slug": "islamic_cairo",
        "period": "Fatimid (1092 CE)",
        "featured": False,
        "description": "The last surviving southern gate of Fatimid Cairo, topped by the twin minarets of the Mosque of al-Mu'ayyad. Visitors can climb to the top for panoramic views of Islamic Cairo. Historically it was the site of public executions — the last Mamluk sultan Tumanbay was hanged from this gate in 1517 after the Ottoman conquest.",
        "has_image": True,
        "coordinates": {"lat": 30.0427, "lng": 31.2570},
        "tags": ["architecture", "photography", "panoramic-view"],
        "related_sites": ["islamic_cairo", "al_muizz_street"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "islamic_cairo_al_muizz_street",
        "name": "Al-Muizz li-Din Allah Street",
        "name_ar": "شارع المعز لدين الله",
        "category": "Islamic",
        "subcategory": "Historic Districts",
        "region": "Cairo",
        "parent_slug": "islamic_cairo",
        "period": "Fatimid–Mamluk–Ottoman (969 CE onward)",
        "featured": True,
        "description": "The spine of historic Cairo — a 1-km open-air museum stretching from Bab al-Futuh to Bab Zuweila. Lined with the highest concentration of medieval Islamic architecture in the world: mosques, madrasas, hammams, sabils (public fountains), and caravanserais. Best explored at night when the monuments are illuminated and the street is pedestrianized.",
        "has_image": True,
        "coordinates": {"lat": 30.0480, "lng": 31.2620},
        "tags": ["must-visit", "photography", "UNESCO", "night-spectacle"],
        "related_sites": ["islamic_cairo", "khan_el_khalili"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "islamic_cairo_qalawun_complex",
        "name": "Complex of Sultan Qalawun",
        "name_ar": "مجموعة السلطان قلاوون",
        "category": "Islamic",
        "subcategory": "Mosques",
        "region": "Cairo",
        "parent_slug": "islamic_cairo",
        "period": "Mamluk (1284–1285 CE)",
        "featured": False,
        "description": "A triple-function complex on Al-Muizz Street: mosque, madrasa, and maristan (hospital). The maristan was one of the medieval world's most advanced hospitals, treating patients free of charge. The mausoleum's octagonal interior with stained glass and marble inlay rivals the finest Gothic cathedrals in ambition.",
        "has_image": True,
        "coordinates": {"lat": 30.0502, "lng": 31.2615},
        "tags": ["architecture", "off-the-beaten-path"],
        "related_sites": ["islamic_cairo", "islamic_cairo_al_muizz_street"],
        "images": [],
        "sections": [],
    },
]
