"""Karnak Temple Complex — sub-sites."""

KARNAK_CHILDREN = [
    {
        "slug": "karnak_great_hypostyle_hall",
        "name": "Great Hypostyle Hall",
        "name_ar": "قاعة الأعمدة الكبرى",
        "category": "Pharaonic",
        "subcategory": "Temples",
        "region": "Luxor",
        "parent_slug": "karnak_temple",
        "period": "New Kingdom (19th Dynasty)",
        "featured": True,
        "description": "The most awe-inspiring interior space of the ancient world — 134 massive stone columns covering 5,000 sq meters. The 12 central columns rise 24 meters tall with open papyrus capitals, while 122 flanking columns stand 15 meters with closed bud capitals. Built by Seti I and Ramesses II. The forest of carved columns, once vibrantly painted, still bears traces of original color.",
        "has_image": True,
        "coordinates": {"lat": 25.7188, "lng": 32.6573},
        "tags": ["must-visit", "iconic", "architecture"],
        "related_sites": ["luxor_temple", "karnak_temple"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "karnak_sacred_lake",
        "name": "Sacred Lake",
        "name_ar": "البحيرة المقدسة",
        "category": "Pharaonic",
        "subcategory": "Temples",
        "region": "Luxor",
        "parent_slug": "karnak_temple",
        "period": "New Kingdom",
        "featured": False,
        "description": "A large artificial lake (120×77 meters) used by priests for ritual purification before entering the temple. The waters represented the primeval ocean Nun — the source of all creation. Nearby sits a giant granite scarab of Khepri; legend says circling it 7 times grants a wish.",
        "has_image": True,
        "coordinates": {"lat": 25.7177, "lng": 32.6578},
        "tags": ["photography", "legend"],
        "related_sites": ["karnak_temple"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "karnak_temple_of_khonsu",
        "name": "Temple of Khonsu",
        "name_ar": "معبد خونسو",
        "category": "Pharaonic",
        "subcategory": "Temples",
        "region": "Luxor",
        "parent_slug": "karnak_temple",
        "period": "New Kingdom (20th Dynasty)",
        "featured": False,
        "description": "A complete, well-preserved small temple dedicated to the moon god Khonsu (son of Amun and Mut). Built by Ramesses III and completed by later pharaohs, it preserves an excellent example of a standard Egyptian temple plan — from pylon gateway through open court, hypostyle hall, to inner sanctuary.",
        "has_image": True,
        "coordinates": {"lat": 25.7171, "lng": 32.6555},
        "tags": ["architecture", "off-the-beaten-path"],
        "related_sites": ["karnak_temple", "medinet_habu"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "karnak_sound_and_light",
        "name": "Karnak Sound & Light Show",
        "name_ar": "عرض الصوت والضوء بالكرنك",
        "category": "Pharaonic",
        "subcategory": "Temples",
        "region": "Luxor",
        "parent_slug": "karnak_temple",
        "period": "Modern",
        "featured": False,
        "description": "An evening spectacle that brings Karnak to life with dramatic lighting, narration, and music. Visitors walk through the illuminated temple precincts as the story of ancient Thebes unfolds. Available in multiple languages. The nighttime lighting transforms the massive columns into a magical experience.",
        "has_image": True,
        "coordinates": {"lat": 25.7188, "lng": 32.6573},
        "tags": ["family-friendly", "evening"],
        "related_sites": ["karnak_temple", "avenue_of_sphinxes"],
        "images": [],
        "sections": [],
    },
]
