"""Luxor Temple — sub-sites and sections."""

LUXOR_TEMPLE_CHILDREN = [
    {
        "slug": "luxor_temple_court_ramesses",
        "name": "Court of Ramesses II",
        "name_ar": "فناء رمسيس الثاني",
        "category": "Pharaonic",
        "subcategory": "Tombs & Temples",
        "region": "Luxor",
        "parent_slug": "luxor_temple",
        "period": "New Kingdom (19th Dynasty, c. 1250 BC)",
        "featured": True,
        "description": "The first court upon entering the temple, surrounded by 74 papyrus-bud columns in a double row. Originally fronted by six colossal statues of Ramesses II (only two survive) and two obelisks — one now stands in the Place de la Concorde in Paris (gifted to France in 1829). The Abu El Haggag Mosque sits atop the northeast corner, built when the court was buried under centuries of sediment.",
        "has_image": True,
        "coordinates": {"lat": 25.6995, "lng": 32.6392},
        "tags": ["must-visit", "iconic", "architecture"],
        "related_sites": ["luxor_temple"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "luxor_temple_colonnade_amenhotep",
        "name": "Colonnade of Amenhotep III",
        "name_ar": "بهو أعمدة أمنحتب الثالث",
        "category": "Pharaonic",
        "subcategory": "Tombs & Temples",
        "region": "Luxor",
        "parent_slug": "luxor_temple",
        "period": "New Kingdom (18th Dynasty, c. 1350 BC)",
        "featured": False,
        "description": "A processional colonnade of fourteen massive papyrus columns, each 16 meters high with open capitals. The walls depict the Opet Festival in vivid relief — Amun's sacred barque carried from Karnak to Luxor Temple along the Avenue of Sphinxes. These are among the finest reliefs from the 18th Dynasty.",
        "has_image": True,
        "coordinates": {"lat": 25.6998, "lng": 32.6390},
        "tags": ["architecture", "art"],
        "related_sites": ["luxor_temple", "karnak_temple_complex"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "luxor_temple_abu_el_haggag",
        "name": "Mosque of Abu El Haggag",
        "name_ar": "مسجد أبو الحجاج الأقصري",
        "category": "Islamic",
        "subcategory": "Mosques",
        "region": "Luxor",
        "parent_slug": "luxor_temple",
        "period": "Fatimid/Ayyubid (13th century CE)",
        "featured": False,
        "description": "A functioning mosque built atop the buried northeast corner of Luxor Temple — a remarkable layering of 3,000 years of worship. When the temple was excavated in the 19th century, the mosque's door was found 8 meters above the ancient floor. The annual moulid (festival) of Abu El Haggag features a boat procession echoing the ancient Opet Festival.",
        "has_image": True,
        "coordinates": {"lat": 25.7000, "lng": 32.6395},
        "tags": ["religious", "architecture", "cultural-event"],
        "related_sites": ["luxor_temple"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "luxor_temple_avenue_of_sphinxes",
        "name": "Avenue of Sphinxes (Sphinx Alley)",
        "name_ar": "طريق الكباش",
        "category": "Pharaonic",
        "subcategory": "Monuments & Statues",
        "region": "Luxor",
        "parent_slug": "luxor_temple",
        "period": "New Kingdom (18th–30th Dynasty)",
        "featured": True,
        "description": "A 2.7-km ceremonial road connecting Luxor Temple to Karnak Temple, lined with over 1,350 sphinx statues (mostly ram-headed near Karnak, human-headed near Luxor). Restored and reopened in November 2021 in a spectacular ceremony. Walking this path at sunset is one of Luxor's most atmospheric experiences.",
        "has_image": True,
        "coordinates": {"lat": 25.7010, "lng": 32.6405},
        "tags": ["must-visit", "iconic", "photography", "night-spectacle"],
        "related_sites": ["luxor_temple", "karnak_temple_complex"],
        "images": [],
        "sections": [],
    },
]
