# Modern & Contemporary Heritage
SITES = [
    {"slug": "cairo_tower", "name": "Cairo Tower", "name_ar": "برج القاهرة",
     "category": "Modern", "subcategory": "Landmarks", "region": "Cairo",
     "period": "Built 1956-1961",
     "description": "A 187-meter lotus-shaped tower on Gezira Island offering 360-degree panoramic views of Cairo, the Nile, and the Giza Pyramids on clear days.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0459, "lng": 31.2243},
     "tags": ["modern", "must-visit", "photography"], "related_sites": ["gezira_island"]},

    {"slug": "aswan_high_dam", "name": "Aswan High Dam", "name_ar": "السد العالي",
     "category": "Modern", "subcategory": "Engineering", "region": "Aswan",
     "period": "Built 1960-1970",
     "description": "One of the 20th century's greatest engineering feats, taming the Nile's annual flood and creating Lake Nasser while generating hydroelectric power for Egypt.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 23.9708, "lng": 32.8781},
     "tags": ["modern", "must-visit"], "related_sites": ["lake_nasser", "philae_temple"]},

    {"slug": "suez_canal", "name": "Suez Canal", "name_ar": "قناة السويس",
     "category": "Modern", "subcategory": "Engineering", "region": "Suez",
     "period": "Opened 1869",
     "description": "The 193 km artificial waterway connecting the Mediterranean and Red Sea, one of the most important maritime shortcuts in global trade history.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.4550, "lng": 32.3500},
     "tags": ["modern", "must-visit"], "related_sites": []},

    {"slug": "baron_empain_palace", "name": "Baron Empain Palace", "name_ar": "قصر البارون إمبان",
     "category": "Modern", "subcategory": "Palaces", "region": "Cairo",
     "period": "Built 1907-1911",
     "description": "A mesmerizing Hindu-Khmer inspired palace in Heliopolis, recently restored to its original glory. Inspired by the temples of Angkor Wat.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0903, "lng": 31.3281},
     "tags": ["photography"], "related_sites": []},

    {"slug": "abdeen_palace", "name": "Abdeen Palace", "name_ar": "قصر عابدين",
     "category": "Modern", "subcategory": "Palaces", "region": "Cairo",
     "period": "Built 1863-1874",
     "description": "The official presidential palace of Egypt, containing several museums displaying royal weapons, silver, and gifts from world leaders.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0422, "lng": 31.2475},
     "tags": ["architecture", "historic", "must-visit"], "related_sites": ["manial_palace"]},

    {"slug": "manial_palace", "name": "Manial Palace Museum", "name_ar": "متحف قصر المنيل",
     "category": "Modern", "subcategory": "Palaces", "region": "Cairo",
     "period": "Built 1899-1929",
     "description": "A lavish palace complex on Rhoda Island blending Ottoman, Moorish, Persian, and Art Nouveau styles, surrounded by beautiful tropical gardens.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0167, "lng": 31.2253},
     "tags": ["architecture", "historic", "photography"], "related_sites": ["abdeen_palace"]},

    {"slug": "zamalek", "name": "Zamalek District", "name_ar": "حي الزمالك",
     "category": "Modern", "subcategory": "Districts", "region": "Cairo",
     "period": "19th-20th Century",
     "description": "An affluent island neighborhood known for its tree-lined streets, embassies, art galleries, trendy cafés, and the Cairo Opera House complex.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0608, "lng": 31.2194},
     "tags": ["photography", "urban"], "related_sites": ["gezira_island", "cairo_tower"]},

    {"slug": "stanley_bridge", "name": "Stanley Bridge", "name_ar": "كوبري ستانلي",
     "category": "Modern", "subcategory": "Landmarks", "region": "Alexandria",
     "period": "Built 2001",
     "description": "An iconic modern bridge in Alexandria with elegant towers inspired by Islamic and pharaonic architecture, a beloved symbol of the coastal city.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 31.2431, "lng": 29.9603},
     "tags": ["modern", "photography"], "related_sites": ["bibliotheca_alexandrina"]},

    {"slug": "al_azhar_park", "name": "Al-Azhar Park", "name_ar": "حديقة الأزهر",
     "category": "Modern", "subcategory": "Parks", "region": "Cairo",
     "period": "Opened 2005",
     "description": "A stunning 30-hectare Islamic garden built on a 500-year-old garbage dump by the Aga Khan Trust, offering panoramic views of Islamic Cairo and the Citadel.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0393, "lng": 31.2661},
     "tags": ["family-friendly", "must-visit", "photography"], "related_sites": ["cairo_citadel", "al_azhar_mosque"]},

    {"slug": "cairo_opera_house", "name": "Cairo Opera House", "name_ar": "دار الأوبرا المصرية",
     "category": "Modern", "subcategory": "Cultural", "region": "Cairo",
     "period": "Opened 1988",
     "description": "Egypt's premier performing arts venue, the Cairo Opera House was inaugurated in 1988 as a gift from the Japanese government to replace the original Khedivial Opera House destroyed by fire in 1971. Located on Gezira Island in the National Cultural Center, it hosts opera, ballet, symphony orchestras, and Arabic music performances. The complex includes the Main Hall (1,200 seats), Small Hall (500 seats), Open Air Theatre, and the Museum of Modern Egyptian Art.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0422, "lng": 31.2244},
     "tags": ["modern", "architecture", "cultural"], "related_sites": ["cairo_tower", "gezira_island"]},

    {"slug": "new_administrative_capital", "name": "New Administrative Capital", "name_ar": "العاصمة الإدارية الجديدة",
     "category": "Modern", "subcategory": "Urban Development", "region": "Cairo",
     "period": "Under Construction (2015-present)",
     "description": "Egypt's ambitious new capital city being built 45 km east of Cairo in the desert. The $58 billion mega-project spans 700 km² and will eventually house 6.5 million people along with all government ministries. Key landmarks include the Iconic Tower (385m, Africa's tallest building), the massive Al-Fattah Al-Aleem Mosque (one of the world's largest), the Cathedral of the Nativity of Christ, monorail system, and a vast central park twice the size of New York's Central Park.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0196, "lng": 31.7600},
     "tags": ["modern", "architecture", "photography"], "related_sites": []},

    {"slug": "port_said", "name": "Port Said", "name_ar": "بورسعيد",
     "category": "Modern", "subcategory": "Cities", "region": "Port Said",
     "period": "Founded 1859",
     "description": "A historic port city at the northern entrance of the Suez Canal, founded alongside the canal's construction. Known for its distinctive colonial-era wooden-balcony architecture, duty-free shopping, and the iconic Suez Canal Authority building. The city played a heroic role during the 1956 Suez Crisis and the Lighthouse of Port Said (built 1869) was the first building in the world constructed with reinforced concrete. The military museum and De Lesseps statue pedestal recall the canal's dramatic history.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 31.2653, "lng": 32.3019},
     "tags": ["historic", "architecture", "photography"], "related_sites": ["suez_canal", "ismailia"]},

    {"slug": "ismailia", "name": "Ismailia", "name_ar": "الإسماعيلية",
     "category": "Modern", "subcategory": "Cities", "region": "Ismailia",
     "period": "Founded 1863",
     "description": "The 'City of Beauty and Enchantment' — a charming garden city built midway along the Suez Canal. Named after Khedive Ismail, it features tree-lined European-style boulevards, Lake Timsah (Crocodile Lake), the Ismailia Museum housing Pharaonic and Greco-Roman artifacts, and the beautiful De Lesseps House. The city serves as the administrative headquarters of the Suez Canal Authority.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.5965, "lng": 32.2715},
     "tags": ["scenic", "historic"], "related_sites": ["suez_canal", "port_said"]},
]
