# Museums
SITES = [
    {"slug": "grand_egyptian_museum", "name": "Grand Egyptian Museum (GEM)", "name_ar": "المتحف المصري الكبير",
     "category": "Museum", "subcategory": "National Museums", "region": "Giza",
     "period": "Inaugurated November 2025",
     "description": "The world's largest archaeological museum dedicated to a single civilization, located 2 km from the Giza Pyramids. At a cost of $1.2 billion, the GEM houses over 100,000 artifacts across 12 permanent galleries arranged chronologically from prehistory to the Greco-Roman period. Its crown jewel is the complete 5,398-piece Tutankhamun collection displayed together for the first time. The museum spans 500,000 square meters with a dramatic glass-roofed atrium housing an 11-meter, 83-ton Ramesses II colossus, a monumental grand staircase with 60+ artifacts, the reconstructed Khufu Solar Boats, a children's museum with AR experiences, and 19 conservation laboratories. Officially inaugurated on November 1, 2025 — the anniversary of Tutankhamun's tomb discovery — it received 18,000 visitors on its first public day.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.9950, "lng": 31.1193},
     "tags": ["must-visit"], "related_sites": ["great_pyramids_of_giza", "egyptian_museum"]},

    {"slug": "egyptian_museum", "name": "Egyptian Museum (Tahrir)", "name_ar": "المتحف المصري بالتحرير",
     "category": "Museum", "subcategory": "National Museums", "region": "Cairo",
     "period": "Founded 1902",
     "description": "The iconic pink building in Tahrir Square that housed Egypt's antiquities for over a century, with 120,000+ artifacts spanning pharaonic through Greco-Roman eras.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0478, "lng": 31.2336},
     "tags": ["must-visit"], "related_sites": ["grand_egyptian_museum"]},

    {"slug": "nmec", "name": "National Museum of Egyptian Civilization", "name_ar": "المتحف القومي للحضارة المصرية",
     "category": "Museum", "subcategory": "National Museums", "region": "Cairo",
     "period": "Opened 2017 (full 2021)",
     "description": "A museum in Fustat spanning all of Egyptian civilization from prehistory to modern times, home to the Royal Mummies Hall with 22 pharaonic mummies.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0058, "lng": 31.2461},
     "tags": ["must-visit"], "related_sites": ["egyptian_museum"]},

    {"slug": "luxor_museum", "name": "Luxor Museum", "name_ar": "متحف الأقصر",
     "category": "Museum", "subcategory": "Regional Museums", "region": "Luxor",
     "period": "Founded 1975",
     "description": "A beautifully curated museum on the Nile corniche showcasing masterpieces from the Theban area, including statues from the Luxor Temple cachette.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 25.7000, "lng": 32.6375},
     "tags": ["indoor", "must-visit"], "related_sites": ["luxor_temple", "karnak_temple"]},

    {"slug": "nubia_museum", "name": "Nubia Museum", "name_ar": "متحف النوبة",
     "category": "Museum", "subcategory": "Regional Museums", "region": "Aswan",
     "period": "Founded 1997",
     "description": "An award-winning museum preserving the rich culture of Nubia, showcasing artifacts rescued from the flooding of Lower Nubia by Lake Nasser.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 24.0828, "lng": 32.8939},
     "tags": ["indoor", "must-visit"], "related_sites": ["philae_temple", "abu_simbel"]},

    {"slug": "museum_of_islamic_art", "name": "Museum of Islamic Art", "name_ar": "متحف الفن الإسلامي",
     "category": "Museum", "subcategory": "Specialized Museums", "region": "Cairo",
     "period": "Founded 1881",
     "description": "One of the world's greatest collections of Islamic art, with 100,000+ objects spanning 1,400 years from across the Muslim world. Beautifully restored after 2014.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0419, "lng": 31.2544},
     "tags": ["indoor", "off-the-beaten-path"], "related_sites": ["al_muizz_street"]},

    {"slug": "alexandria_national_museum", "name": "Alexandria National Museum", "name_ar": "متحف الإسكندرية القومي",
     "category": "Museum", "subcategory": "Regional Museums", "region": "Alexandria",
     "period": "Founded 2003",
     "description": "A museum in a beautifully restored Italian palazzo presenting Alexandria's history from pharaonic times through the Greco-Roman, Coptic, Islamic, and modern eras.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 31.2000, "lng": 29.9000},
     "tags": ["indoor", "off-the-beaten-path"], "related_sites": ["bibliotheca_alexandrina"]},

    {"slug": "imhotep_museum", "name": "Imhotep Museum", "name_ar": "متحف إيمحوتب",
     "category": "Museum", "subcategory": "Site Museums", "region": "Giza",
     "period": "Founded 2006",
     "description": "A museum at the entrance to Saqqara dedicated to the architect Imhotep, displaying artifacts found during excavations of the surrounding necropolis.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.8706, "lng": 31.2173},
     "tags": ["indoor", "off-the-beaten-path"], "related_sites": ["saqqara_necropolis", "pyramid_of_djoser"]},

    {"slug": "mummification_museum", "name": "Mummification Museum", "name_ar": "متحف التحنيط",
     "category": "Museum", "subcategory": "Specialized Museums", "region": "Luxor",
     "period": "Founded 1997",
     "description": "A unique museum on the Nile Corniche in Luxor devoted entirely to the ancient Egyptian art of mummification. The underground galleries house a fascinating collection of mummified animals and humans, canopic jars, surgical tools, natron salts, embalming fluids, and sarcophagi. Exhibits explain the 70-day mummification process step by step with real artifacts. Highlights include the mummy of the 21st Dynasty priest Maserharti, mummified cats, fish, and crocodiles, and a beautifully preserved collection of amulets and linen wrappings.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 25.7000, "lng": 32.6392},
     "tags": ["indoor", "unique", "must-visit"], "related_sites": ["luxor_museum", "luxor_temple"]},

    {"slug": "solar_boat_museum", "name": "Khufu Solar Boat Museum", "name_ar": "متحف مركب الشمس",
     "category": "Museum", "subcategory": "Site Museums", "region": "Giza",
     "period": "New Kingdom artifact, Museum 1982-2021",
     "description": "The Khufu Solar Boat (also called the Khufu Ship) is a 4,600-year-old full-size vessel sealed into a pit at the foot of the Great Pyramid around 2500 BC. Discovered in 1954, the 43.6-meter cedar wood boat was found disassembled in 1,224 pieces and painstakingly reconstructed over 14 years. It was displayed in a purpose-built museum beside the Great Pyramid from 1982 until 2021, when it was carefully transferred to the Grand Egyptian Museum using a specially designed vehicle. A second boat found in an adjacent pit in 1987 is also being restored.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.9792, "lng": 31.1342},
     "tags": ["unique", "must-visit", "historic"], "related_sites": ["great_pyramids_of_giza", "grand_egyptian_museum"]},
]
