# Natural Wonders
SITES = [
    # ── Nile ──
    {"slug": "nile_corniche", "name": "Nile River & Corniche", "name_ar": "نهر النيل والكورنيش",
     "category": "Natural", "subcategory": "Nile", "region": "Cairo",
     "period": "",
     "description": "The lifeblood of Egypt — the world's longest river winds through the country, flanked in Cairo by the famous Corniche promenade with felucca boats.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0444, "lng": 31.2357},
     "tags": ["must-visit", "nature", "photography", "scenic"], "related_sites": ["gezira_island"]},

    {"slug": "lake_nasser", "name": "Lake Nasser", "name_ar": "بحيرة ناصر",
     "category": "Natural", "subcategory": "Nile", "region": "Aswan",
     "period": "Created 1970",
     "description": "One of the world's largest artificial lakes, created by the Aswan High Dam. Home to Nile crocodiles and the relocated Abu Simbel temples on its shores.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 23.0000, "lng": 32.5000},
     "tags": ["must-visit", "nature", "photography", "scenic"], "related_sites": ["aswan_high_dam", "abu_simbel"]},

    {"slug": "kitchener_island_aswan", "name": "Kitchener's Island (Botanical Garden)", "name_ar": "جزيرة النباتات",
     "category": "Natural", "subcategory": "Nile", "region": "Aswan",
     "period": "19th Century",
     "description": "A lush botanical garden on a Nile island in Aswan, featuring exotic plants from across Africa and Asia collected during the British colonial era.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 24.0853, "lng": 32.8822},
     "tags": ["nature", "photography", "scenic"], "related_sites": ["elephantine_island"]},

    {"slug": "gezira_island", "name": "Gezira Island", "name_ar": "جزيرة الجزيرة",
     "category": "Natural", "subcategory": "Nile", "region": "Cairo",
     "period": "",
     "description": "An upscale island in the Nile housing the Cairo Opera House, Cairo Tower, and the Gezira Sporting Club among tree-lined boulevards.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0500, "lng": 31.2244},
     "tags": ["nature", "photography", "scenic"], "related_sites": ["cairo_tower", "zamalek"]},

    # ── Deserts ──
    {"slug": "white_desert", "name": "White Desert", "name_ar": "الصحراء البيضاء",
     "category": "Natural", "subcategory": "Deserts", "region": "New Valley",
     "period": "",
     "description": "A surreal landscape of white chalk rock formations sculpted by wind erosion into mushroom shapes and other otherworldly forms under starlit desert skies.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 27.3333, "lng": 28.2000},
     "tags": ["must-visit", "photography"], "related_sites": ["black_desert", "farafra_oasis"]},

    {"slug": "black_desert", "name": "Black Desert", "name_ar": "الصحراء السوداء",
     "category": "Natural", "subcategory": "Deserts", "region": "New Valley",
     "period": "",
     "description": "Volcanic hills covered in black dolerite stones and powder, creating a dramatic contrast with the golden sand. Often visited en route to the White Desert.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 28.0000, "lng": 28.6000},
     "tags": ["photography"], "related_sites": ["white_desert", "bahariya_oasis"]},

    {"slug": "wadi_el_hitan", "name": "Wadi Al-Hitan (Valley of the Whales)", "name_ar": "وادي الحيتان",
     "category": "Natural", "subcategory": "Deserts", "region": "Fayoum",
     "period": "40 million years ago",
     "description": "A UNESCO World Heritage Site containing invaluable fossil remains of the earliest forms of whales, documenting their evolution from land to sea creatures.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.2667, "lng": 30.0333},
     "tags": ["UNESCO", "photography"], "related_sites": ["wadi_el_rayan", "fayoum_oasis"]},

    {"slug": "wadi_el_rayan", "name": "Wadi El Rayan Waterfalls", "name_ar": "شلالات وادي الريان",
     "category": "Natural", "subcategory": "Deserts", "region": "Fayoum",
     "period": "",
     "description": "Egypt's only waterfalls, formed between two artificial lakes in the desert. A protected area popular for sandboarding and picnics amid stunning desert scenery.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.1833, "lng": 30.3833},
     "tags": ["UNESCO", "desert", "nature", "photography"], "related_sites": ["wadi_el_hitan", "lake_qarun"]},

    {"slug": "lake_qarun", "name": "Lake Qarun", "name_ar": "بحيرة قارون",
     "category": "Natural", "subcategory": "Deserts", "region": "Fayoum",
     "period": "",
     "description": "An ancient lake in the Fayoum depression, remnant of the prehistoric Lake Moeris. A major birdwatching destination and archaeological treasure zone.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.4500, "lng": 30.6000},
     "tags": ["desert", "nature", "photography"], "related_sites": ["fayoum_oasis", "wadi_el_rayan"]},

    # ── Oases ──
    {"slug": "siwa_oasis", "name": "Siwa Oasis", "name_ar": "واحة سيوة",
     "category": "Natural", "subcategory": "Oases", "region": "Matrouh",
     "period": "",
     "description": "A remote and magical oasis near the Libyan border, famous for the Oracle Temple consulted by Alexander the Great, natural hot springs, and unique Siwi culture.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.2031, "lng": 25.5194},
     "tags": ["must-visit"], "related_sites": []},

    {"slug": "bahariya_oasis", "name": "Bahariya Oasis", "name_ar": "الواحات البحرية",
     "category": "Natural", "subcategory": "Oases", "region": "New Valley",
     "period": "",
     "description": "Gateway to the Black and White Deserts, known for the Valley of the Golden Mummies discovered in 1996 — the largest mummy find in Egyptian history.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 28.3500, "lng": 28.8667},
     "tags": ["desert", "must-visit", "nature", "photography"], "related_sites": ["black_desert", "white_desert"]},

    {"slug": "farafra_oasis", "name": "Farafra Oasis", "name_ar": "واحة الفرافرة",
     "category": "Natural", "subcategory": "Oases", "region": "New Valley",
     "period": "",
     "description": "The smallest and most isolated of Egypt's oases, gateway to the White Desert. Home to the quirky Badr Museum of local art and the hot springs of Bir Sitta.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 27.0572, "lng": 27.9700},
     "tags": ["desert", "nature", "off-the-beaten-path", "photography"], "related_sites": ["white_desert"]},

    {"slug": "dakhla_oasis", "name": "Dakhla Oasis", "name_ar": "واحة الداخلة",
     "category": "Natural", "subcategory": "Oases", "region": "New Valley",
     "period": "",
     "description": "One of the most picturesque oases with medieval mud-brick town of Al-Qasr, Roman-era Deir el-Hagar temple, and pink-tinted sand dunes.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 25.5000, "lng": 29.0000},
     "tags": ["desert", "nature", "off-the-beaten-path", "photography"], "related_sites": ["kharga_oasis"]},

    {"slug": "kharga_oasis", "name": "Kharga Oasis", "name_ar": "واحة الخارجة",
     "category": "Natural", "subcategory": "Oases", "region": "New Valley",
     "period": "",
     "description": "The largest of Egypt's Western Desert oases and capital of the New Valley Governorate, with the well-preserved Temple of Hibis and Bagawat necropolis.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 25.4500, "lng": 30.5500},
     "tags": ["desert", "nature", "off-the-beaten-path"], "related_sites": ["temple_of_hibis", "dakhla_oasis"]},

    {"slug": "fayoum_oasis", "name": "Fayoum Oasis", "name_ar": "واحة الفيوم",
     "category": "Natural", "subcategory": "Oases", "region": "Fayoum",
     "period": "",
     "description": "Egypt's largest oasis and a fertile agricultural region since pharaonic times, offering waterfalls, whale fossils, ancient pyramids, and ancient lakeside villages.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.3100, "lng": 30.8400},
     "tags": ["desert", "nature", "photography"], "related_sites": ["wadi_el_hitan", "wadi_el_rayan", "lake_qarun"]},

    # ── Coastal & Marine ──
    {"slug": "ras_muhammad", "name": "Ras Mohammed National Park", "name_ar": "محمية رأس محمد",
     "category": "Natural", "subcategory": "Coastal & Marine", "region": "South Sinai",
     "period": "Established 1983",
     "description": "Egypt's first national park at the southern tip of Sinai, featuring spectacular coral reefs teeming with marine life and dramatic cliff landscapes.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 27.7333, "lng": 34.2500},
     "tags": ["must-visit"], "related_sites": ["sharm_el_sheikh"]},

    {"slug": "tiran_island", "name": "Tiran Island", "name_ar": "جزيرة تيران",
     "category": "Natural", "subcategory": "Coastal & Marine", "region": "South Sinai",
     "period": "",
     "description": "A stunning island in the Straits of Tiran renowned for world-class coral reefs and four massive reef systems that attract divers from around the globe.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 27.9500, "lng": 34.5667},
     "tags": ["nature", "photography", "scenic"], "related_sites": ["sharm_el_sheikh"]},

    {"slug": "colored_canyon", "name": "Colored Canyon", "name_ar": "الوادي الملون",
     "category": "Natural", "subcategory": "Mountains & Geological", "region": "South Sinai",
     "period": "35 million years old",
     "description": "A narrow slot canyon with mesmerizing layers of multicolored sandstone in shades of red, gold, purple, and white carved by ancient flash floods.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 28.8667, "lng": 34.5333},
     "tags": ["photography"], "related_sites": ["dahab"]},

    # ── Mountains ──
    {"slug": "mount_sinai", "name": "Mount Sinai (Jabal Musa)", "name_ar": "جبل موسى",
     "category": "Natural", "subcategory": "Mountains & Geological", "region": "South Sinai",
     "period": "",
     "description": "The sacred mountain where Moses is believed to have received the Ten Commandments. A popular sunrise trek offering breathtaking panoramic desert views.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 28.5394, "lng": 33.9753},
     "tags": ["must-visit"], "related_sites": ["saint_catherine_monastery"]},

    {"slug": "el_alamein_war_cemetery", "name": "El Alamein War Cemetery", "name_ar": "مقبرة العلمين",
     "category": "Natural", "subcategory": "Historic Sites", "region": "Matrouh",
     "period": "World War II (1942)",
     "description": "A moving Commonwealth war cemetery and memorial honoring the fallen of the pivotal WWII Battle of El Alamein that turned the tide in North Africa.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.8333, "lng": 28.9500},
     "tags": ["historic", "photography"], "related_sites": []},

    {"slug": "blue_hole_dahab", "name": "Blue Hole", "name_ar": "الحفرة الزرقاء",
     "category": "Natural", "subcategory": "Red Sea", "region": "South Sinai",
     "period": "",
     "description": "One of the world's most famous dive sites — a 130-meter-deep submarine sinkhole in the Red Sea coast near Dahab. Known for its crystalline blue water, dramatic coral walls, and 'The Arch' passage at 56 meters connecting to the open sea. Popular with freedivers and scuba divers of all levels (shallow reef sections are safe for snorkelers), though its depth has earned it a reputation as one of the most dangerous dive sites. The surrounding coral reef is spectacularly healthy and teeming with marine life.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 28.5722, "lng": 34.5381},
     "tags": ["must-visit", "diving", "nature", "unique"], "related_sites": ["dahab", "ras_muhammad"]},

    {"slug": "ain_sukhna", "name": "Ain Sukhna", "name_ar": "العين السخنة",
     "category": "Natural", "subcategory": "Beaches", "region": "Suez",
     "period": "",
     "description": "The closest Red Sea beach resort to Cairo (120 km), Ain Sukhna ('Hot Spring') is named after its natural sulfur hot springs that emerge from Jebel Ataqa. Popular as a weekend getaway for Cairenes, it offers calm turquoise waters, coral reefs for snorkeling, and a chain of modern resorts along the Gulf of Suez coastline. The area also has historical significance — ancient Pharaonic quarries and a port used for expeditions to Punt were discovered nearby.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.6018, "lng": 32.3163},
     "tags": ["beach", "nature", "family-friendly"], "related_sites": ["hurghada"]},

    {"slug": "wadi_degla", "name": "Wadi Degla Protectorate", "name_ar": "محمية وادي دجلة",
     "category": "Natural", "subcategory": "Nature Reserves", "region": "Cairo",
     "period": "Protected since 1999",
     "description": "A stunning desert canyon and nature reserve just 10 minutes from Maadi in Cairo's eastern suburbs. The 60 km² protectorate preserves a dramatic wadi (dry riverbed) with towering limestone cliffs up to 50 meters high, home to Dorcas gazelles, Nubian ibex, foxes, and over 18 species of reptiles. Popular with hikers, cyclists, and trail runners, the main trail follows the wadi floor for 4 km through spectacular geological formations revealing 60 million years of marine fossils.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.9558, "lng": 31.3403},
     "tags": ["nature", "hiking", "photography"], "related_sites": []},
]
