"""Siwa Oasis, White Desert, and other natural wonders — sub-sites."""

SIWA_CHILDREN = [
    {
        "slug": "siwa_temple_of_oracle",
        "name": "Temple of the Oracle (Amun)",
        "name_ar": "معبد الوحي (آمون)",
        "category": "Pharaonic",
        "subcategory": "Tombs & Temples",
        "region": "Western Desert",
        "parent_slug": "siwa_oasis",
        "period": "Late Period (26th Dynasty, c. 6th century BC)",
        "featured": True,
        "description": "The temple where Alexander the Great received confirmation of his divine status in 331 BC. Perched on the rock of Aghurmi, the Oracle of Amun was one of the ancient world's most important — comparable to Delphi in Greece. The remaining walls still show relief fragments of Pharaoh Amasis. The journey through the desert to reach it mirrors Alexander's own perilous march.",
        "has_image": True,
        "coordinates": {"lat": 29.2052, "lng": 25.5390},
        "tags": ["must-visit", "off-the-beaten-path", "archaeological"],
        "related_sites": ["siwa_oasis"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "siwa_cleopatra_spring",
        "name": "Cleopatra's Spring (Ain Juba)",
        "name_ar": "عين كليوباترا",
        "category": "Natural",
        "subcategory": "Oases & Deserts",
        "region": "Western Desert",
        "parent_slug": "siwa_oasis",
        "period": "Natural / Ancient",
        "featured": True,
        "description": "A large natural spring pool fed by underground aquifers, where locals and visitors swim year-round in the bubbling 28°C water. Legend (unsubstantiated) says Cleopatra bathed here. Surrounded by palm trees, it's the social heart of Siwa — best enjoyed at sunset when the palms create dramatic silhouettes.",
        "has_image": True,
        "coordinates": {"lat": 29.2080, "lng": 25.5350},
        "tags": ["relaxation", "photography", "swimming"],
        "related_sites": ["siwa_oasis"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "siwa_shali_fortress",
        "name": "Shali Fortress (Old Town)",
        "name_ar": "قلعة شالي",
        "category": "Islamic",
        "subcategory": "Historic Districts",
        "region": "Western Desert",
        "parent_slug": "siwa_oasis",
        "period": "Medieval (13th century CE)",
        "featured": False,
        "description": "The crumbling mud-brick citadel at the heart of Siwa, built in 1203 CE from kershif (salt-mud) blocks. Rising organically from the rock, its melted-looking towers are a photographers' dream, especially at sunset. Largely abandoned after a 1926 rainstorm dissolved much of the structure. Partially restored, with a mosque and viewpoint accessible.",
        "has_image": True,
        "coordinates": {"lat": 29.2035, "lng": 25.5192},
        "tags": ["photography", "architecture", "off-the-beaten-path"],
        "related_sites": ["siwa_oasis"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "siwa_mountain_of_the_dead",
        "name": "Mountain of the Dead (Gebel al-Mawta)",
        "name_ar": "جبل الموتى",
        "category": "Pharaonic",
        "subcategory": "Tombs & Temples",
        "region": "Western Desert",
        "parent_slug": "siwa_oasis",
        "period": "Late Period – Greco-Roman (26th Dynasty – Roman)",
        "featured": False,
        "description": "A cone-shaped hill riddled with hundreds of rock-cut tombs from the 26th Dynasty through the Roman period. Four painted tombs are open to visitors — the Tomb of Si-Amun features the finest Greco-Egyptian art outside Alexandria. During WWII, locals used the tombs as bomb shelters during the North African campaign.",
        "has_image": True,
        "coordinates": {"lat": 29.2070, "lng": 25.5140},
        "tags": ["off-the-beaten-path", "underground", "art"],
        "related_sites": ["siwa_oasis"],
        "images": [],
        "sections": [],
    },
]


WHITE_DESERT_CHILDREN = [
    {
        "slug": "white_desert_mushroom_rocks",
        "name": "Mushroom Rock Formations",
        "name_ar": "صخور عيش الغراب",
        "category": "Natural",
        "subcategory": "Oases & Deserts",
        "region": "Western Desert",
        "parent_slug": "white_desert",
        "period": "Geological (Cretaceous limestone)",
        "featured": True,
        "description": "Surreal white chalk formations sculpted by wind erosion into shapes resembling giant mushrooms, sphinxes, and animals. Rising from the flat desert floor, these formations glow orange at sunset and gleam under moonlight. The most photographed include the 'Chicken and Tree' and the 'White Sphinx'. Camping among them under a star-blanket sky is an unforgettable desert experience.",
        "has_image": True,
        "coordinates": {"lat": 28.2000, "lng": 28.0000},
        "tags": ["must-visit", "photography", "adventure", "camping"],
        "related_sites": ["white_desert"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "white_desert_crystal_mountain",
        "name": "Crystal Mountain",
        "name_ar": "الجبل الكريستالي",
        "category": "Natural",
        "subcategory": "Oases & Deserts",
        "region": "Western Desert",
        "parent_slug": "white_desert",
        "period": "Geological",
        "featured": False,
        "description": "A small ridge of quartz crystal formations that sparkle in the desert sun between the Black and White Deserts. Not a mountain in the traditional sense but a stunning natural arch and outcrop of calcite crystals. A popular stop on desert safari routes.",
        "has_image": True,
        "coordinates": {"lat": 28.3500, "lng": 28.7000},
        "tags": ["photography", "off-the-beaten-path"],
        "related_sites": ["white_desert"],
        "images": [],
        "sections": [],
    },
]
