# Pharaonic — Pyramids & Necropolises
SITES = [
    {"slug": "great_pyramids_of_giza", "name": "Great Pyramids of Giza", "name_ar": "أهرامات الجيزة الكبرى",
     "category": "Pharaonic", "subcategory": "Pyramids & Necropolises", "region": "Giza",
     "period": "Old Kingdom, 4th Dynasty (~2580-2510 BC)",
     "description": "The last surviving wonder of the ancient world — three monumental pyramids built for pharaohs Khufu, Khafre, and Menkaure on the Giza Plateau.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.9792, "lng": 31.1342},
     "tags": ["UNESCO", "must-visit", "Seven Wonders"], "related_sites": ["great_sphinx_of_giza", "pyramid_of_khafre", "pyramid_of_menkaure"]},

    {"slug": "pyramid_of_khafre", "name": "Pyramid of Khafre", "name_ar": "هرم خفرع",
     "category": "Pharaonic", "subcategory": "Pyramids & Necropolises", "region": "Giza",
     "period": "Old Kingdom, 4th Dynasty (~2570 BC)",
     "description": "The second-largest pyramid at Giza, built for Pharaoh Khafre. Retains some of its original limestone casing at the apex.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.9761, "lng": 31.1308},
     "tags": ["UNESCO"], "related_sites": ["great_pyramids_of_giza", "great_sphinx_of_giza"]},

    {"slug": "pyramid_of_menkaure", "name": "Pyramid of Menkaure", "name_ar": "هرم منكاورع",
     "category": "Pharaonic", "subcategory": "Pyramids & Necropolises", "region": "Giza",
     "period": "Old Kingdom, 4th Dynasty (~2510 BC)",
     "description": "The smallest of the three Giza pyramids, built for Pharaoh Menkaure. Features three subsidiary queen pyramids.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.9725, "lng": 31.1281},
     "tags": ["UNESCO"], "related_sites": ["great_pyramids_of_giza", "pyramid_of_khafre"]},

    {"slug": "pyramid_of_djoser", "name": "Step Pyramid of Djoser", "name_ar": "هرم زوسر المدرج",
     "category": "Pharaonic", "subcategory": "Pyramids & Necropolises", "region": "Giza",
     "period": "Old Kingdom, 3rd Dynasty (~2670 BC)",
     "description": "The world's oldest monumental stone structure, designed by the legendary architect Imhotep for Pharaoh Djoser at Saqqara.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.8713, "lng": 31.2165},
     "tags": ["UNESCO", "must-visit"], "related_sites": ["saqqara_necropolis", "serapeum_of_saqqara"]},

    {"slug": "saqqara_necropolis", "name": "Saqqara Necropolis", "name_ar": "جبانة سقارة",
     "category": "Pharaonic", "subcategory": "Pyramids & Necropolises", "region": "Giza",
     "period": "Old Kingdom to Late Period",
     "description": "A vast burial ground spanning 3,000 years of Egyptian history, containing numerous pyramids, mastabas, and animal necropolises.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.8711, "lng": 31.2161},
     "tags": ["UNESCO"], "related_sites": ["pyramid_of_djoser", "serapeum_of_saqqara", "pyramid_of_unas"]},

    {"slug": "serapeum_of_saqqara", "name": "Serapeum of Saqqara", "name_ar": "سرابيوم سقارة",
     "category": "Pharaonic", "subcategory": "Pyramids & Necropolises", "region": "Giza",
     "period": "New Kingdom to Ptolemaic",
     "description": "Underground gallery containing massive granite sarcophagi of the sacred Apis bulls, weighing up to 70 tons each.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.8687, "lng": 31.2130},
     "tags": ["ancient-architecture", "must-visit"], "related_sites": ["saqqara_necropolis", "pyramid_of_djoser"]},

    {"slug": "pyramid_of_unas", "name": "Pyramid of Unas", "name_ar": "هرم أوناس",
     "category": "Pharaonic", "subcategory": "Pyramids & Necropolises", "region": "Giza",
     "period": "Old Kingdom, 5th Dynasty (~2350 BC)",
     "description": "Contains the oldest known religious texts in the world — the Pyramid Texts — carved into the burial chamber walls.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.8681, "lng": 31.2146},
     "tags": ["ancient-architecture", "off-the-beaten-path"], "related_sites": ["saqqara_necropolis", "pyramid_of_djoser"]},

    {"slug": "mastaba_of_ti", "name": "Mastaba of Ti", "name_ar": "مصطبة تي",
     "category": "Pharaonic", "subcategory": "Pyramids & Necropolises", "region": "Giza",
     "period": "Old Kingdom, 5th Dynasty",
     "description": "One of the finest decorated Old Kingdom tombs, featuring vivid reliefs depicting daily life, farming, and craftsmanship.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.8723, "lng": 31.2178},
     "tags": ["ancient-architecture", "off-the-beaten-path"], "related_sites": ["saqqara_necropolis"]},

    {"slug": "bent_pyramid", "name": "Bent Pyramid", "name_ar": "الهرم المنحني",
     "category": "Pharaonic", "subcategory": "Pyramids & Necropolises", "region": "Giza",
     "period": "Old Kingdom, 4th Dynasty (~2600 BC)",
     "description": "A unique transitional pyramid at Dahshur with a distinctive change in angle midway up, representing the evolution of pyramid construction.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.7903, "lng": 31.2094},
     "tags": ["UNESCO"], "related_sites": ["red_pyramid", "dahshur_necropolis"]},

    {"slug": "red_pyramid", "name": "Red Pyramid", "name_ar": "الهرم الأحمر",
     "category": "Pharaonic", "subcategory": "Pyramids & Necropolises", "region": "Giza",
     "period": "Old Kingdom, 4th Dynasty (~2590 BC)",
     "description": "Egypt's first true smooth-sided pyramid, built by Sneferu at Dahshur. Named for the reddish limestone blocks visible today.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.8091, "lng": 31.2061},
     "tags": ["UNESCO"], "related_sites": ["bent_pyramid", "dahshur_necropolis"]},

    {"slug": "dahshur_necropolis", "name": "Dahshur Necropolis", "name_ar": "جبانة دهشور",
     "category": "Pharaonic", "subcategory": "Pyramids & Necropolises", "region": "Giza",
     "period": "Old Kingdom to Middle Kingdom",
     "description": "Royal necropolis south of Cairo containing five pyramids including the Bent and Red Pyramids of Sneferu.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.8000, "lng": 31.2067},
     "tags": ["UNESCO"], "related_sites": ["bent_pyramid", "red_pyramid"]},

    {"slug": "abu_rawash", "name": "Abu Rawash Pyramid", "name_ar": "هرم أبو رواش",
     "category": "Pharaonic", "subcategory": "Pyramids & Necropolises", "region": "Giza",
     "period": "Old Kingdom, 4th Dynasty",
     "description": "The northernmost Egyptian pyramid, built for Pharaoh Djedefre. Only the foundation remains but offers panoramic views of the Giza Plateau.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.0322, "lng": 31.0747},
     "tags": ["ancient-architecture", "off-the-beaten-path"], "related_sites": ["great_pyramids_of_giza"]},

    {"slug": "meidum_pyramid", "name": "Meidum Pyramid", "name_ar": "هرم ميدوم",
     "category": "Pharaonic", "subcategory": "Pyramids & Necropolises", "region": "Fayoum",
     "period": "Old Kingdom, 3rd-4th Dynasty",
     "description": "A partially collapsed pyramid that marks the transition from step to true pyramids. The exposed core gives it a distinctive tower-like appearance.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.3883, "lng": 31.1571},
     "tags": ["ancient-architecture", "off-the-beaten-path"], "related_sites": ["bent_pyramid"]},

    {"slug": "hawara_pyramid", "name": "Pyramid of Hawara", "name_ar": "هرم هوارة",
     "category": "Pharaonic", "subcategory": "Pyramids & Necropolises", "region": "Fayoum",
     "period": "Middle Kingdom, 12th Dynasty",
     "description": "Built by Amenemhat III, once accompanied by the legendary Labyrinth described by Herodotus as surpassing even the pyramids.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.2724, "lng": 30.8985},
     "tags": ["ancient-architecture", "off-the-beaten-path"], "related_sites": ["lahun_pyramid"]},

    {"slug": "lahun_pyramid", "name": "Pyramid of Lahun", "name_ar": "هرم اللاهون",
     "category": "Pharaonic", "subcategory": "Pyramids & Necropolises", "region": "Fayoum",
     "period": "Middle Kingdom, 12th Dynasty",
     "description": "Built by Senusret II with an innovative internal structure. The nearby workers' village (Kahun) provided invaluable insights into daily life.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.2350, "lng": 30.9700},
     "tags": ["ancient-architecture", "off-the-beaten-path"], "related_sites": ["hawara_pyramid"]},
]
