# Pharaonic — Ancient Cities & Sites
SITES = [
    {"slug": "ancient_thebes", "name": "Ancient Thebes (Luxor)", "name_ar": "طيبة القديمة",
     "category": "Pharaonic", "subcategory": "Ancient Cities", "region": "Luxor",
     "period": "Middle Kingdom to Late Period",
     "description": "The ancient capital of Upper Egypt and religious center of Amun worship, encompassing modern Luxor and its extraordinary concentration of temples and tombs.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 25.6969, "lng": 32.6422},
     "tags": ["UNESCO"], "related_sites": ["karnak_temple", "luxor_temple", "valley_of_the_kings"]},

    {"slug": "tell_el_amarna", "name": "Tell el-Amarna (Akhetaten)", "name_ar": "تل العمارنة",
     "category": "Pharaonic", "subcategory": "Ancient Cities", "region": "Minya",
     "period": "New Kingdom, 18th Dynasty (~1346 BC)",
     "description": "The short-lived capital of the heretic pharaoh Akhenaten, where monotheistic sun worship replaced traditional gods. Birthplace of revolutionary Amarna art style.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 27.6453, "lng": 30.8965},
     "tags": ["archaeological", "off-the-beaten-path"], "related_sites": ["beni_hasan"]},

    {"slug": "elephantine_island", "name": "Elephantine Island", "name_ar": "جزيرة الفنتين",
     "category": "Pharaonic", "subcategory": "Ancient Cities", "region": "Aswan",
     "period": "Predynastic to Roman",
     "description": "An island in the Nile at Aswan that was the ancient frontier town and cult center of the ram-headed god Khnum. Features a Nilometer for measuring annual floods.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 24.0847, "lng": 32.8863},
     "tags": ["archaeological", "off-the-beaten-path"], "related_sites": ["philae_temple", "kitchener_island_aswan"]},

    {"slug": "tanis", "name": "Tanis (San el-Hagar)", "name_ar": "تانيس – صان الحجر",
     "category": "Pharaonic", "subcategory": "Ancient Cities", "region": "Sharqia",
     "period": "Third Intermediate Period (1070-712 BC)",
     "description": "Capital of Egypt during the 21st-22nd Dynasties. The royal tombs here contained treasures rivaling Tutankhamun's, discovered intact in 1939.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.9780, "lng": 31.8810},
     "tags": ["archaeological", "off-the-beaten-path"], "related_sites": ["per_ramesses"]},

    {"slug": "per_ramesses", "name": "Pi-Ramesses", "name_ar": "بر رمسيس",
     "category": "Pharaonic", "subcategory": "Ancient Cities", "region": "Sharqia",
     "period": "New Kingdom, 19th Dynasty",
     "description": "The great capital of Ramesses II in the Delta, one of the largest cities of the ancient world with an estimated population of 300,000.",
     "has_image": False, "has_coordinates": True,
     "coordinates": {"lat": 30.8000, "lng": 31.8333},
     "tags": ["archaeological", "off-the-beaten-path"], "related_sites": ["tanis"]},

    {"slug": "bubastis", "name": "Bubastis (Tell Basta)", "name_ar": "بوباسطيس – تل بسطة",
     "category": "Pharaonic", "subcategory": "Ancient Cities", "region": "Sharqia",
     "period": "Old Kingdom to Roman",
     "description": "The cult center of the cat goddess Bastet, where massive feline festivals drew hundreds of thousands of pilgrims from across Egypt.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 30.5700, "lng": 31.5150},
     "tags": ["archaeological", "off-the-beaten-path"], "related_sites": ["tanis"]},

    {"slug": "crocodilopolis", "name": "Crocodilopolis (Medinet el-Fayoum)", "name_ar": "مدينة التماسيح",
     "category": "Pharaonic", "subcategory": "Ancient Cities", "region": "Fayoum",
     "period": "Middle Kingdom to Roman",
     "description": "The cult center of the crocodile god Sobek in the Fayoum Oasis, where sacred crocodiles were adorned with gold and jewels.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.3100, "lng": 30.8400},
     "tags": ["archaeological", "off-the-beaten-path"], "related_sites": ["hawara_pyramid", "fayoum_oasis"]},

    {"slug": "rosetta_city", "name": "Rosetta (Rashid)", "name_ar": "رشيد",
     "category": "Pharaonic", "subcategory": "Ancient Cities", "region": "Beheira",
     "period": "Islamic to Ottoman",
     "description": "The city where the famous Rosetta Stone was discovered in 1799, enabling the decipherment of Egyptian hieroglyphs. Features beautiful Ottoman-era houses.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 31.4053, "lng": 30.4167},
     "tags": ["archaeological", "off-the-beaten-path"], "related_sites": ["bibliotheca_alexandrina"]},
]
