# Pharaonic — Temples
SITES = [
    {"slug": "karnak_temple", "name": "Karnak Temple Complex", "name_ar": "معبد الكرنك",
     "category": "Pharaonic", "subcategory": "Temples", "region": "Luxor",
     "period": "Middle Kingdom to Ptolemaic (~2000-30 BC)",
     "description": "The largest ancient religious complex in the world, spanning 2,000 years of construction with the awe-inspiring Hypostyle Hall of 134 massive columns.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 25.7188, "lng": 32.6573},
     "tags": ["UNESCO", "must-visit"], "related_sites": ["luxor_temple", "avenue_of_sphinxes"]},

    {"slug": "luxor_temple", "name": "Luxor Temple", "name_ar": "معبد الأقصر",
     "category": "Pharaonic", "subcategory": "Temples", "region": "Luxor",
     "period": "New Kingdom (~1400 BC)",
     "description": "A majestic temple on the east bank of the Nile dedicated to the Theban Triad, spectacularly illuminated at night.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 25.6996, "lng": 32.6392},
     "tags": ["UNESCO", "must-visit"], "related_sites": ["karnak_temple", "avenue_of_sphinxes"]},

    {"slug": "abu_simbel", "name": "Abu Simbel Temples", "name_ar": "معابد أبو سمبل",
     "category": "Pharaonic", "subcategory": "Temples", "region": "Aswan",
     "period": "New Kingdom, 19th Dynasty (~1264 BC)",
     "description": "Two massive rock-cut temples built by Ramesses II, famously relocated in the 1960s to save them from Lake Nasser's rising waters. The sun illuminates the inner sanctuary twice yearly.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 22.3360, "lng": 31.6258},
     "tags": ["UNESCO", "must-visit"], "related_sites": ["philae_temple", "lake_nasser"]},

    {"slug": "temple_of_hatshepsut", "name": "Temple of Hatshepsut", "name_ar": "معبد حتشبسوت",
     "category": "Pharaonic", "subcategory": "Temples", "region": "Luxor",
     "period": "New Kingdom, 18th Dynasty (~1470 BC)",
     "description": "A stunning terraced mortuary temple at Deir el-Bahari, built for Egypt's most powerful female pharaoh against dramatic limestone cliffs.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 25.7381, "lng": 32.6067},
     "tags": ["UNESCO", "must-visit"], "related_sites": ["valley_of_the_kings", "deir_el_medina"]},

    {"slug": "dendera_temple", "name": "Dendera Temple Complex", "name_ar": "معبد دندرة",
     "category": "Pharaonic", "subcategory": "Temples", "region": "Qena",
     "period": "Ptolemaic to Roman",
     "description": "One of the best-preserved temple complexes in Egypt, dedicated to Hathor. Features the famous zodiac ceiling and remarkably intact colors.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 26.1425, "lng": 32.6701},
     "tags": ["photography"], "related_sites": ["abydos_temple"]},

    {"slug": "edfu_temple", "name": "Temple of Horus at Edfu", "name_ar": "معبد حورس بإدفو",
     "category": "Pharaonic", "subcategory": "Temples", "region": "Aswan",
     "period": "Ptolemaic (237-57 BC)",
     "description": "The best-preserved ancient temple in Egypt, dedicated to the falcon god Horus. Its massive pylon entrance stands nearly 36 meters tall.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 24.9779, "lng": 32.8734},
     "tags": ["must-visit"], "related_sites": ["kom_ombo_temple"]},

    {"slug": "kom_ombo_temple", "name": "Temple of Kom Ombo", "name_ar": "معبد كوم أمبو",
     "category": "Pharaonic", "subcategory": "Temples", "region": "Aswan",
     "period": "Ptolemaic (180-47 BC)",
     "description": "A unique double temple dedicated to both Sobek the crocodile god and Haroeris the falcon god, perched above the Nile with a mummified crocodile museum.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 24.4520, "lng": 32.9284},
     "tags": ["UNESCO", "ancient-architecture"], "related_sites": ["edfu_temple", "philae_temple"]},

    {"slug": "philae_temple", "name": "Philae Temple (Temple of Isis)", "name_ar": "معبد فيلة",
     "category": "Pharaonic", "subcategory": "Temples", "region": "Aswan",
     "period": "Ptolemaic to Roman",
     "description": "A beautiful island temple dedicated to the goddess Isis, relocated to Agilkia Island to save it from flooding. Features a stunning sound and light show.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 24.0226, "lng": 32.8841},
     "tags": ["UNESCO", "must-visit"], "related_sites": ["aswan_high_dam", "unfinished_obelisk"]},

    {"slug": "abydos_temple", "name": "Temple of Seti I at Abydos", "name_ar": "معبد سيتي الأول بأبيدوس",
     "category": "Pharaonic", "subcategory": "Temples", "region": "Sohag",
     "period": "New Kingdom, 19th Dynasty (~1280 BC)",
     "description": "Sacred pilgrimage center containing the famous Kings List and some of the finest relief carvings in all of Egypt, with remarkably preserved colors.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 26.1853, "lng": 31.9190},
     "tags": ["UNESCO", "ancient-architecture"], "related_sites": ["dendera_temple"]},

    {"slug": "medinet_habu", "name": "Medinet Habu", "name_ar": "مدينة هابو",
     "category": "Pharaonic", "subcategory": "Temples", "region": "Luxor",
     "period": "New Kingdom, 20th Dynasty (~1150 BC)",
     "description": "The mortuary temple of Ramesses III, featuring massive walls covered with vivid battle scenes and the best-preserved royal palace in Thebes.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 25.7188, "lng": 32.6009},
     "tags": ["ancient-architecture", "must-visit"], "related_sites": ["valley_of_the_kings", "ramesseum"]},

    {"slug": "ramesseum", "name": "Ramesseum", "name_ar": "الرامسيوم",
     "category": "Pharaonic", "subcategory": "Temples", "region": "Luxor",
     "period": "New Kingdom, 19th Dynasty",
     "description": "The mortuary temple of Ramesses II on the west bank of Luxor, with the remains of a colossal fallen statue that inspired Shelley's poem Ozymandias.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 25.7282, "lng": 32.6107},
     "tags": ["ancient-architecture", "must-visit"], "related_sites": ["medinet_habu", "colossi_of_memnon"]},

    {"slug": "esna_temple", "name": "Temple of Khnum at Esna", "name_ar": "معبد خنوم بإسنا",
     "category": "Pharaonic", "subcategory": "Temples", "region": "Luxor",
     "period": "Ptolemaic to Roman",
     "description": "An exceptionally well-preserved hypostyle hall dedicated to the ram-headed god Khnum, recently restored to reveal its original vivid colors.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 25.2921, "lng": 32.5539},
     "tags": ["ancient-architecture", "off-the-beaten-path"], "related_sites": ["edfu_temple"]},

    {"slug": "kalabsha_temple", "name": "Temple of Kalabsha", "name_ar": "معبد كلابشة",
     "category": "Pharaonic", "subcategory": "Temples", "region": "Aswan",
     "period": "Roman Period (~30 BC)",
     "description": "The largest free-standing temple in Nubia, relocated near the Aswan High Dam. Dedicated to the Nubian sun god Mandulis.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 23.9633, "lng": 32.8700},
     "tags": ["ancient-architecture", "must-visit"], "related_sites": ["philae_temple", "aswan_high_dam"]},

    {"slug": "temple_of_hibis", "name": "Temple of Hibis", "name_ar": "معبد هيبس",
     "category": "Pharaonic", "subcategory": "Temples", "region": "New Valley",
     "period": "Late Period, 26th-27th Dynasty",
     "description": "The best-preserved temple from the Late Period, located in the Kharga Oasis. One of the few temples built during Persian rule of Egypt.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 25.4667, "lng": 30.5667},
     "tags": ["ancient-architecture", "off-the-beaten-path"], "related_sites": ["kharga_oasis"]},

    {"slug": "avenue_of_sphinxes", "name": "Avenue of Sphinxes", "name_ar": "طريق الكباش",
     "category": "Pharaonic", "subcategory": "Temples", "region": "Luxor",
     "period": "New Kingdom (~1400 BC)",
     "description": "A 2.7 km processional road lined with sphinx statues connecting Karnak and Luxor temples, recently restored and reopened after decades of excavation.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 25.7100, "lng": 32.6500},
     "tags": ["must-visit"], "related_sites": ["karnak_temple", "luxor_temple"]},

    {"slug": "temple_of_amada", "name": "Temple of Amada", "name_ar": "معبد أمادا",
     "category": "Pharaonic", "subcategory": "Temples", "region": "Aswan",
     "period": "New Kingdom, 18th Dynasty",
     "description": "The oldest Egyptian temple in Nubia, with some of the finest and sharpest relief work found in any Nubian monument.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 22.7330, "lng": 32.2461},
     "tags": ["ancient-architecture", "off-the-beaten-path"], "related_sites": ["abu_simbel", "wadi_el_sebua"]},

    {"slug": "wadi_el_sebua", "name": "Wadi el-Sebua Temple", "name_ar": "معبد وادي السبوع",
     "category": "Pharaonic", "subcategory": "Temples", "region": "Aswan",
     "period": "New Kingdom, 19th Dynasty",
     "description": "A rock-cut temple built by Ramesses II in Nubia, preceded by an avenue of sphinx statues. Relocated due to the Aswan Dam project.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 22.7917, "lng": 32.5417},
     "tags": ["ancient-architecture", "off-the-beaten-path"], "related_sites": ["abu_simbel", "temple_of_amada"]},
]
