# Pharaonic — Tombs & Valleys
SITES = [
    {"slug": "valley_of_the_kings", "name": "Valley of the Kings", "name_ar": "وادي الملوك",
     "category": "Pharaonic", "subcategory": "Tombs & Valleys", "region": "Luxor",
     "period": "New Kingdom (1539-1075 BC)",
     "description": "The royal burial ground of Egypt's New Kingdom pharaohs, containing 63 decorated tombs including Tutankhamun's famous treasure-filled tomb.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 25.7402, "lng": 32.6014},
     "tags": ["UNESCO", "must-visit"], "related_sites": ["valley_of_the_queens", "temple_of_hatshepsut", "tomb_of_tutankhamun"]},

    {"slug": "valley_of_the_queens", "name": "Valley of the Queens", "name_ar": "وادي الملكات",
     "category": "Pharaonic", "subcategory": "Tombs & Valleys", "region": "Luxor",
     "period": "New Kingdom",
     "description": "The burial place of queens and royal children, featuring the breathtaking tomb of Nefertari with its perfectly preserved colorful paintings.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 25.7264, "lng": 32.5972},
     "tags": ["UNESCO"], "related_sites": ["valley_of_the_kings", "tomb_of_nefertari"]},

    {"slug": "tomb_of_tutankhamun", "name": "Tomb of Tutankhamun (KV62)", "name_ar": "مقبرة توت عنخ آمون",
     "category": "Pharaonic", "subcategory": "Tombs & Valleys", "region": "Luxor",
     "period": "New Kingdom, 18th Dynasty (~1323 BC)",
     "description": "The most famous archaeological discovery in history, found nearly intact by Howard Carter in 1922 with over 5,000 treasures including the iconic gold death mask.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 25.7401, "lng": 32.6013},
     "tags": ["must-visit"], "related_sites": ["valley_of_the_kings", "grand_egyptian_museum"]},

    {"slug": "tomb_of_nefertari", "name": "Tomb of Nefertari (QV66)", "name_ar": "مقبرة نفرتاري",
     "category": "Pharaonic", "subcategory": "Tombs & Valleys", "region": "Luxor",
     "period": "New Kingdom, 19th Dynasty",
     "description": "Called the Sistine Chapel of Ancient Egypt, this tomb features the most beautiful and well-preserved wall paintings in any Egyptian tomb.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 25.7264, "lng": 32.5972},
     "tags": ["photography"], "related_sites": ["valley_of_the_queens", "abu_simbel"]},

    {"slug": "tomb_of_seti_i", "name": "Tomb of Seti I (KV17)", "name_ar": "مقبرة سيتي الأول",
     "category": "Pharaonic", "subcategory": "Tombs & Valleys", "region": "Luxor",
     "period": "New Kingdom, 19th Dynasty",
     "description": "The longest and deepest tomb in the Valley of the Kings, with extraordinarily detailed astronomical ceiling paintings and religious scenes.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 25.7406, "lng": 32.6018},
     "tags": ["must-visit", "underground"], "related_sites": ["valley_of_the_kings", "abydos_temple"]},

    {"slug": "tombs_of_the_nobles_luxor", "name": "Tombs of the Nobles", "name_ar": "مقابر النبلاء",
     "category": "Pharaonic", "subcategory": "Tombs & Valleys", "region": "Luxor",
     "period": "New Kingdom",
     "description": "Over 400 tombs of ancient Egyptian officials and nobles, offering intimate glimpses of daily life, banquets, farming, and religious rituals.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 25.7333, "lng": 32.6100},
     "tags": ["must-visit", "underground"], "related_sites": ["valley_of_the_kings", "deir_el_medina"]},

    {"slug": "deir_el_medina", "name": "Deir el-Medina", "name_ar": "دير المدينة",
     "category": "Pharaonic", "subcategory": "Tombs & Valleys", "region": "Luxor",
     "period": "New Kingdom",
     "description": "The village of the artisans who built the royal tombs. One of the most thoroughly documented communities from the ancient world.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 25.7281, "lng": 32.6019},
     "tags": ["must-visit", "underground"], "related_sites": ["valley_of_the_kings", "valley_of_the_queens"]},

    {"slug": "beni_hasan", "name": "Beni Hasan Tombs", "name_ar": "مقابر بني حسن",
     "category": "Pharaonic", "subcategory": "Tombs & Valleys", "region": "Minya",
     "period": "Middle Kingdom, 11th-12th Dynasty",
     "description": "Rock-cut tombs of Middle Kingdom provincial governors featuring unique wrestling scenes and the earliest known depiction of a desert caravan.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 27.9294, "lng": 30.8831},
     "tags": ["off-the-beaten-path", "underground"], "related_sites": ["tell_el_amarna"]},
]
