# Pharaonic — Monuments & Statues
SITES = [
    {"slug": "great_sphinx_of_giza", "name": "Great Sphinx of Giza", "name_ar": "أبو الهول",
     "category": "Pharaonic", "subcategory": "Monuments & Statues", "region": "Giza",
     "period": "Old Kingdom, 4th Dynasty (~2500 BC)",
     "description": "The largest and oldest monumental sculpture in the world — a limestone statue with the body of a lion and head of a pharaoh, guarding the Giza Plateau.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.9753, "lng": 31.1376},
     "tags": ["UNESCO", "must-visit"], "related_sites": ["great_pyramids_of_giza"]},

    {"slug": "colossi_of_memnon", "name": "Colossi of Memnon", "name_ar": "تمثالا ممنون",
     "category": "Pharaonic", "subcategory": "Monuments & Statues", "region": "Luxor",
     "period": "New Kingdom, 18th Dynasty (~1350 BC)",
     "description": "Two massive stone statues of Pharaoh Amenhotep III, each standing 18 meters tall, once guarding the entrance to his now-vanished mortuary temple.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 25.7205, "lng": 32.6105},
     "tags": ["must-visit"], "related_sites": ["valley_of_the_kings", "medinet_habu"]},

    {"slug": "unfinished_obelisk", "name": "Unfinished Obelisk", "name_ar": "المسلة الناقصة",
     "category": "Pharaonic", "subcategory": "Monuments & Statues", "region": "Aswan",
     "period": "New Kingdom, 18th Dynasty",
     "description": "The largest known ancient obelisk, abandoned in the Aswan quarries after a crack appeared. Would have stood 42 meters tall and weighed 1,168 tons.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 24.0750, "lng": 32.8972},
     "tags": ["ancient-architecture", "must-visit"], "related_sites": ["philae_temple", "nubia_museum"]},

    {"slug": "memphis_ruins", "name": "Memphis Open Air Museum", "name_ar": "متحف ممفيس المفتوح",
     "category": "Pharaonic", "subcategory": "Monuments & Statues", "region": "Giza",
     "period": "Old Kingdom to Late Period",
     "description": "The ruins of Egypt's first capital, featuring a colossal fallen statue of Ramesses II and an alabaster sphinx. Once the most important city in the ancient world.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.8484, "lng": 31.2548},
     "tags": ["UNESCO"], "related_sites": ["saqqara_necropolis", "pyramid_of_djoser"]},

    {"slug": "nubian_monuments", "name": "Nubian Monuments", "name_ar": "آثار النوبة",
     "category": "Pharaonic", "subcategory": "Monuments & Statues", "region": "Aswan",
     "period": "Various periods",
     "description": "A collection of ancient monuments in Lower Nubia, many relocated during the UNESCO campaign to save them from Lake Nasser's waters.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 23.5000, "lng": 32.5000},
     "tags": ["UNESCO"], "related_sites": ["abu_simbel", "philae_temple"]},

    {"slug": "qasr_ibrim", "name": "Qasr Ibrim", "name_ar": "قصر إبريم",
     "category": "Pharaonic", "subcategory": "Monuments & Statues", "region": "Aswan",
     "period": "New Kingdom to Ottoman",
     "description": "The only major archaeological site in Lower Nubia that survived the flooding of Lake Nasser, now on a small island. Spans 3,000 years of occupation.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 22.6500, "lng": 31.9833},
     "tags": ["ancient-architecture", "off-the-beaten-path"], "related_sites": ["abu_simbel"]},

    {"slug": "aga_khan_mausoleum", "name": "Aga Khan Mausoleum", "name_ar": "ضريح الآغا خان",
     "category": "Pharaonic", "subcategory": "Monuments & Statues", "region": "Aswan",
     "period": "Modern (1957)",
     "description": "A stunning pink limestone mausoleum on the west bank of the Nile in Aswan, built for Aga Khan III (Sultan Muhammad Shah), the 48th Imam of the Ismaili Muslims who loved Aswan and spent winters there. The elegant Fatimid-style domed tomb is modeled on the tombs of the Fatimid Caliphs in Cairo. A single red rose was placed on the white marble sarcophagus every day by his widow, the Begum, until her death in 2000. The hilltop location offers spectacular panoramic views of the Nile, Elephantine Island, and the surrounding desert.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 24.0850, "lng": 32.8783},
     "tags": ["architecture", "photography", "scenic"], "related_sites": ["elephantine_island", "kitchener_island_aswan"]},

    {"slug": "tombs_of_the_nobles_aswan", "name": "Tombs of the Nobles (Aswan)", "name_ar": "مقابر النبلاء بأسوان",
     "category": "Pharaonic", "subcategory": "Monuments & Statues", "region": "Aswan",
     "period": "Old Kingdom to Ptolemaic",
     "description": "A hillside necropolis on the west bank of the Nile at Aswan containing over 80 rock-cut tombs of provincial governors, priests, and military leaders from the Old Kingdom through the Ptolemaic period. The most notable tombs include those of Mekhu and Sabni (6th Dynasty), whose biographical inscriptions tell of daring expeditions into Nubia, and Sirenput I and II with beautifully painted scenes of daily life and offerings. The site offers magnificent views over the Nile and access by local ferry.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 24.1000, "lng": 32.8917},
     "tags": ["off-the-beaten-path", "photography"], "related_sites": ["aga_khan_mausoleum", "elephantine_island"]},
]
