# Resort & Beach Destinations
SITES = [
    {"slug": "sharm_el_sheikh", "name": "Sharm El Sheikh", "name_ar": "شرم الشيخ",
     "category": "Resort", "subcategory": "Red Sea", "region": "South Sinai",
     "period": "",
     "description": "Egypt's premier Red Sea resort city, famed for crystal-clear waters, world-class diving, vibrant nightlife, and proximity to Ras Mohammed National Park.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 27.9158, "lng": 34.3300},
     "tags": ["must-visit"], "related_sites": ["ras_muhammad", "tiran_island"]},

    {"slug": "hurghada", "name": "Hurghada", "name_ar": "الغردقة",
     "category": "Resort", "subcategory": "Red Sea", "region": "Red Sea",
     "period": "",
     "description": "A major Red Sea resort town offering some of Egypt's best coral reefs, beach resorts, and marine activities including snorkeling with dolphins.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 27.2579, "lng": 33.8116},
     "tags": ["beach", "diving", "must-visit", "photography"], "related_sites": ["sharm_el_sheikh"]},

    {"slug": "dahab", "name": "Dahab", "name_ar": "دهب",
     "category": "Resort", "subcategory": "Red Sea", "region": "South Sinai",
     "period": "",
     "description": "A laid-back Bedouin coastal town beloved by backpackers and divers, home to the famous Blue Hole — one of the world's most iconic dive sites.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 28.5000, "lng": 34.5167},
     "tags": ["beach", "diving", "must-visit", "photography"], "related_sites": ["colored_canyon", "mount_sinai"]},

    {"slug": "ain_sokhna", "name": "Ain Sokhna", "name_ar": "العين السخنة",
     "category": "Resort", "subcategory": "Red Sea", "region": "Suez",
     "period": "",
     "description": "Cairo's nearest beach getaway on the Gulf of Suez, popular for weekend escapes with warm natural springs, beach resorts, and clear Red Sea waters.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.5922, "lng": 32.3189},
     "tags": ["beach", "diving", "photography"], "related_sites": ["suez_canal"]},

    {"slug": "nuweiba", "name": "Nuweiba", "name_ar": "نويبع",
     "category": "Resort", "subcategory": "Red Sea", "region": "South Sinai",
     "period": "",
     "description": "A quiet coastal town on the Gulf of Aqaba with pristine beaches, eco-lodges, and a relaxed Bedouin vibe far from the tourist crowds.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.0417, "lng": 34.6667},
     "tags": ["beach", "diving", "off-the-beaten-path", "photography"], "related_sites": ["dahab", "taba"]},

    {"slug": "taba", "name": "Taba", "name_ar": "طابا",
     "category": "Resort", "subcategory": "Red Sea", "region": "South Sinai",
     "period": "",
     "description": "A border resort town at the northern tip of the Gulf of Aqaba, offering dramatic mountain-meets-sea scenery and proximity to Pharaoh's Island castle.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 29.4917, "lng": 34.8833},
     "tags": ["beach", "diving", "off-the-beaten-path", "photography"], "related_sites": ["nuweiba"]},

    {"slug": "el_gouna", "name": "El Gouna", "name_ar": "الجونة",
     "category": "Resort", "subcategory": "Red Sea", "region": "Red Sea",
     "period": "Established 1990s",
     "description": "A self-contained luxury resort town 25 km north of Hurghada, built by Egyptian billionaire Samih Sawiris. Designed around lagoons and islands connected by bridges, it offers upscale hotels, a marina, golf course, international restaurants, and vibrant nightlife. Known for its annual film festival and kite-surfing scene, El Gouna is one of the Red Sea's most exclusive destinations.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 27.1828, "lng": 33.6814},
     "tags": ["beach", "luxury", "nightlife"], "related_sites": ["hurghada"]},

    {"slug": "marsa_alam", "name": "Marsa Alam", "name_ar": "مرسى علم",
     "category": "Resort", "subcategory": "Red Sea", "region": "Red Sea",
     "period": "",
     "description": "An emerging Red Sea destination south of Hurghada, celebrated for pristine coral reefs, swimming with wild dolphins at Samadai Reef (Dolphin House), sea turtle encounters, and the chance to spot dugongs — one of the rarest marine mammals. Less developed than Hurghada or Sharm, it offers a more authentic diving experience with some of Egypt's healthiest reefs.",
     "has_image": True, "has_coordinates": True,
     "coordinates": {"lat": 25.0679, "lng": 34.8989},
     "tags": ["beach", "diving", "off-the-beaten-path"], "related_sites": ["hurghada"]},
]
