"""Saqqara necropolis — sub-sites."""

SAQQARA_CHILDREN = [
    {
        "slug": "saqqara_step_pyramid",
        "name": "Step Pyramid of Djoser",
        "name_ar": "الهرم المدرج لزوسر",
        "category": "Pharaonic",
        "subcategory": "Pyramids & Necropolises",
        "region": "Giza",
        "parent_slug": "saqqara_necropolis",
        "period": "Old Kingdom (3rd Dynasty, c. 2670 BC)",
        "featured": True,
        "description": "The world's first monumental stone building, designed by the legendary architect Imhotep. Rising 62 meters in six tiers, it revolutionized architecture by translating mud-brick forms into limestone. After a 14-year restoration (completed 2020), visitors can now enter the burial shaft 28 meters underground. The surrounding mortuary complex features the Heb-Sed court and the 'House of the North' with proto-Doric columns.",
        "has_image": True,
        "coordinates": {"lat": 29.8713, "lng": 31.2164},
        "tags": ["must-visit", "iconic", "underground"],
        "related_sites": ["saqqara"],
        "images": [],
        "sections": [
            {"title": "Imhotep's Innovation", "content": "Imhotep stacked six mastabas of decreasing size, creating history's first pyramid. He was later deified as a god of medicine and wisdom — the only commoner-to-god in Egyptian history."},
            {"title": "Underground Chambers", "content": "Beneath the pyramid lies a labyrinth of tunnels totaling 5.7 km. The king's burial chamber is carved from a single block of Aswan granite. Blue faience tiles decorating the chambers imitate reed matting."},
        ],
    },
    {
        "slug": "saqqara_serapeum",
        "name": "Serapeum (Bull Catacombs)",
        "name_ar": "السرابيوم",
        "category": "Pharaonic",
        "subcategory": "Tombs & Temples",
        "region": "Giza",
        "parent_slug": "saqqara_necropolis",
        "period": "New Kingdom to Ptolemaic (c. 1390–30 BC)",
        "featured": True,
        "description": "An underground gallery where the sacred Apis bulls — believed to be incarnations of the god Ptah — were mummified and entombed in massive granite sarcophagi. Discovered by Auguste Mariette in 1851, the main gallery stretches 350 meters with 24 enormous sarcophagi, each weighing 60–80 tons. How they were moved into position remains a mystery.",
        "has_image": True,
        "coordinates": {"lat": 29.8680, "lng": 31.2120},
        "tags": ["must-visit", "underground", "mysterious"],
        "related_sites": ["saqqara", "saqqara_step_pyramid"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "saqqara_mastaba_of_ti",
        "name": "Mastaba of Ti",
        "name_ar": "مصطبة تي",
        "category": "Pharaonic",
        "subcategory": "Tombs & Temples",
        "region": "Giza",
        "parent_slug": "saqqara_necropolis",
        "period": "Old Kingdom (5th Dynasty, c. 2450 BC)",
        "featured": False,
        "description": "One of the finest decorated tombs in Egypt, belonging to Ti, a high official who oversaw royal barbers, manicurists, and the sun temples. Its wall reliefs are a masterclass in Old Kingdom art — vivid scenes of daily life including farming, fishing, boat-building, and market trading. The serdab contains a life-like statue of Ti peering through viewing slots.",
        "has_image": True,
        "coordinates": {"lat": 29.8700, "lng": 31.2140},
        "tags": ["off-the-beaten-path", "art"],
        "related_sites": ["saqqara"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "saqqara_pyramid_of_unas",
        "name": "Pyramid of Unas",
        "name_ar": "هرم أوناس",
        "category": "Pharaonic",
        "subcategory": "Pyramids & Necropolises",
        "region": "Giza",
        "parent_slug": "saqqara_necropolis",
        "period": "Old Kingdom (5th Dynasty, c. 2345 BC)",
        "featured": False,
        "description": "The smallest of the Old Kingdom royal pyramids at Saqqara, but historically the most important — it contains the oldest known religious texts in the world: the Pyramid Texts. These 283 spells carved into the walls of the burial chamber were meant to help the king in the afterlife and became the basis for all later funerary literature including the Book of the Dead.",
        "has_image": True,
        "coordinates": {"lat": 29.8685, "lng": 31.2165},
        "tags": ["off-the-beaten-path", "underground"],
        "related_sites": ["saqqara", "saqqara_step_pyramid"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "saqqara_imhotep_museum",
        "name": "Imhotep Museum",
        "name_ar": "متحف إيمحوتب",
        "category": "Museum",
        "subcategory": "Antiquities Museums",
        "region": "Giza",
        "parent_slug": "saqqara_necropolis",
        "period": "Modern (opened 2006)",
        "featured": False,
        "description": "A modern museum at Saqqara's entrance housing artifacts from the necropolis including Djoser's blue faience tiles, Greco-Roman mummies, beautifully painted sarcophagi, and the tools of Egyptologist Jean-Philippe Lauer who spent 75 years restoring the Step Pyramid. Named after the architect of the Step Pyramid.",
        "has_image": True,
        "coordinates": {"lat": 29.8710, "lng": 31.2175},
        "tags": ["museum", "family-friendly"],
        "related_sites": ["saqqara", "saqqara_step_pyramid"],
        "images": [],
        "sections": [],
    },
]
