"""Philae Temple Complex — sub-sites."""

PHILAE_CHILDREN = [
    {
        "slug": "philae_temple_of_isis",
        "name": "Temple of Isis",
        "name_ar": "معبد إيزيس",
        "category": "Pharaonic",
        "subcategory": "Temples",
        "region": "Aswan",
        "parent_slug": "philae_temple",
        "period": "Ptolemaic (c. 380–30 BC)",
        "featured": True,
        "description": "The main and largest temple on Philae island, dedicated to the goddess Isis — one of the last places where ancient Egyptian religion was practiced (temple closed officially in 537 AD by Justinian). Features a massive first pylon with reliefs of Ptolemy XII smiting enemies, a beautiful birth house (mammisi), hypostyle hall with floral columns, and an inner sanctuary where the sacred barque of Isis was kept. The entire complex was rescued from Nile flooding by UNESCO in the 1960s-70s, moved block by block to higher ground on Agilkia Island.",
        "has_image": True,
        "coordinates": {"lat": 24.0262, "lng": 32.8841},
        "tags": ["must-visit", "iconic"],
        "related_sites": ["kalabsha_temple", "unfinished_obelisk"],
        "images": [],
        "sections": [
            {"title": "First Pylon", "content": "The monumental gateway (18 meters high) decorated with colossal reliefs of Ptolemy XII Neos Dionysos making offerings to the gods, flanked by two granite lions."},
            {"title": "Birth House (Mammisi)", "content": "Dedicated to the birth of Horus, son of Isis and Osiris. Reliefs show the divine birth narrative and nursing scenes, surrounded by Hathor-headed columns."},
            {"title": "The UNESCO Rescue", "content": "Between 1960 and 1980, the entire temple complex was dismantled and reassembled on Agilkia Island (reshaped to match original Philae) to save it from permanent submersion by the Aswan High Dam."},
        ],
    },
    {
        "slug": "philae_kiosk_of_trajan",
        "name": "Kiosk of Trajan",
        "name_ar": "كشك تراجان",
        "category": "Pharaonic",
        "subcategory": "Temples",
        "region": "Aswan",
        "parent_slug": "philae_temple",
        "period": "Roman (c. 100 AD)",
        "featured": True,
        "description": "An iconic open-roofed Roman-era kiosk (sometimes called 'Pharaoh's Bed') on the eastern shore of the island, built under Emperor Trajan. Its 14 massive columns with elaborate floral capitals, connected by screen walls with reliefs of Trajan making offerings to Isis and Osiris, make it one of the most photographed monuments in Egypt. Though never completed, it served as a formal entrance for visitors arriving by boat.",
        "has_image": True,
        "coordinates": {"lat": 24.0262, "lng": 32.8841},
        "tags": ["iconic", "architecture"],
        "related_sites": ["roman_amphitheatre_alexandria"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "philae_temple_of_hathor",
        "name": "Temple of Hathor",
        "name_ar": "معبد حتحور",
        "category": "Pharaonic",
        "subcategory": "Temples",
        "region": "Aswan",
        "parent_slug": "philae_temple",
        "period": "Ptolemaic (c. 200 BC)",
        "featured": False,
        "description": "A small but charming temple dedicated to Hathor, located east of the main Temple of Isis. Features playful reliefs of the god Bes (dwarf deity of music and joy) playing instruments, and offerings scenes from the Ptolemaic period. The temple was later adapted with Christian crosses when Philae became a Coptic settlement.",
        "has_image": True,
        "coordinates": {"lat": 24.0262, "lng": 32.8841},
        "tags": ["art", "off-the-beaten-path"],
        "related_sites": ["dendera_temple"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "philae_hadrians_gate",
        "name": "Hadrian's Gate & Second Pylon",
        "name_ar": "بوابة هادريان",
        "category": "Pharaonic",
        "subcategory": "Temples",
        "region": "Aswan",
        "parent_slug": "philae_temple",
        "period": "Roman (c. 130 AD)",
        "featured": False,
        "description": "A gateway built under Emperor Hadrian, featuring significant mythological reliefs including a depiction of the source of the Nile emerging from a cave beneath Bigeh Island, with the god Hapy pouring water from twin vases. Also shows Isis watching as a crocodile carries the body of Osiris — key scenes from the Isis-Osiris myth that made Philae one of the holiest pilgrimage sites in the ancient world.",
        "has_image": True,
        "coordinates": {"lat": 24.0262, "lng": 32.8841},
        "tags": ["historic"],
        "related_sites": [],
        "images": [],
        "sections": [],
    },
]


"""Dendera Temple Complex — sub-sites."""

DENDERA_CHILDREN = [
    {
        "slug": "dendera_hypostyle_hall",
        "name": "Great Hypostyle Hall",
        "name_ar": "صالة الأعمدة الكبرى",
        "category": "Pharaonic",
        "subcategory": "Temples",
        "region": "Qena",
        "parent_slug": "dendera_temple",
        "period": "Ptolemaic–Roman (c. 54–20 BC)",
        "featured": True,
        "description": "The stunning entrance hall of the Temple of Hathor featuring 24 massive columns topped with four-faced Hathor capitals — the goddess's face bearing cow ears on each side. The ceiling retains remarkable original astronomical decoration in vivid blues, showing the sky goddess Nut swallowing and rebirthing the sun, zodiac figures, and vultures. Added by the Roman Emperor Tiberius, the hall's rich color makes it one of the best-preserved temple interiors in Egypt.",
        "has_image": True,
        "coordinates": {"lat": 26.1425, "lng": 32.6700},
        "tags": ["must-visit", "art", "iconic"],
        "related_sites": ["karnak_temple"],
        "images": [],
        "sections": [
            {"title": "Hathor-Headed Columns", "content": "24 towering columns each topped with the face of Hathor on all four sides — a forest of goddess faces unique to Dendera. The capitals were originally painted in vivid colors."},
            {"title": "Astronomical Ceiling", "content": "The ceiling preserves extraordinary astronomical decoration — the sky goddess Nut stretches across the full length, with zodiac figures, decans (star groups), and detailed depictions of the sun's daily cycle."},
        ],
    },
    {
        "slug": "dendera_zodiac_chapel",
        "name": "Zodiac Chapel (Osiris Chapels)",
        "name_ar": "غرفة البروج",
        "category": "Pharaonic",
        "subcategory": "Temples",
        "region": "Qena",
        "parent_slug": "dendera_temple",
        "period": "Ptolemaic (c. 50 BC)",
        "featured": True,
        "description": "The rooftop chapel containing the famous Dendera Zodiac — a circular bas-relief astronomical map on the ceiling showing the 12 zodiac constellations, 36 decans, planets, and the Egyptian constellations. The original was removed to France in 1820 and is now in the Louvre; a plaster replica remains in place. This is one of the most important astronomical documents from the ancient world, combining Egyptian, Babylonian, and Greek star-mapping traditions.",
        "has_image": True,
        "coordinates": {"lat": 26.1425, "lng": 32.6700},
        "tags": ["must-visit", "iconic", "science"],
        "related_sites": [],
        "images": [],
        "sections": [
            {"title": "The Dendera Zodiac", "content": "A circular planisphere (now in the Louvre) that is one of the earliest complete maps of the sky, dating to around 50 BC. It shows all 12 zodiac signs recognizable today, alongside Egyptian constellations like Taweret (the hippopotamus) and the Foreleg of the Bull."},
            {"title": "Osiris Mystery Play Reliefs", "content": "The surrounding chapels depict scenes from the Osiris resurrection mystery plays performed at Dendera — Isis reassembling and resurrecting Osiris, among the most complete surviving records of these sacred rites."},
        ],
    },
    {
        "slug": "dendera_crypts",
        "name": "Underground Crypts",
        "name_ar": "السراديب",
        "category": "Pharaonic",
        "subcategory": "Temples",
        "region": "Qena",
        "parent_slug": "dendera_temple",
        "period": "Ptolemaic",
        "featured": False,
        "description": "A series of mysterious underground passages and chambers beneath the temple, used to store sacred objects, ritual equipment, and temple treasures. The crypt walls feature fascinating reliefs including the controversial 'Dendera Light' — a large bulb-like object that some interpret as evidence of ancient electricity (mainstream Egyptology identifies it as a lotus flower/djed pillar). The tight corridors create an atmospheric descent into the temple's hidden heart.",
        "has_image": True,
        "coordinates": {"lat": 26.1425, "lng": 32.6700},
        "tags": ["off-the-beaten-path", "unique"],
        "related_sites": [],
        "images": [],
        "sections": [],
    },
    {
        "slug": "dendera_sacred_lake",
        "name": "Sacred Lake & Birth House",
        "name_ar": "البحيرة المقدسة وبيت الولادة",
        "category": "Pharaonic",
        "subcategory": "Temples",
        "region": "Qena",
        "parent_slug": "dendera_temple",
        "period": "Ptolemaic–Roman",
        "featured": False,
        "description": "The temple complex includes a well-preserved sacred lake where priests performed ritual purifications, a Roman-era Birth House (mammisi) with exquisite reliefs of the divine birth of Ihy (son of Hathor and Horus), and a small temple of Isis. The Birth House columns are decorated with elaborate composite capitals featuring the dwarf god Bes playing musical instruments.",
        "has_image": True,
        "coordinates": {"lat": 26.1425, "lng": 32.6700},
        "tags": ["historic"],
        "related_sites": [],
        "images": [],
        "sections": [],
    },
]


"""Edfu Temple — sub-sites."""

EDFU_CHILDREN = [
    {
        "slug": "edfu_great_pylon",
        "name": "Great Pylon & Courtyard",
        "name_ar": "البوابة الكبرى والفناء",
        "category": "Pharaonic",
        "subcategory": "Temples",
        "region": "Aswan",
        "parent_slug": "edfu_temple",
        "period": "Ptolemaic (237–57 BC)",
        "featured": True,
        "description": "The 36-meter-high pylon — the best-preserved temple gateway in Egypt — featuring enormous reliefs of Ptolemy XII smiting enemies before Horus. Two black granite falcon statues of Horus wearing the double crown guard the entrance. Beyond lies a spacious columned courtyard surrounded by 32 columns with varied floral capitals.",
        "has_image": True,
        "coordinates": {"lat": 24.9780, "lng": 32.8730},
        "tags": ["must-visit", "iconic"],
        "related_sites": ["philae_temple"],
        "images": [],
        "sections": [
            {"title": "The Horus Falcons", "content": "Two magnificent black granite statues of Horus as a falcon wearing the double crown of Upper and Lower Egypt — among the most iconic images of ancient Egypt."},
            {"title": "Festival Courtyard", "content": "The open courtyard was the setting for the annual Beautiful Festival of Reunion, when the statue of Hathor traveled from Dendera to 'visit' Horus at Edfu."},
        ],
    },
    {
        "slug": "edfu_hypostyle_hall",
        "name": "Hypostyle Halls",
        "name_ar": "صالات الأعمدة",
        "category": "Pharaonic",
        "subcategory": "Temples",
        "region": "Aswan",
        "parent_slug": "edfu_temple",
        "period": "Ptolemaic",
        "featured": False,
        "description": "Two successive hypostyle halls leading progressively deeper and darker into the temple. The outer hall has 12 columns and contains a small library room ('House of Books') with inscribed catalog of temple texts. The inner hall has 12 columns and leads to the offering hall. Walls are covered with elaborate ritual scenes, astronomical ceilings, and texts describing temple ceremonies.",
        "has_image": True,
        "coordinates": {"lat": 24.9780, "lng": 32.8730},
        "tags": ["architecture"],
        "related_sites": ["karnak_temple"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "edfu_sanctuary",
        "name": "Holy of Holies (Sanctuary)",
        "name_ar": "قدس الأقداس",
        "category": "Pharaonic",
        "subcategory": "Temples",
        "region": "Aswan",
        "parent_slug": "edfu_temple",
        "period": "Ptolemaic",
        "featured": False,
        "description": "The innermost sacred chamber where the golden cult statue of Horus was kept in a polished granite naos (shrine) that still stands in place — the oldest element of the temple, dating to the reign of Nectanebo II (360–342 BC). Only the high priest could enter this darkened room to perform the daily ritual of awakening, dressing, anointing, and feeding the god's statue.",
        "has_image": True,
        "coordinates": {"lat": 24.9780, "lng": 32.8730},
        "tags": ["historic"],
        "related_sites": [],
        "images": [],
        "sections": [],
    },
]


"""Kom Ombo Temple — sub-sites."""

KOM_OMBO_CHILDREN = [
    {
        "slug": "kom_ombo_sobek_temple",
        "name": "Temple of Sobek (South Side)",
        "name_ar": "معبد سوبك",
        "category": "Pharaonic",
        "subcategory": "Temples",
        "region": "Aswan",
        "parent_slug": "kom_ombo_temple",
        "period": "Ptolemaic (180–47 BC)",
        "featured": True,
        "description": "The southern half of this unique dual temple, dedicated to Sobek, the crocodile god of fertility and the Nile. The symmetrical layout mirrors the northern Horus section, with its own entrance, hypostyle hall, and sanctuary. Wall reliefs include a famous panel showing ancient surgical instruments — scalpels, forceps, bone saws, and dental tools — suggesting advanced medical knowledge. A unique calendar and fascinating relief of Sobek with a crocodile head adorn the walls.",
        "has_image": True,
        "coordinates": {"lat": 24.4522, "lng": 32.9285},
        "tags": ["must-visit", "science"],
        "related_sites": ["crocodilopolis"],
        "images": [],
        "sections": [
            {"title": "Surgical Instruments Panel", "content": "A remarkable wall relief depicting what appear to be ancient surgical and medical instruments — including scalpels, bone saws, suction cups, forceps, and what may be birthing tools — evidence of advanced ancient Egyptian medical practice."},
            {"title": "The Nilometer", "content": "A stone well connected to the Nile used to measure water levels, crucial for predicting floods and calculating agricultural taxes."},
        ],
    },
    {
        "slug": "kom_ombo_horus_temple",
        "name": "Temple of Haroeris (North Side)",
        "name_ar": "معبد حورس الكبير",
        "category": "Pharaonic",
        "subcategory": "Temples",
        "region": "Aswan",
        "parent_slug": "kom_ombo_temple",
        "period": "Ptolemaic (180–47 BC)",
        "featured": False,
        "description": "The northern half of the dual temple, dedicated to Haroeris (Horus the Elder), the falcon-headed sky god. A mirror image of the Sobek side, it features its own entrance, halls, and sanctuary. Reliefs depict Horus receiving offerings, mythological scenes, and the ritual of 'purification of the pharaoh' by Horus and Thoth pouring sacred water depicted as ankh symbols.",
        "has_image": True,
        "coordinates": {"lat": 24.4522, "lng": 32.9285},
        "tags": ["historic"],
        "related_sites": ["edfu_temple"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "kom_ombo_crocodile_museum",
        "name": "Crocodile Museum",
        "name_ar": "متحف التماسيح",
        "category": "Museum",
        "subcategory": "Site Museums",
        "region": "Aswan",
        "parent_slug": "kom_ombo_temple",
        "period": "Modern (opened 2012)",
        "featured": False,
        "description": "A modern museum adjacent to the temple displaying over 20 mummified crocodiles found in the surrounding area, ranging from tiny hatchlings to massive full-grown specimens up to 4 meters long. Exhibits explain the cult of Sobek, the role of sacred crocodiles in ancient Egyptian religion, and the elaborate mummification process for these feared and revered animals.",
        "has_image": True,
        "coordinates": {"lat": 24.4522, "lng": 32.9285},
        "tags": ["family-friendly", "unique"],
        "related_sites": [],
        "images": [],
        "sections": [],
    },
]
