"""Valley of the Kings — individual tombs as sub-sites."""

VALLEY_OF_KINGS_CHILDREN = [
    {
        "slug": "vok_kv62_tutankhamun",
        "name": "Tomb of Tutankhamun (KV62)",
        "name_ar": "مقبرة توت عنخ آمون",
        "category": "Pharaonic",
        "subcategory": "Tombs & Temples",
        "region": "Luxor",
        "parent_slug": "valley_of_the_kings",
        "period": "New Kingdom (18th Dynasty, c. 1323 BC)",
        "featured": True,
        "description": "The most famous tomb in Egypt, discovered nearly intact by Howard Carter on November 26, 1922. Though small by royal standards (4 chambers), it contained 5,398 objects including the iconic golden death mask (11 kg of solid gold), three nested coffins, the golden throne, and four canopic miniature coffins. The 'curse of the pharaoh' legend began with Lord Carnarvon's death.",
        "has_image": True,
        "coordinates": {"lat": 25.7404, "lng": 32.6014},
        "tags": ["must-visit", "iconic", "underground"],
        "related_sites": ["valley_of_the_kings", "grand_egyptian_museum"],
        "images": [],
        "sections": [
            {"title": "The Discovery", "content": "After six seasons of fruitless digging, Carter found a step on Nov 4, 1922 beneath ancient workmen's huts. 'Can you see anything?' asked Carnarvon. 'Yes, wonderful things,' replied Carter."},
            {"title": "The Burial Chamber", "content": "Walls painted with scenes from the Book of the Dead and the Amduat. The quartzite sarcophagus still holds the outermost gilded coffin with the mummy inside."},
        ],
    },
    {
        "slug": "vok_kv17_seti_i",
        "name": "Tomb of Seti I (KV17)",
        "name_ar": "مقبرة سيتي الأول",
        "category": "Pharaonic",
        "subcategory": "Tombs & Temples",
        "region": "Luxor",
        "parent_slug": "valley_of_the_kings",
        "period": "New Kingdom (19th Dynasty, c. 1279 BC)",
        "featured": True,
        "description": "The finest and longest tomb in the Valley (137 meters deep), discovered by Giovanni Belzoni in 1817. Every surface is covered in exquisite painted reliefs — the astronomical ceiling in the burial chamber is the most complete ancient Egyptian star chart known. Currently closed for conservation but viewable via the Factum Arte replica nearby.",
        "has_image": True,
        "coordinates": {"lat": 25.7412, "lng": 32.6021},
        "tags": ["iconic", "underground", "art"],
        "related_sites": ["valley_of_the_kings", "temple_of_seti_i_abydos"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "vok_kv9_ramesses_vi",
        "name": "Tomb of Ramesses V/VI (KV9)",
        "name_ar": "مقبرة رمسيس الخامس والسادس",
        "category": "Pharaonic",
        "subcategory": "Tombs & Temples",
        "region": "Luxor",
        "parent_slug": "valley_of_the_kings",
        "period": "New Kingdom (20th Dynasty)",
        "featured": False,
        "description": "One of the most spectacular tombs visitors can enter, known for its double astronomical ceiling depicting the Book of Day and Book of Night. The tomb was started for Ramesses V but usurped by Ramesses VI. Ironically, debris from its construction concealed and protected Tutankhamun's tomb below for 3,000 years.",
        "has_image": True,
        "coordinates": {"lat": 25.7408, "lng": 32.6016},
        "tags": ["must-visit", "underground", "art", "photography"],
        "related_sites": ["valley_of_the_kings"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "vok_kv34_thutmose_iii",
        "name": "Tomb of Thutmose III (KV34)",
        "name_ar": "مقبرة تحتمس الثالث",
        "category": "Pharaonic",
        "subcategory": "Tombs & Temples",
        "region": "Luxor",
        "parent_slug": "valley_of_the_kings",
        "period": "New Kingdom (18th Dynasty, c. 1425 BC)",
        "featured": False,
        "description": "Hidden high in a cliff face, this tomb requires climbing steep stairs. The oval-shaped burial chamber features the earliest complete Book of the Amduat painted in a unique 'stick-figure' style on a yellow background. The cartouche-shaped sarcophagus is red quartzite. An adventure to reach but architecturally fascinating.",
        "has_image": True,
        "coordinates": {"lat": 25.7418, "lng": 32.6008},
        "tags": ["off-the-beaten-path", "underground", "adventure"],
        "related_sites": ["valley_of_the_kings", "hatshepsut_temple"],
        "images": [],
        "sections": [],
    },
    {
        "slug": "vok_kv35_amenhotep_ii",
        "name": "Tomb of Amenhotep II (KV35)",
        "name_ar": "مقبرة أمنحتب الثاني",
        "category": "Pharaonic",
        "subcategory": "Tombs & Temples",
        "region": "Luxor",
        "parent_slug": "valley_of_the_kings",
        "period": "New Kingdom (18th Dynasty, c. 1400 BC)",
        "featured": False,
        "description": "Famous for two reasons: it still contains the pharaoh's mummy lying in his original sarcophagus (unique in the Valley), and a side chamber was used as a cache for thirteen royal mummies hidden by priests in antiquity, including Thutmose IV and Seti II. The painted walls of the burial chamber depict the Amduat.",
        "has_image": True,
        "coordinates": {"lat": 25.7416, "lng": 32.6010},
        "tags": ["underground", "off-the-beaten-path"],
        "related_sites": ["valley_of_the_kings"],
        "images": [],
        "sections": [],
    },
]
