"""
Wadjet AI — Rich Description Generation.

Generates dynamic, language-aware descriptions for Egyptian landmarks
using Gemini AI.  Results are cached for 1 hour to avoid redundant
API calls.

Phase 3.4 — Rich Description Generation.
"""

from __future__ import annotations

import json
from typing import Any

import structlog
from pydantic import BaseModel, Field

from app.core.cache import gemini_cache
from app.core.exceptions import GeminiError

logger = structlog.get_logger("wadjet.gemini.descriptions")

# ---------------------------------------------------------------------------
# Structured result model
# ---------------------------------------------------------------------------


class RichDescription(BaseModel):
    """Structured description generated by Gemini for a landmark."""

    landmark_name: str = Field(..., description="Name of the landmark")
    language: str = Field(..., description="Language code of the content")
    summary: str = Field(
        ...,
        description="One-paragraph overview of the landmark",
    )
    history: str = Field(
        ...,
        description="Historical background and significance",
    )
    architectural_significance: str = Field(
        ...,
        description="Architectural features and engineering importance",
    )
    interesting_facts: list[str] = Field(
        default_factory=list,
        description="4-6 interesting facts about the landmark",
    )
    visiting_tips: str = Field(
        ...,
        description="Practical tips for visitors",
    )
    best_time_to_visit: str = Field(
        default="",
        description="Recommended time of day / season to visit",
    )
    nearby_attractions: list[str] = Field(
        default_factory=list,
        description="Notable sites within walking distance",
    )


# ---------------------------------------------------------------------------
# JSON schema for Gemini structured output
# ---------------------------------------------------------------------------


def _description_response_schema() -> dict[str, Any]:
    """Return the JSON Schema for Gemini structured output."""
    return {
        "type": "object",
        "properties": {
            "summary": {"type": "string"},
            "history": {"type": "string"},
            "architectural_significance": {"type": "string"},
            "interesting_facts": {
                "type": "array",
                "items": {"type": "string"},
            },
            "visiting_tips": {"type": "string"},
            "best_time_to_visit": {"type": "string"},
            "nearby_attractions": {
                "type": "array",
                "items": {"type": "string"},
            },
        },
        "required": [
            "summary",
            "history",
            "architectural_significance",
            "interesting_facts",
            "visiting_tips",
            "best_time_to_visit",
            "nearby_attractions",
        ],
    }


# ---------------------------------------------------------------------------
# System prompts per language
# ---------------------------------------------------------------------------

_SYSTEM_PROMPTS: dict[str, str] = {
    "en": (
        "You are a world-class Egyptologist and travel writer. "
        "Generate a rich, detailed description of the specified Egyptian landmark. "
        "Your response must be a JSON object with these fields:\n"
        "- summary: a compelling one-paragraph overview (3-5 sentences)\n"
        "- history: detailed historical background covering construction, purpose, "
        "and historical events (4-8 sentences)\n"
        "- architectural_significance: key architectural and engineering features "
        "(3-6 sentences)\n"
        "- interesting_facts: a list of 4-6 fascinating facts\n"
        "- visiting_tips: practical advice for visitors (3-5 sentences)\n"
        "- best_time_to_visit: recommended time of day and season\n"
        "- nearby_attractions: list of 2-4 notable sites nearby\n\n"
        "Write in English. Be accurate, engaging, and informative."
    ),
    "ar": (
        "أنت عالم آثار مصري من الطراز العالمي وكاتب سفر. "
        "أنشئ وصفًا غنيًا ومفصلًا للمعلم المصري المحدد. "
        "يجب أن تكون إجابتك كائن JSON بالحقول التالية:\n"
        "- summary: نظرة عامة مقنعة في فقرة واحدة (3-5 جمل)\n"
        "- history: خلفية تاريخية مفصلة تغطي البناء والغرض "
        "والأحداث التاريخية (4-8 جمل)\n"
        "- architectural_significance: الميزات المعمارية والهندسية الرئيسية "
        "(3-6 جمل)\n"
        "- interesting_facts: قائمة من 4-6 حقائق مذهلة\n"
        "- visiting_tips: نصائح عملية للزوار (3-5 جمل)\n"
        "- best_time_to_visit: الوقت الموصى به من اليوم والموسم\n"
        "- nearby_attractions: قائمة من 2-4 مواقع بارزة قريبة\n\n"
        "اكتب بالعربية. كن دقيقًا وجذابًا ومعلوماتيًا."
    ),
    "fr": (
        "Vous etes un egyptologue de renommee mondiale et ecrivain de voyage. "
        "Generez une description riche et detaillee du monument egyptien specifie. "
        "Votre reponse doit etre un objet JSON avec les champs suivants:\n"
        "- summary: un apercu captivant en un paragraphe (3-5 phrases)\n"
        "- history: un contexte historique detaille couvrant la construction, "
        "le but et les evenements historiques (4-8 phrases)\n"
        "- architectural_significance: les caracteristiques architecturales et "
        "techniques cles (3-6 phrases)\n"
        "- interesting_facts: une liste de 4-6 faits fascinants\n"
        "- visiting_tips: des conseils pratiques pour les visiteurs (3-5 phrases)\n"
        "- best_time_to_visit: le moment recommande de la journee et la saison\n"
        "- nearby_attractions: liste de 2-4 sites remarquables a proximite\n\n"
        "Ecrivez en francais. Soyez precis, engageant et informatif."
    ),
    "de": (
        "Sie sind ein weltbekannter Agyptologe und Reiseschriftsteller. "
        "Erstellen Sie eine ausfuhrliche Beschreibung des angegebenen "
        "agyptischen Wahrzeichens. "
        "Ihre Antwort muss ein JSON-Objekt mit folgenden Feldern sein:\n"
        "- summary: ein fesselnder Uberblick in einem Absatz (3-5 Satze)\n"
        "- history: detaillierter historischer Hintergrund uber Bau, Zweck "
        "und historische Ereignisse (4-8 Satze)\n"
        "- architectural_significance: wichtige architektonische und "
        "technische Merkmale (3-6 Satze)\n"
        "- interesting_facts: eine Liste von 4-6 faszinierenden Fakten\n"
        "- visiting_tips: praktische Tipps fur Besucher (3-5 Satze)\n"
        "- best_time_to_visit: empfohlene Tageszeit und Jahreszeit\n"
        "- nearby_attractions: Liste von 2-4 bemerkenswerten Statten in der Nahe\n\n"
        "Schreiben Sie auf Deutsch. Seien Sie genau, ansprechend und informativ."
    ),
}


# ---------------------------------------------------------------------------
# Cache key helper
# ---------------------------------------------------------------------------


def _cache_key(landmark_name: str, language: str) -> str:
    """Build a deterministic cache key for a description."""
    return f"desc:{landmark_name.lower().strip()}:{language}"


# ---------------------------------------------------------------------------
# Core generation function
# ---------------------------------------------------------------------------


async def generate_description(
    gemini_service: Any,
    landmark_name: str,
    *,
    language: str = "en",
    use_cache: bool = True,
) -> RichDescription:
    """Generate a rich description for an Egyptian landmark.

    Parameters
    ----------
    gemini_service:
        An initialised ``GeminiService`` instance (from DI).
    landmark_name:
        The name of the landmark to describe.
    language:
        ISO 639-1 language code (``en``, ``ar``, ``fr``, ``de``).
    use_cache:
        If ``True`` (default), check/populate the 1-hour cache.

    Returns
    -------
    RichDescription
        Structured description with history, facts, tips, etc.

    Raises
    ------
    GeminiError
        If the Gemini API call fails or the response cannot be parsed.
    """
    cache_key = _cache_key(landmark_name, language)

    # ── Check cache ─────────────────────────────
    if use_cache:
        cached = gemini_cache.get(cache_key)
        if cached is not None:
            logger.info(
                "description_cache_hit",
                landmark=landmark_name,
                language=language,
            )
            return cached

    # ── Build prompt ────────────────────────────
    system_prompt = _SYSTEM_PROMPTS.get(language, _SYSTEM_PROMPTS["en"])

    user_prompt = (
        f"Generate a rich description for the Egyptian landmark: {landmark_name}\n\n"
        f"Return ONLY a valid JSON object following the specified schema."
    )

    logger.info(
        "description_generate_start",
        landmark=landmark_name,
        language=language,
    )

    # ── Call Gemini ──────────────────────────────
    try:
        raw_json = await gemini_service.generate_json(
            prompt=user_prompt,
            system_instruction=system_prompt,
            temperature=0.7,
            max_output_tokens=4096,
            response_schema=_description_response_schema(),
        )
    except GeminiError:
        raise
    except Exception as exc:
        logger.error("description_api_error", error=str(exc))
        raise GeminiError(f"Description generation failed: {exc}") from exc

    # ── Parse JSON ──────────────────────────────
    try:
        parsed: dict[str, Any] = json.loads(raw_json)
    except json.JSONDecodeError as exc:
        logger.error(
            "description_json_parse_error",
            raw_response=raw_json[:500],
            error=str(exc),
        )
        raise GeminiError(f"Gemini returned invalid JSON: {exc}") from exc

    # ── Validate with Pydantic ──────────────────
    try:
        result = RichDescription(
            landmark_name=landmark_name,
            language=language,
            **parsed,
        )
    except Exception as exc:
        logger.error(
            "description_validation_error",
            parsed_data=parsed,
            error=str(exc),
        )
        raise GeminiError(f"Description response failed validation: {exc}") from exc

    # ── Store in cache (1h TTL) ─────────────────
    if use_cache:
        gemini_cache.set(cache_key, result)

    logger.info(
        "description_generate_complete",
        landmark=landmark_name,
        language=language,
        facts_count=len(result.interesting_facts),
        nearby_count=len(result.nearby_attractions),
    )

    return result
