"""Category A — Man and his Activities (80 signs)."""

# fmt: off
# Each entry: (code, hex, description, phonetic, type, logographic, det_class)
SIGNS: list[tuple[str, int, str, str, str, str, str]] = [
    ("A1", 0x13000, "seated man", "", "DETERMINATIVE", "", ""),
    ("A2", 0x13001, "man with hand to mouth", "", "DETERMINATIVE", "", ""),
    ("A3", 0x13002, "man sitting on heel", "", "DETERMINATIVE", "", ""),
    ("A4", 0x13003, "seated man with hands raised", "", "DETERMINATIVE", "", ""),
    ("A5", 0x13004, "man hiding behind wall", "", "DETERMINATIVE", "", ""),
    ("A5A", 0x13005, "man hiding behind wall (variant)", "", "DETERMINATIVE", "", ""),
    ("A6", 0x13006, "man under vase from which water flows", "", "DETERMINATIVE", "", ""),
    ("A6A", 0x13007, "man under vase from which water flows (variant)", "", "DETERMINATIVE", "", ""),
    ("A6B", 0x13008, "man under vase from which water flows (variant)", "", "DETERMINATIVE", "", ""),
    ("A7", 0x13009, "fatigued man", "", "DETERMINATIVE", "", ""),
    ("A8", 0x1300A, "man performing hnw-rite", "", "DETERMINATIVE", "", ""),
    ("A9", 0x1300B, "man steadying basket on head", "", "DETERMINATIVE", "", ""),
    ("A10", 0x1300C, "seated man holding oar", "", "DETERMINATIVE", "", ""),
    ("A11", 0x1300D, "seated man holding scepter and staff", "", "DETERMINATIVE", "", ""),
    ("A12", 0x1300E, "soldier with bow and quiver", "", "DETERMINATIVE", "", ""),
    ("A13", 0x1300F, "man with arms tied behind back", "", "DETERMINATIVE", "", ""),
    ("A14", 0x13010, "falling man with blood streaming from head", "", "DETERMINATIVE", "", ""),
    ("A14A", 0x13011, "falling man with blood streaming from head (variant)", "", "DETERMINATIVE", "", ""),
    ("A15", 0x13012, "man falling", "", "DETERMINATIVE", "", ""),
    ("A16", 0x13013, "man bowing down", "", "DETERMINATIVE", "", ""),
    ("A17", 0x13014, "child sitting with hand to mouth", "ms", "BILITERAL", "", ""),
    ("A17A", 0x13015, "child sitting with hand to mouth (variant)", "", "DETERMINATIVE", "", ""),
    ("A18", 0x13016, "child wearing red crown", "", "DETERMINATIVE", "", ""),
    ("A19", 0x13017, "bent man leaning on staff", "jk", "BILITERAL", "", ""),
    ("A20", 0x13018, "man leaning on forked staff", "", "DETERMINATIVE", "", ""),
    ("A21", 0x13019, "man holding staff with handkerchief", "", "DETERMINATIVE", "", ""),
    ("A22", 0x1301A, "statue of man with staff and scepter", "", "DETERMINATIVE", "", ""),
    ("A23", 0x1301B, "king with staff and mace", "", "DETERMINATIVE", "", ""),
    ("A24", 0x1301C, "man striking with both hands", "", "DETERMINATIVE", "", ""),
    ("A25", 0x1301D, "man striking, left arm behind back", "", "DETERMINATIVE", "", ""),
    ("A26", 0x1301E, "man with one arm pointing forward", "", "DETERMINATIVE", "", ""),
    ("A27", 0x1301F, "hastening man", "jn", "BILITERAL", "", ""),
    ("A28", 0x13020, "man with both hands raised", "", "DETERMINATIVE", "", ""),
    ("A29", 0x13021, "man upside down", "", "DETERMINATIVE", "", ""),
    ("A30", 0x13022, "man with hands raised in front", "", "DETERMINATIVE", "", ""),
    ("A31", 0x13023, "man with hands raised behind", "", "DETERMINATIVE", "", ""),
    ("A32", 0x13024, "man dancing with arms to back", "", "DETERMINATIVE", "", ""),
    ("A32A", 0x13025, "man dancing with arms to back (variant)", "", "DETERMINATIVE", "", ""),
    ("A33", 0x13026, "man with stick and bundle on shoulder", "", "DETERMINATIVE", "", ""),
    ("A34", 0x13027, "man pounding in mortar", "", "DETERMINATIVE", "", ""),
    ("A35", 0x13028, "man building wall", "", "DETERMINATIVE", "", ""),
    ("A36", 0x13029, "man kneading into vessel", "", "DETERMINATIVE", "", ""),
    ("A37", 0x1302A, "man in vessel", "", "DETERMINATIVE", "", ""),
    ("A38", 0x1302B, "man holding necks of two animals", "", "DETERMINATIVE", "", ""),
    ("A39", 0x1302C, "man on two giraffes", "", "DETERMINATIVE", "", ""),
    ("A40", 0x1302D, "seated god", "", "DETERMINATIVE", "", ""),
    ("A40A", 0x1302E, "seated god (variant)", "", "DETERMINATIVE", "", ""),
    ("A41", 0x1302F, "king with uraeus", "", "DETERMINATIVE", "", ""),
    ("A42", 0x13030, "king with uraeus and flagellum", "", "DETERMINATIVE", "", ""),
    ("A42A", 0x13031, "king with uraeus and flagellum (variant)", "", "DETERMINATIVE", "", ""),
    ("A43", 0x13032, "king wearing white crown", "", "DETERMINATIVE", "", ""),
    ("A43A", 0x13033, "king wearing white crown (variant)", "", "DETERMINATIVE", "", ""),
    ("A44", 0x13034, "king wearing white crown with flagellum", "", "DETERMINATIVE", "", ""),
    ("A45", 0x13035, "king wearing red crown", "", "DETERMINATIVE", "", ""),
    ("A45A", 0x13036, "king wearing red crown (variant)", "", "DETERMINATIVE", "", ""),
    ("A46", 0x13037, "king wearing red crown with flagellum", "", "DETERMINATIVE", "", ""),
    ("A47", 0x13038, "shepherd seated wrapped in mantle", "", "DETERMINATIVE", "", ""),
    ("A48", 0x13039, "beardless man sitting with knife", "", "DETERMINATIVE", "", ""),
    ("A49", 0x1303A, "seated Syrian holding stick", "", "DETERMINATIVE", "", ""),
    ("A50", 0x1303B, "noble on chair", "", "DETERMINATIVE", "", ""),
    ("A51", 0x1303C, "noble on chair with flagellum", "", "DETERMINATIVE", "", ""),
    ("A52", 0x1303D, "noble squatting with flagellum", "", "DETERMINATIVE", "", ""),
    ("A53", 0x1303E, "standing mummy", "", "DETERMINATIVE", "", ""),
    ("A54", 0x1303F, "lying mummy", "", "DETERMINATIVE", "", ""),
    ("A55", 0x13040, "mummy on bed", "Hs", "BILITERAL", "", "death"),
    ("A56", 0x13041, "seated man holding stick", "", "DETERMINATIVE", "", ""),
    ("A57", 0x13042, "man holding loaf on mat", "", "DETERMINATIVE", "", ""),
    ("A58", 0x13043, "man applying hoe to ground", "", "DETERMINATIVE", "", ""),
    ("A59", 0x13044, "man threatening with stick", "", "DETERMINATIVE", "", ""),
    ("A60", 0x13045, "man sowing seeds", "", "DETERMINATIVE", "", ""),
    ("A61", 0x13046, "man looking over shoulder", "", "DETERMINATIVE", "", ""),
    ("A62", 0x13047, "Asiatic", "", "DETERMINATIVE", "", ""),
    ("A63", 0x13048, "king on throne holding staff", "", "DETERMINATIVE", "", ""),
    ("A64", 0x13049, "man sitting on heels holding cup", "", "DETERMINATIVE", "", ""),
    ("A65", 0x1304A, "man in tunic with mace and staff", "", "DETERMINATIVE", "", ""),
    ("A66", 0x1304B, "man holding sistrum", "", "DETERMINATIVE", "", ""),
    ("A67", 0x1304C, "dwarf", "", "DETERMINATIVE", "", ""),
    ("A68", 0x1304D, "man holding up knife", "", "DETERMINATIVE", "", ""),
    ("A69", 0x1304E, "seated man with raised right arm", "", "DETERMINATIVE", "", ""),
    ("A70", 0x1304F, "seated man with raised arms", "", "DETERMINATIVE", "", ""),
]
# fmt: on
