"""Category D — Parts of the Human Body (92 signs)."""

# fmt: off
# Each entry: (code, hex, description, phonetic, type, logographic, det_class)
SIGNS: list[tuple[str, int, str, str, str, str, str]] = [
    ("D1", 0x13076, "head in profile", "tp", "BILITERAL", "", ""),
    ("D2", 0x13077, "face", "Hr", "BILITERAL", "", ""),
    ("D3", 0x13078, "hair", "", "DETERMINATIVE", "", ""),
    ("D4", 0x13079, "eye", "ir", "BILITERAL", "eye; to do, make", ""),
    ("D5", 0x1307A, "eye with paint", "", "DETERMINATIVE", "", ""),
    ("D6", 0x1307B, "eye with painted upper lid", "", "DETERMINATIVE", "", ""),
    ("D7", 0x1307C, "eye with painted lower lid", "", "DETERMINATIVE", "", ""),
    ("D8", 0x1307D, "eye enclosed in sandy tract", "", "DETERMINATIVE", "", ""),
    ("D8A", 0x1307E, "eye enclosed in sandy tract (variant)", "", "DETERMINATIVE", "", ""),
    ("D9", 0x1307F, "eye with flowing tears", "rmi", "TRILITERAL", "", ""),
    ("D10", 0x13080, "Eye of Horus", "wDAt", "TRILITERAL", "", ""),
    ("D11", 0x13081, "left part of Eye of Horus", "", "DETERMINATIVE", "", ""),
    ("D12", 0x13082, "pupil of Eye of Horus", "", "DETERMINATIVE", "", ""),
    ("D13", 0x13083, "eyebrow", "", "DETERMINATIVE", "", ""),
    ("D14", 0x13084, "right part of Eye of Horus", "", "DETERMINATIVE", "", ""),
    ("D15", 0x13085, "diagonal of Eye of Horus", "", "DETERMINATIVE", "", ""),
    ("D16", 0x13086, "vertical mark of Eye of Horus", "", "DETERMINATIVE", "", ""),
    ("D17", 0x13087, "diagonal and vertical of Eye of Horus", "", "DETERMINATIVE", "", ""),
    ("D18", 0x13088, "ear", "", "DETERMINATIVE", "", ""),
    ("D19", 0x13089, "nose, eye and cheek", "fnD", "TRILITERAL", "nose", ""),
    ("D20", 0x1308A, "nose, eye and cheek (cursive)", "", "DETERMINATIVE", "", ""),
    ("D21", 0x1308B, "mouth", "r", "UNILITERAL", "", ""),
    ("D22", 0x1308C, "mouth with two strokes", "", "DETERMINATIVE", "", ""),
    ("D23", 0x1308D, "mouth with three strokes", "", "DETERMINATIVE", "", ""),
    ("D24", 0x1308E, "upper lip with teeth", "spt", "TRILITERAL", "", ""),
    ("D25", 0x1308F, "two lips", "", "DETERMINATIVE", "", ""),
    ("D26", 0x13090, "liquid issuing from lips", "ns", "BILITERAL", "", ""),
    ("D27", 0x13091, "small breast", "mnD", "TRILITERAL", "", ""),
    ("D27A", 0x13092, "small breast (variant)", "", "DETERMINATIVE", "", ""),
    ("D28", 0x13093, "two arms upraised (ka)", "kA", "BILITERAL", "ka (spirit)", ""),
    ("D29", 0x13094, "combination of D28 and R12", "", "DETERMINATIVE", "", ""),
    ("D30", 0x13095, "two arms with tail", "", "DETERMINATIVE", "", ""),
    ("D31", 0x13096, "arms embracing club with seal", "", "DETERMINATIVE", "", ""),
    ("D31A", 0x13097, "arms embracing club with seal (variant)", "", "DETERMINATIVE", "", ""),
    ("D32", 0x13098, "arms embracing", "Hnk", "TRILITERAL", "", ""),
    ("D33", 0x13099, "arms rowing", "Xn", "BILITERAL", "", ""),
    ("D34", 0x1309A, "arms holding shield and axe", "aS", "BILITERAL", "", ""),
    ("D34A", 0x1309B, "arms holding shield and axe (variant)", "", "DETERMINATIVE", "", ""),
    ("D35", 0x1309C, "arms in gesture of negation", "n", "BILITERAL", "", ""),
    ("D36", 0x1309D, "forearm", "a", "UNILITERAL", "", ""),
    ("D37", 0x1309E, "forearm with bread", "di", "BILITERAL", "", ""),
    ("D38", 0x1309F, "forearm with rounded loaf", "", "DETERMINATIVE", "", ""),
    ("D39", 0x130A0, "forearm with offering bowl", "mH", "BILITERAL", "", ""),
    ("D40", 0x130A1, "forearm with stick", "Hwi", "TRILITERAL", "", ""),
    ("D41", 0x130A2, "forearm with palm down", "ni", "BILITERAL", "", ""),
    ("D42", 0x130A3, "forearm with hand from above", "mi", "BILITERAL", "", ""),
    ("D43", 0x130A4, "forearm striking", "", "DETERMINATIVE", "", ""),
    ("D44", 0x130A5, "forearm with flail", "", "DETERMINATIVE", "", ""),
    ("D45", 0x130A6, "forearm with wand", "Dsr", "TRILITERAL", "", ""),
    ("D46", 0x130A7, "hand", "d", "UNILITERAL", "", ""),
    ("D46A", 0x130A8, "hand (variant)", "", "DETERMINATIVE", "", ""),
    ("D47", 0x130A9, "hand with palm up", "", "DETERMINATIVE", "", ""),
    ("D48", 0x130AA, "hand without thumb", "", "DETERMINATIVE", "", ""),
    ("D48A", 0x130AB, "hand without thumb (variant)", "", "DETERMINATIVE", "", ""),
    ("D49", 0x130AC, "fist", "", "DETERMINATIVE", "", ""),
    ("D50", 0x130AD, "one finger pointing", "Dba", "TRILITERAL", "", ""),
    ("D50A", 0x130AE, "one finger pointing (variant)", "", "DETERMINATIVE", "", ""),
    ("D50B", 0x130AF, "one finger pointing (variant)", "", "DETERMINATIVE", "", ""),
    ("D50C", 0x130B0, "one finger pointing (variant)", "", "DETERMINATIVE", "", ""),
    ("D50D", 0x130B1, "one finger pointing (variant)", "", "DETERMINATIVE", "", ""),
    ("D50E", 0x130B2, "one finger pointing (variant)", "", "DETERMINATIVE", "", ""),
    ("D50F", 0x130B3, "one finger pointing (variant)", "", "DETERMINATIVE", "", ""),
    ("D50G", 0x130B4, "one finger pointing (variant)", "", "DETERMINATIVE", "", ""),
    ("D50H", 0x130B5, "one finger pointing (variant)", "", "DETERMINATIVE", "", ""),
    ("D50I", 0x130B6, "one finger pointing (variant)", "", "DETERMINATIVE", "", ""),
    ("D51", 0x130B7, "one finger vertical", "", "DETERMINATIVE", "", ""),
    ("D52", 0x130B8, "phallus", "mt", "BILITERAL", "", ""),
    ("D52A", 0x130B9, "phallus (variant)", "", "DETERMINATIVE", "", ""),
    ("D53", 0x130BA, "phallus with emission", "mw", "BILITERAL", "", ""),
    ("D54", 0x130BB, "legs walking", "", "DETERMINATIVE", "", "motion, walking"),
    ("D54A", 0x130BC, "legs walking (variant)", "", "DETERMINATIVE", "", ""),
    ("D55", 0x130BD, "legs walking backwards", "", "DETERMINATIVE", "", ""),
    ("D56", 0x130BE, "leg", "rd", "BILITERAL", "leg, foot", ""),
    ("D57", 0x130BF, "leg with flesh", "", "DETERMINATIVE", "", ""),
    ("D58", 0x130C0, "foot", "b", "UNILITERAL", "", ""),
    ("D59", 0x130C1, "foot with toes", "", "DETERMINATIVE", "", ""),
    ("D60", 0x130C2, "water flowing between legs", "wab", "TRILITERAL", "", ""),
    ("D61", 0x130C3, "toes", "", "DETERMINATIVE", "", ""),
    ("D62", 0x130C4, "two toes", "mt", "BILITERAL", "", ""),
    ("D63", 0x130C5, "two toes variant", "", "DETERMINATIVE", "", ""),
    ("D64", 0x130C6, "hand with forearm", "", "DETERMINATIVE", "", ""),
    ("D65", 0x130C7, "foot reversed", "", "DETERMINATIVE", "", ""),
    ("D66", 0x130C8, "combination of leg signs", "", "DETERMINATIVE", "", ""),
    ("D67", 0x130C9, "three dots", "", "DETERMINATIVE", "", ""),
    ("D67A", 0x130CA, "three dots (variant)", "", "DETERMINATIVE", "", ""),
    ("D67B", 0x130CB, "three dots (variant)", "", "DETERMINATIVE", "", ""),
    ("D67C", 0x130CC, "three dots (variant)", "", "DETERMINATIVE", "", ""),
    ("D67D", 0x130CD, "three dots (variant)", "", "DETERMINATIVE", "", ""),
    ("D67E", 0x130CE, "three dots (variant)", "", "DETERMINATIVE", "", ""),
    ("D67F", 0x130CF, "three dots (variant)", "", "DETERMINATIVE", "", ""),
    ("D67G", 0x130D0, "three dots (variant)", "", "DETERMINATIVE", "", ""),
    ("D67H", 0x130D1, "three dots (variant)", "", "DETERMINATIVE", "", ""),
]
# fmt: on
