"""Category E — Mammals (44 signs)."""

# fmt: off
# Each entry: (code, hex, description, phonetic, type, logographic, det_class)
SIGNS: list[tuple[str, int, str, str, str, str, str]] = [
    ("E1", 0x130D2, "bull", "kA", "LOGOGRAM", "bull", ""),
    ("E2", 0x130D3, "bull charging", "", "DETERMINATIVE", "", ""),
    ("E3", 0x130D4, "calf", "", "DETERMINATIVE", "", ""),
    ("E4", 0x130D5, "sacred cow", "", "DETERMINATIVE", "", ""),
    ("E5", 0x130D6, "cow suckling calf", "", "DETERMINATIVE", "", ""),
    ("E6", 0x130D7, "horse", "", "DETERMINATIVE", "", ""),
    ("E7", 0x130D8, "donkey", "", "DETERMINATIVE", "", ""),
    ("E8", 0x130D9, "kid (young goat)", "", "DETERMINATIVE", "", ""),
    ("E8A", 0x130DA, "kid (young goat) (variant)", "", "DETERMINATIVE", "", ""),
    ("E9", 0x130DB, "newborn baboon", "sAb", "TRILITERAL", "", ""),
    ("E9A", 0x130DC, "newborn baboon (variant)", "", "DETERMINATIVE", "", ""),
    ("E10", 0x130DD, "ram", "", "DETERMINATIVE", "", ""),
    ("E11", 0x130DE, "ram lying down", "", "DETERMINATIVE", "", ""),
    ("E12", 0x130DF, "pig", "", "DETERMINATIVE", "", ""),
    ("E13", 0x130E0, "cat", "", "DETERMINATIVE", "", ""),
    ("E14", 0x130E1, "dog", "", "DETERMINATIVE", "", ""),
    ("E15", 0x130E2, "lying dog", "", "DETERMINATIVE", "", ""),
    ("E16", 0x130E3, "lying dog with elongated tail", "", "DETERMINATIVE", "", ""),
    ("E16A", 0x130E4, "lying dog with elongated tail (variant)", "", "DETERMINATIVE", "", ""),
    ("E17", 0x130E5, "jackal", "mAi", "TRILITERAL", "lion", ""),
    ("E17A", 0x130E6, "jackal (variant)", "", "DETERMINATIVE", "", ""),
    ("E18", 0x130E7, "seated wolf", "", "DETERMINATIVE", "", ""),
    ("E19", 0x130E8, "canine on shrine", "", "DETERMINATIVE", "", ""),
    ("E20", 0x130E9, "Set animal", "", "DETERMINATIVE", "", ""),
    ("E20A", 0x130EA, "Set animal (variant)", "", "DETERMINATIVE", "", ""),
    ("E21", 0x130EB, "lying Set animal", "", "DETERMINATIVE", "", ""),
    ("E22", 0x130EC, "recumbent lion", "", "DETERMINATIVE", "", ""),
    ("E23", 0x130ED, "lying lion", "rwD", "TRILITERAL", "", ""),
    ("E24", 0x130EE, "panther", "", "DETERMINATIVE", "", ""),
    ("E25", 0x130EF, "hippopotamus", "", "DETERMINATIVE", "", ""),
    ("E26", 0x130F0, "elephant", "", "DETERMINATIVE", "", ""),
    ("E27", 0x130F1, "giraffe", "", "DETERMINATIVE", "", ""),
    ("E28", 0x130F2, "oryx", "", "DETERMINATIVE", "", ""),
    ("E28A", 0x130F3, "oryx (variant)", "", "DETERMINATIVE", "", ""),
    ("E29", 0x130F4, "gazelle", "", "DETERMINATIVE", "", ""),
    ("E30", 0x130F5, "ibex", "", "DETERMINATIVE", "", ""),
    ("E31", 0x130F6, "goat with collar", "", "DETERMINATIVE", "", ""),
    ("E32", 0x130F7, "baboon", "", "DETERMINATIVE", "", ""),
    ("E33", 0x130F8, "monkey", "", "DETERMINATIVE", "", ""),
    ("E34", 0x130F9, "hare", "SA", "BILITERAL", "", ""),
    ("E34A", 0x130FA, "hare (variant)", "", "DETERMINATIVE", "", ""),
    ("E36", 0x130FB, "Mammals sign", "", "DETERMINATIVE", "", ""),
    ("E37", 0x130FC, "Mammals sign", "", "DETERMINATIVE", "", ""),
    ("E38", 0x130FD, "Mammals sign", "", "DETERMINATIVE", "", ""),
]
# fmt: on
