"""Category F — Parts of Mammals (65 signs)."""

# fmt: off
# Each entry: (code, hex, description, phonetic, type, logographic, det_class)
SIGNS: list[tuple[str, int, str, str, str, str, str]] = [
    ("F1", 0x130FE, "ox head", "", "DETERMINATIVE", "", ""),
    ("F1A", 0x130FF, "ox head (variant)", "", "DETERMINATIVE", "", ""),
    ("F2", 0x13100, "charging ox head", "", "DETERMINATIVE", "", ""),
    ("F3", 0x13101, "hippopotamus head", "", "DETERMINATIVE", "", ""),
    ("F4", 0x13102, "forepart of lion", "kA", "BILITERAL", "bull", ""),
    ("F5", 0x13103, "forepart of hartebeest", "", "DETERMINATIVE", "", ""),
    ("F6", 0x13104, "forepart of hartebeest reversed", "", "DETERMINATIVE", "", ""),
    ("F7", 0x13105, "ram head", "", "DETERMINATIVE", "", ""),
    ("F8", 0x13106, "forepart of ram", "", "DETERMINATIVE", "", ""),
    ("F9", 0x13107, "leopard head", "nSm", "TRILITERAL", "", ""),
    ("F10", 0x13108, "head of Seth animal", "", "DETERMINATIVE", "", ""),
    ("F11", 0x13109, "head of Seth animal on standard", "", "DETERMINATIVE", "", ""),
    ("F12", 0x1310A, "head and neck of canine", "wsr", "TRILITERAL", "mighty", ""),
    ("F13", 0x1310B, "horns", "wp", "BILITERAL", "open", ""),
    ("F13A", 0x1310C, "horns (variant)", "", "DETERMINATIVE", "", ""),
    ("F14", 0x1310D, "horns with palm branch", "", "DETERMINATIVE", "", ""),
    ("F15", 0x1310E, "horns with mace", "", "DETERMINATIVE", "", ""),
    ("F16", 0x1310F, "horn", "db", "BILITERAL", "", ""),
    ("F17", 0x13110, "horn with palm branch and sun", "", "DETERMINATIVE", "", ""),
    ("F18", 0x13111, "tusk", "ns", "BILITERAL", "", ""),
    ("F19", 0x13112, "jawbone with teeth", "", "DETERMINATIVE", "", ""),
    ("F20", 0x13113, "tongue", "", "DETERMINATIVE", "", ""),
    ("F21", 0x13114, "ear of bovine", "sDm", "TRILITERAL", "to hear", ""),
    ("F21A", 0x13115, "ear of bovine (variant)", "", "DETERMINATIVE", "", ""),
    ("F22", 0x13116, "hindquarter of lion", "Hw", "BILITERAL", "", ""),
    ("F23", 0x13117, "foreleg of ox", "xnt", "TRILITERAL", "", ""),
    ("F24", 0x13118, "foreleg of ox reversed", "", "DETERMINATIVE", "", ""),
    ("F25", 0x13119, "leg of ox", "", "DETERMINATIVE", "", ""),
    ("F26", 0x1311A, "goat skin", "Hn", "BILITERAL", "", ""),
    ("F27", 0x1311B, "skin with tail", "", "DETERMINATIVE", "", ""),
    ("F28", 0x1311C, "skin with tail and arrow", "", "DETERMINATIVE", "", ""),
    ("F29", 0x1311D, "cattle skin pierced by arrow", "sti", "TRILITERAL", "", ""),
    ("F30", 0x1311E, "water-skin", "sD", "BILITERAL", "", ""),
    ("F31", 0x1311F, "three fox skins", "ms", "BILITERAL", "birth", ""),
    ("F31A", 0x13120, "three fox skins (variant)", "", "DETERMINATIVE", "", ""),
    ("F32", 0x13121, "animal belly with tail", "X", "UNILITERAL", "", ""),
    ("F33", 0x13122, "tail", "", "DETERMINATIVE", "", ""),
    ("F34", 0x13123, "heart", "ib", "BILITERAL", "heart", ""),
    ("F35", 0x13124, "heart with windpipe", "nfr", "TRILITERAL", "good, beautiful", ""),
    ("F36", 0x13125, "lungs with windpipe", "", "DETERMINATIVE", "", ""),
    ("F37", 0x13126, "backbone and ribs with spinal cord", "", "DETERMINATIVE", "", ""),
    ("F37A", 0x13127, "backbone and ribs with spinal cord (variant)", "", "DETERMINATIVE", "", ""),
    ("F38", 0x13128, "backbone and ribs", "", "DETERMINATIVE", "", ""),
    ("F38A", 0x13129, "backbone and ribs (variant)", "", "DETERMINATIVE", "", ""),
    ("F39", 0x1312A, "backbone with spinal cord", "", "DETERMINATIVE", "", ""),
    ("F40", 0x1312B, "backbone with ribs", "Aw", "BILITERAL", "length", ""),
    ("F41", 0x1312C, "vertebral column", "", "DETERMINATIVE", "", ""),
    ("F42", 0x1312D, "rib", "", "DETERMINATIVE", "", ""),
    ("F43", 0x1312E, "ribs", "", "DETERMINATIVE", "", ""),
    ("F44", 0x1312F, "leg bone with meat", "", "DETERMINATIVE", "", ""),
    ("F45", 0x13130, "uterus", "", "DETERMINATIVE", "", ""),
    ("F45A", 0x13131, "uterus (variant)", "", "DETERMINATIVE", "", ""),
    ("F46", 0x13132, "intestine", "", "DETERMINATIVE", "", ""),
    ("F46A", 0x13133, "intestine (variant)", "", "DETERMINATIVE", "", ""),
    ("F47", 0x13134, "intestine piece", "", "DETERMINATIVE", "", ""),
    ("F47A", 0x13135, "intestine piece (variant)", "", "DETERMINATIVE", "", ""),
    ("F48", 0x13136, "intestine piece outlined", "", "DETERMINATIVE", "", ""),
    ("F49", 0x13137, "intestine coiled", "", "DETERMINATIVE", "", ""),
    ("F50", 0x13138, "combination intestine and leg", "", "DETERMINATIVE", "", ""),
    ("F51", 0x13139, "piece of flesh", "", "DETERMINATIVE", "", ""),
    ("F51A", 0x1313A, "piece of flesh (variant)", "", "DETERMINATIVE", "", ""),
    ("F51B", 0x1313B, "piece of flesh (variant)", "", "DETERMINATIVE", "", ""),
    ("F51C", 0x1313C, "piece of flesh (variant)", "", "DETERMINATIVE", "", ""),
    ("F52", 0x1313D, "excrement", "", "DETERMINATIVE", "", ""),
    ("F53", 0x1313E, "combination of F51 signs", "", "DETERMINATIVE", "", ""),
]
# fmt: on
