"""Category G — Birds (64 signs)."""

# fmt: off
# Each entry: (code, hex, description, phonetic, type, logographic, det_class)
SIGNS: list[tuple[str, int, str, str, str, str, str]] = [
    ("G1", 0x1313F, "Egyptian vulture", "A", "UNILITERAL", "", ""),
    ("G2", 0x13140, "two Egyptian vultures", "", "DETERMINATIVE", "", ""),
    ("G3", 0x13141, "combination of G1 and stroke", "", "DETERMINATIVE", "", ""),
    ("G4", 0x13142, "buzzard", "tyw", "TRILITERAL", "", ""),
    ("G5", 0x13143, "falcon", "Hr", "LOGOGRAM", "Horus", ""),
    ("G6", 0x13144, "falcon with flagellum", "", "DETERMINATIVE", "", ""),
    ("G6A", 0x13145, "falcon with flagellum (variant)", "", "DETERMINATIVE", "", ""),
    ("G7", 0x13146, "falcon on standard", "", "DETERMINATIVE", "", "god, divine"),
    ("G7A", 0x13147, "falcon on standard (variant)", "", "DETERMINATIVE", "", ""),
    ("G7B", 0x13148, "falcon on standard (variant)", "", "DETERMINATIVE", "", ""),
    ("G8", 0x13149, "falcon on standard in boat", "", "DETERMINATIVE", "", ""),
    ("G9", 0x1314A, "falcon with sun on head", "", "DETERMINATIVE", "", ""),
    ("G10", 0x1314B, "falcon on basket", "tA", "BILITERAL", "", ""),
    ("G11", 0x1314C, "image of falcon on stand", "", "DETERMINATIVE", "", ""),
    ("G11A", 0x1314D, "image of falcon on stand (variant)", "", "DETERMINATIVE", "", ""),
    ("G12", 0x1314E, "combination of G11 and stroke", "", "DETERMINATIVE", "", ""),
    ("G13", 0x1314F, "image of falcon with plumes", "", "DETERMINATIVE", "", ""),
    ("G14", 0x13150, "vulture", "mwt", "TRILITERAL", "mother", ""),
    ("G15", 0x13151, "combination of vulture and flagellum", "", "DETERMINATIVE", "", ""),
    ("G16", 0x13152, "vulture and cobra on baskets", "", "DETERMINATIVE", "", ""),
    ("G17", 0x13153, "owl", "m", "UNILITERAL", "", ""),
    ("G18", 0x13154, "two owls", "", "DETERMINATIVE", "", ""),
    ("G19", 0x13155, "combination of owl and arm", "", "DETERMINATIVE", "", ""),
    ("G20", 0x13156, "combination of owl and forearm", "", "DETERMINATIVE", "", ""),
    ("G20A", 0x13157, "combination of owl and forearm (variant)", "", "DETERMINATIVE", "", ""),
    ("G21", 0x13158, "guinea fowl", "nH", "BILITERAL", "", ""),
    ("G22", 0x13159, "hoopoe", "", "DETERMINATIVE", "", ""),
    ("G23", 0x1315A, "lapwing with twisted wings", "", "DETERMINATIVE", "", ""),
    ("G24", 0x1315B, "lapwing", "rxyt", "LOGOGRAM", "common people", ""),
    ("G25", 0x1315C, "crested ibis", "Ax", "BILITERAL", "spirit, glory", ""),
    ("G26", 0x1315D, "sacred ibis on standard", "bA", "BILITERAL", "ba-soul", ""),
    ("G26A", 0x1315E, "sacred ibis on standard (variant)", "", "DETERMINATIVE", "", ""),
    ("G27", 0x1315F, "flamingo", "", "DETERMINATIVE", "", ""),
    ("G28", 0x13160, "black ibis", "", "DETERMINATIVE", "", ""),
    ("G29", 0x13161, "jabiru", "bA", "BILITERAL", "", ""),
    ("G30", 0x13162, "three jabirus", "", "DETERMINATIVE", "", ""),
    ("G31", 0x13163, "heron on perch", "", "DETERMINATIVE", "", ""),
    ("G32", 0x13164, "heron", "", "DETERMINATIVE", "", ""),
    ("G33", 0x13165, "egret", "", "DETERMINATIVE", "", ""),
    ("G34", 0x13166, "ostrich", "", "DETERMINATIVE", "", ""),
    ("G35", 0x13167, "cormorant", "aq", "BILITERAL", "", ""),
    ("G36", 0x13168, "swallow", "wr", "BILITERAL", "great", ""),
    ("G36A", 0x13169, "swallow (variant)", "", "DETERMINATIVE", "", ""),
    ("G37", 0x1316A, "sparrow", "nDs", "TRILITERAL", "", ""),
    ("G37A", 0x1316B, "sparrow (variant)", "", "DETERMINATIVE", "", ""),
    ("G38", 0x1316C, "white-fronted goose", "", "DETERMINATIVE", "", ""),
    ("G39", 0x1316D, "pintail duck", "sA", "BILITERAL", "", ""),
    ("G40", 0x1316E, "pintail duck flying", "pA", "BILITERAL", "", ""),
    ("G41", 0x1316F, "pintail alighting", "", "DETERMINATIVE", "", ""),
    ("G42", 0x13170, "fattened duck", "", "DETERMINATIVE", "", ""),
    ("G43", 0x13171, "quail chick", "w", "UNILITERAL", "", ""),
    ("G43A", 0x13172, "quail chick (variant)", "", "DETERMINATIVE", "", ""),
    ("G44", 0x13173, "two quail chicks", "", "DETERMINATIVE", "", ""),
    ("G45", 0x13174, "combination of quail and stroke", "", "DETERMINATIVE", "", ""),
    ("G45A", 0x13175, "combination of quail and stroke (variant)", "", "DETERMINATIVE", "", ""),
    ("G46", 0x13176, "combination of quail and forearm", "", "DETERMINATIVE", "", ""),
    ("G47", 0x13177, "duckling", "", "DETERMINATIVE", "", ""),
    ("G48", 0x13178, "three ducklings in nest", "", "DETERMINATIVE", "", ""),
    ("G49", 0x13179, "three ducklings in pool", "", "DETERMINATIVE", "", ""),
    ("G50", 0x1317A, "two plovers", "pAq", "TRILITERAL", "", ""),
    ("G51", 0x1317B, "bird pecking at fish", "", "DETERMINATIVE", "", ""),
    ("G52", 0x1317C, "goose picking up grain", "", "DETERMINATIVE", "", ""),
    ("G53", 0x1317D, "human-headed bird (ba)", "", "DETERMINATIVE", "", ""),
    ("G54", 0x1317E, "plucked bird", "", "DETERMINATIVE", "", ""),
]
# fmt: on
