"""Category M — Trees and Plants (66 signs)."""

# fmt: off
# Each entry: (code, hex, description, phonetic, type, logographic, det_class)
SIGNS: list[tuple[str, int, str, str, str, str, str]] = [
    ("M1", 0x131AD, "tree", "xt", "BILITERAL", "tree, wood", ""),
    ("M1A", 0x131AE, "tree (variant)", "", "DETERMINATIVE", "", ""),
    ("M1B", 0x131AF, "tree (variant)", "", "DETERMINATIVE", "", ""),
    ("M2", 0x131B0, "plant", "", "DETERMINATIVE", "", ""),
    ("M3", 0x131B1, "branch", "Ht", "BILITERAL", "", ""),
    ("M3A", 0x131B2, "branch (variant)", "", "DETERMINATIVE", "", ""),
    ("M4", 0x131B3, "palm branch", "rnp", "TRILITERAL", "year", ""),
    ("M5", 0x131B4, "combination of palm branch and stroke", "", "DETERMINATIVE", "", ""),
    ("M6", 0x131B5, "combination of palm branch and mouth", "", "DETERMINATIVE", "", ""),
    ("M7", 0x131B6, "combination of palm branch and stool", "", "DETERMINATIVE", "", ""),
    ("M8", 0x131B7, "pool with lotus flowers", "SA", "BILITERAL", "", ""),
    ("M9", 0x131B8, "lotus flower", "", "DETERMINATIVE", "", ""),
    ("M10", 0x131B9, "lotus bud with straight stem", "", "DETERMINATIVE", "", ""),
    ("M10A", 0x131BA, "lotus bud with straight stem (variant)", "", "DETERMINATIVE", "", ""),
    ("M11", 0x131BB, "lotus bud with winding stem", "", "DETERMINATIVE", "", ""),
    ("M12", 0x131BC, "lotus plant", "xA", "BILITERAL", "", ""),
    ("M12A", 0x131BD, "lotus plant (variant)", "", "DETERMINATIVE", "", ""),
    ("M12B", 0x131BE, "lotus plant (variant)", "", "DETERMINATIVE", "", ""),
    ("M12C", 0x131BF, "lotus plant (variant)", "", "DETERMINATIVE", "", ""),
    ("M12D", 0x131C0, "lotus plant (variant)", "", "DETERMINATIVE", "", ""),
    ("M12E", 0x131C1, "lotus plant (variant)", "", "DETERMINATIVE", "", ""),
    ("M12F", 0x131C2, "lotus plant (variant)", "", "DETERMINATIVE", "", ""),
    ("M12G", 0x131C3, "lotus plant (variant)", "", "DETERMINATIVE", "", ""),
    ("M12H", 0x131C4, "lotus plant (variant)", "", "DETERMINATIVE", "", ""),
    ("M13", 0x131C5, "papyrus stem", "", "DETERMINATIVE", "", ""),
    ("M14", 0x131C6, "papyrus clump with shoots", "", "DETERMINATIVE", "", ""),
    ("M15", 0x131C7, "clump of papyrus with buds", "", "DETERMINATIVE", "", ""),
    ("M15A", 0x131C8, "clump of papyrus with buds (variant)", "", "DETERMINATIVE", "", ""),
    ("M16", 0x131C9, "clump of papyrus", "HA", "BILITERAL", "", ""),
    ("M16A", 0x131CA, "clump of papyrus (variant)", "", "DETERMINATIVE", "", ""),
    ("M17", 0x131CB, "reed", "i", "UNILITERAL", "", ""),
    ("M17A", 0x131CC, "reed (variant)", "", "DETERMINATIVE", "", ""),
    ("M18", 0x131CD, "combination of two reeds", "y", "UNILITERAL", "", ""),
    ("M19", 0x131CE, "combination of reed and mouth", "", "DETERMINATIVE", "", ""),
    ("M20", 0x131CF, "combination of reed and bread loaf", "sw", "BILITERAL", "", ""),
    ("M21", 0x131D0, "reeds with legs", "", "DETERMINATIVE", "", ""),
    ("M22", 0x131D1, "rush plant", "", "DETERMINATIVE", "", ""),
    ("M22A", 0x131D2, "rush plant (variant)", "", "DETERMINATIVE", "", ""),
    ("M23", 0x131D3, "sedge plant (Upper Egypt)", "sw", "BILITERAL", "King of Upper Egypt", ""),
    ("M24", 0x131D4, "combination of sedge and mouth", "", "DETERMINATIVE", "", ""),
    ("M24A", 0x131D5, "combination of sedge and mouth (variant)", "", "DETERMINATIVE", "", ""),
    ("M25", 0x131D6, "combination of sedge and bread", "", "DETERMINATIVE", "", ""),
    ("M26", 0x131D7, "flowering sedge", "Sma", "TRILITERAL", "", ""),
    ("M27", 0x131D8, "combination of sedge and mouth reversed", "", "DETERMINATIVE", "", ""),
    ("M28", 0x131D9, "combination of sedge signs", "", "DETERMINATIVE", "", ""),
    ("M28A", 0x131DA, "combination of sedge signs (variant)", "", "DETERMINATIVE", "", ""),
    ("M29", 0x131DB, "seed pod", "nDm", "TRILITERAL", "", ""),
    ("M30", 0x131DC, "root", "", "DETERMINATIVE", "", ""),
    ("M31", 0x131DD, "rhizome", "", "DETERMINATIVE", "", ""),
    ("M31A", 0x131DE, "rhizome (variant)", "", "DETERMINATIVE", "", ""),
    ("M32", 0x131DF, "rhizome piece", "", "DETERMINATIVE", "", ""),
    ("M33", 0x131E0, "grain", "", "DETERMINATIVE", "", ""),
    ("M33A", 0x131E1, "grain (variant)", "", "DETERMINATIVE", "", ""),
    ("M33B", 0x131E2, "grain (variant)", "", "DETERMINATIVE", "", ""),
    ("M34", 0x131E3, "ear of emmer wheat", "", "DETERMINATIVE", "", ""),
    ("M35", 0x131E4, "heap of grain", "", "DETERMINATIVE", "", ""),
    ("M36", 0x131E5, "bundle of flax", "", "DETERMINATIVE", "", ""),
    ("M37", 0x131E6, "bundle of flax stalks", "", "DETERMINATIVE", "", ""),
    ("M38", 0x131E7, "wide bundle of flax", "", "DETERMINATIVE", "", ""),
    ("M39", 0x131E8, "basket of fruit", "", "DETERMINATIVE", "", ""),
    ("M40", 0x131E9, "bundle of reeds", "is", "BILITERAL", "", ""),
    ("M40A", 0x131EA, "bundle of reeds (variant)", "", "DETERMINATIVE", "", ""),
    ("M41", 0x131EB, "piece of wood", "Hsa", "TRILITERAL", "", ""),
    ("M42", 0x131EC, "flower", "sn", "BILITERAL", "", ""),
    ("M43", 0x131ED, "vine on trellis", "", "DETERMINATIVE", "", ""),
    ("M44", 0x131EE, "thorn", "sp", "BILITERAL", "", ""),
]
# fmt: on
