"""Category N — Sky, Earth, Water (49 signs)."""

# fmt: off
# Each entry: (code, hex, description, phonetic, type, logographic, det_class)
SIGNS: list[tuple[str, int, str, str, str, str, str]] = [
    ("N1", 0x131EF, "sky", "pt", "BILITERAL", "", ""),
    ("N2", 0x131F0, "sky with sceptre", "", "DETERMINATIVE", "", "sky, heaven"),
    ("N3", 0x131F1, "sky with wavy line", "", "DETERMINATIVE", "", ""),
    ("N4", 0x131F2, "sky with rain", "", "DETERMINATIVE", "", ""),
    ("N5", 0x131F3, "sun", "ra", "LOGOGRAM", "Ra; sun; day", ""),
    ("N6", 0x131F4, "sun with uraeus", "", "DETERMINATIVE", "", ""),
    ("N7", 0x131F5, "combination of sun and stroke", "", "DETERMINATIVE", "", ""),
    ("N8", 0x131F6, "sunshine", "", "DETERMINATIVE", "", ""),
    ("N9", 0x131F7, "moon with lower section", "", "DETERMINATIVE", "", ""),
    ("N10", 0x131F8, "moon disk", "", "DETERMINATIVE", "", ""),
    ("N11", 0x131F9, "crescent moon", "", "DETERMINATIVE", "", ""),
    ("N12", 0x131FA, "crescent and star", "", "DETERMINATIVE", "", ""),
    ("N13", 0x131FB, "combination of crescent and star", "", "DETERMINATIVE", "", ""),
    ("N14", 0x131FC, "star", "sbA", "TRILITERAL", "star", ""),
    ("N15", 0x131FD, "star in circle", "", "DETERMINATIVE", "", ""),
    ("N16", 0x131FE, "flat alluvial land", "tA", "LOGOGRAM", "land, earth", ""),
    ("N17", 0x131FF, "land with grain", "tA", "LOGOGRAM", "", ""),
    ("N18", 0x13200, "sandy tract", "iw", "BILITERAL", "", ""),
    ("N18A", 0x13201, "sandy tract (variant)", "", "DETERMINATIVE", "", ""),
    ("N18B", 0x13202, "sandy tract (variant)", "", "DETERMINATIVE", "", ""),
    ("N19", 0x13203, "two sandy tracts", "iw", "BILITERAL", "", ""),
    ("N20", 0x13204, "tongue of land", "", "DETERMINATIVE", "", ""),
    ("N21", 0x13205, "short tongue of land", "", "DETERMINATIVE", "", ""),
    ("N22", 0x13206, "broad tongue of land", "", "DETERMINATIVE", "", ""),
    ("N23", 0x13207, "irrigation canal scheme (short)", "", "DETERMINATIVE", "", ""),
    ("N24", 0x13208, "irrigation canal scheme", "spAt", "TRILITERAL", "nome, district", ""),
    ("N25", 0x13209, "three hills (desert, foreign land)", "xAst", "TRILITERAL", "foreign land", ""),
    ("N25A", 0x1320A, "three hills (desert, foreign land) (variant)", "", "DETERMINATIVE", "", ""),
    ("N26", 0x1320B, "mountain", "Dw", "BILITERAL", "mountain", ""),
    ("N27", 0x1320C, "sun rising over mountain", "", "DETERMINATIVE", "", ""),
    ("N28", 0x1320D, "rays of sun over hill", "", "DETERMINATIVE", "", ""),
    ("N29", 0x1320E, "slope of hill", "q", "UNILITERAL", "high", ""),
    ("N30", 0x1320F, "mound with plants", "Dba", "TRILITERAL", "", ""),
    ("N31", 0x13210, "road with shrubs", "wAt", "TRILITERAL", "road", ""),
    ("N32", 0x13211, "lump of clay", "", "DETERMINATIVE", "", ""),
    ("N33", 0x13212, "grain of sand", "", "DETERMINATIVE", "", ""),
    ("N33A", 0x13213, "grain of sand (variant)", "", "DETERMINATIVE", "", ""),
    ("N34", 0x13214, "ingot of metal", "", "DETERMINATIVE", "", ""),
    ("N34A", 0x13215, "ingot of metal (variant)", "", "DETERMINATIVE", "", ""),
    ("N35", 0x13216, "water ripple", "n", "UNILITERAL", "", ""),
    ("N35A", 0x13217, "water ripple (variant)", "", "DETERMINATIVE", "", ""),
    ("N36", 0x13218, "canal", "mr", "BILITERAL", "", ""),
    ("N37", 0x13219, "garden pool", "S", "UNILITERAL", "", ""),
    ("N37A", 0x1321A, "garden pool (variant)", "", "DETERMINATIVE", "", ""),
    ("N38", 0x1321B, "pool with water", "", "DETERMINATIVE", "", ""),
    ("N39", 0x1321C, "pool with water variant", "", "DETERMINATIVE", "", ""),
    ("N40", 0x1321D, "pool with legs", "", "DETERMINATIVE", "", ""),
    ("N41", 0x1321E, "well with water", "Hm", "BILITERAL", "", ""),
    ("N42", 0x1321F, "well full of water", "", "DETERMINATIVE", "", ""),
]
# fmt: on
