"""Category O — Buildings, Parts of Buildings (75 signs)."""

# fmt: off
# Each entry: (code, hex, description, phonetic, type, logographic, det_class)
SIGNS: list[tuple[str, int, str, str, str, str, str]] = [
    ("O1", 0x13250, "house", "pr", "BILITERAL", "house", ""),
    ("O1A", 0x13251, "house (variant)", "", "DETERMINATIVE", "", ""),
    ("O2", 0x13252, "combination of house and mace", "", "DETERMINATIVE", "", ""),
    ("O3", 0x13253, "combination of house and tongue of land", "", "DETERMINATIVE", "", ""),
    ("O4", 0x13254, "reed shelter", "h", "UNILITERAL", "", ""),
    ("O5", 0x13255, "winding wall from upper corner", "", "DETERMINATIVE", "", ""),
    ("O5A", 0x13256, "winding wall from upper corner (variant)", "", "DETERMINATIVE", "", ""),
    ("O6", 0x13257, "enclosure", "", "DETERMINATIVE", "", ""),
    ("O6A", 0x13258, "enclosure (variant)", "", "DETERMINATIVE", "", ""),
    ("O6B", 0x13259, "enclosure (variant)", "", "DETERMINATIVE", "", ""),
    ("O6C", 0x1325A, "enclosure (variant)", "", "DETERMINATIVE", "", ""),
    ("O6D", 0x1325B, "enclosure (variant)", "", "DETERMINATIVE", "", ""),
    ("O6E", 0x1325C, "enclosure (variant)", "", "DETERMINATIVE", "", ""),
    ("O6F", 0x1325D, "enclosure (variant)", "", "DETERMINATIVE", "", ""),
    ("O7", 0x1325E, "combination of enclosure and signs", "", "DETERMINATIVE", "", ""),
    ("O8", 0x1325F, "combination of enclosure and well", "", "DETERMINATIVE", "", ""),
    ("O9", 0x13260, "combination of enclosure and bread", "", "DETERMINATIVE", "", ""),
    ("O10", 0x13261, "combination of enclosure and falcon", "", "DETERMINATIVE", "", ""),
    ("O10A", 0x13262, "combination of enclosure and falcon (variant)", "", "DETERMINATIVE", "", ""),
    ("O10B", 0x13263, "combination of enclosure and falcon (variant)", "", "DETERMINATIVE", "", ""),
    ("O10C", 0x13264, "combination of enclosure and falcon (variant)", "", "DETERMINATIVE", "", ""),
    ("O11", 0x13265, "palace", "aH", "BILITERAL", "palace", ""),
    ("O12", 0x13266, "combination of palace and forearm", "", "DETERMINATIVE", "", ""),
    ("O13", 0x13267, "battlemented enclosure with niches", "", "DETERMINATIVE", "", ""),
    ("O14", 0x13268, "part of battlemented enclosure", "", "DETERMINATIVE", "", ""),
    ("O15", 0x13269, "enclosure with mace attacking man", "", "DETERMINATIVE", "", ""),
    ("O16", 0x1326A, "gateway with serpent", "", "DETERMINATIVE", "", ""),
    ("O17", 0x1326B, "open gateway with serpent", "", "DETERMINATIVE", "", ""),
    ("O18", 0x1326C, "shrine with fence", "", "DETERMINATIVE", "", ""),
    ("O19", 0x1326D, "shrine with two plumes", "", "DETERMINATIVE", "", ""),
    ("O19A", 0x1326E, "shrine with two plumes (variant)", "", "DETERMINATIVE", "", ""),
    ("O20", 0x1326F, "shrine", "", "DETERMINATIVE", "", ""),
    ("O20A", 0x13270, "shrine (variant)", "", "DETERMINATIVE", "", ""),
    ("O21", 0x13271, "facade of shrine", "", "DETERMINATIVE", "", ""),
    ("O22", 0x13272, "booth with pole", "", "DETERMINATIVE", "", ""),
    ("O23", 0x13273, "double platform", "", "DETERMINATIVE", "", ""),
    ("O24", 0x13274, "pyramid", "", "DETERMINATIVE", "", ""),
    ("O24A", 0x13275, "pyramid (variant)", "", "DETERMINATIVE", "", ""),
    ("O25", 0x13276, "obelisk", "", "DETERMINATIVE", "", ""),
    ("O25A", 0x13277, "obelisk (variant)", "", "DETERMINATIVE", "", ""),
    ("O26", 0x13278, "stela", "", "DETERMINATIVE", "", ""),
    ("O27", 0x13279, "hall of columns", "", "DETERMINATIVE", "", ""),
    ("O28", 0x1327A, "column", "iwn", "TRILITERAL", "", ""),
    ("O29", 0x1327B, "wooden column (peg)", "aA", "BILITERAL", "", ""),
    ("O29A", 0x1327C, "wooden column (peg) (variant)", "", "DETERMINATIVE", "", ""),
    ("O30", 0x1327D, "support", "", "DETERMINATIVE", "", ""),
    ("O30A", 0x1327E, "support (variant)", "", "DETERMINATIVE", "", ""),
    ("O31", 0x1327F, "door", "Htp", "TRILITERAL", "", ""),
    ("O32", 0x13280, "gateway", "", "DETERMINATIVE", "", ""),
    ("O33", 0x13281, "facade of palace", "", "DETERMINATIVE", "", ""),
    ("O33A", 0x13282, "facade of palace (variant)", "", "DETERMINATIVE", "", ""),
    ("O34", 0x13283, "door bolt", "s", "UNILITERAL", "", ""),
    ("O35", 0x13284, "combination of bolt and legs", "", "DETERMINATIVE", "", ""),
    ("O36", 0x13285, "wall", "", "DETERMINATIVE", "", ""),
    ("O36A", 0x13286, "wall (variant)", "", "DETERMINATIVE", "", ""),
    ("O36B", 0x13287, "wall (variant)", "", "DETERMINATIVE", "", ""),
    ("O36C", 0x13288, "wall (variant)", "", "DETERMINATIVE", "", ""),
    ("O36D", 0x13289, "wall (variant)", "", "DETERMINATIVE", "", ""),
    ("O37", 0x1328A, "falling wall", "", "DETERMINATIVE", "", ""),
    ("O38", 0x1328B, "corner of wall", "", "DETERMINATIVE", "", ""),
    ("O39", 0x1328C, "stone block", "", "DETERMINATIVE", "", ""),
    ("O40", 0x1328D, "stairway", "", "DETERMINATIVE", "", ""),
    ("O41", 0x1328E, "double stairway", "", "DETERMINATIVE", "", ""),
    ("O42", 0x1328F, "fence", "", "DETERMINATIVE", "", ""),
    ("O43", 0x13290, "low wall", "", "DETERMINATIVE", "", ""),
    ("O44", 0x13291, "emblem of Min on stand", "", "DETERMINATIVE", "", ""),
    ("O45", 0x13292, "domed building", "", "DETERMINATIVE", "", ""),
    ("O46", 0x13293, "domed building on platform", "", "DETERMINATIVE", "", ""),
    ("O47", 0x13294, "shrine on sledge", "", "DETERMINATIVE", "", ""),
    ("O48", 0x13295, "enclosed mound", "", "DETERMINATIVE", "", ""),
    ("O49", 0x13296, "village with crossroads", "niwt", "LOGOGRAM", "city, town", ""),
    ("O50", 0x13297, "threshing floor with grain", "Ssp", "TRILITERAL", "", ""),
    ("O50A", 0x13298, "threshing floor with grain (variant)", "", "DETERMINATIVE", "", ""),
    ("O50B", 0x13299, "threshing floor with grain (variant)", "", "DETERMINATIVE", "", ""),
    ("O51", 0x1329A, "pile of grain", "niwt", "LOGOGRAM", "", ""),
]
# fmt: on
