"""Category S — Crowns, Dress, Staves (54 signs)."""

# fmt: off
# Each entry: (code, hex, description, phonetic, type, logographic, det_class)
SIGNS: list[tuple[str, int, str, str, str, str, str]] = [
    ("S1", 0x132D1, "white crown of Upper Egypt", "", "DETERMINATIVE", "", ""),
    ("S2", 0x132D2, "combination of white crown and stroke", "", "DETERMINATIVE", "", ""),
    ("S2A", 0x132D3, "combination of white crown and stroke (variant)", "", "DETERMINATIVE", "", ""),
    ("S3", 0x132D4, "red crown of Lower Egypt", "", "DETERMINATIVE", "", ""),
    ("S4", 0x132D5, "combination of red crown and stroke", "", "DETERMINATIVE", "", ""),
    ("S5", 0x132D6, "double crown (pschent)", "", "DETERMINATIVE", "", ""),
    ("S6", 0x132D7, "combination of double crown and plant", "", "DETERMINATIVE", "", ""),
    ("S6A", 0x132D8, "combination of double crown and plant (variant)", "", "DETERMINATIVE", "", ""),
    ("S7", 0x132D9, "blue crown (khepresh)", "", "DETERMINATIVE", "", ""),
    ("S8", 0x132DA, "atef crown", "", "DETERMINATIVE", "", ""),
    ("S9", 0x132DB, "two plumes", "", "DETERMINATIVE", "", ""),
    ("S10", 0x132DC, "headband with uraeus", "", "DETERMINATIVE", "", ""),
    ("S11", 0x132DD, "broad collar", "", "DETERMINATIVE", "", ""),
    ("S12", 0x132DE, "collar of beads", "", "DETERMINATIVE", "", ""),
    ("S13", 0x132DF, "combination of collar and ankh", "", "DETERMINATIVE", "", ""),
    ("S14", 0x132E0, "combination of S12 and S34", "", "DETERMINATIVE", "", ""),
    ("S14A", 0x132E1, "combination of S12 and S34 (variant)", "", "DETERMINATIVE", "", ""),
    ("S14B", 0x132E2, "combination of S12 and S34 (variant)", "", "DETERMINATIVE", "", ""),
    ("S15", 0x132E3, "pectoral", "", "DETERMINATIVE", "", ""),
    ("S16", 0x132E4, "pectoral variant", "", "DETERMINATIVE", "", ""),
    ("S17", 0x132E5, "pectoral with bead collar", "", "DETERMINATIVE", "", ""),
    ("S17A", 0x132E6, "pectoral with bead collar (variant)", "", "DETERMINATIVE", "", ""),
    ("S18", 0x132E7, "menat necklace collar", "", "DETERMINATIVE", "", ""),
    ("S19", 0x132E8, "seal on necklace", "", "DETERMINATIVE", "", ""),
    ("S20", 0x132E9, "seal with cylinder", "", "DETERMINATIVE", "", ""),
    ("S21", 0x132EA, "ring", "", "DETERMINATIVE", "", ""),
    ("S22", 0x132EB, "shoulder knot", "", "DETERMINATIVE", "", ""),
    ("S23", 0x132EC, "knotted cloth (dmD)", "", "DETERMINATIVE", "", ""),
    ("S24", 0x132ED, "knot of Isis (tyet)", "TAw", "TRILITERAL", "", ""),
    ("S25", 0x132EE, "garment with fringe", "", "DETERMINATIVE", "", ""),
    ("S26", 0x132EF, "apron with streamers", "", "DETERMINATIVE", "", ""),
    ("S26A", 0x132F0, "apron with streamers (variant)", "", "DETERMINATIVE", "", ""),
    ("S26B", 0x132F1, "apron with streamers (variant)", "", "DETERMINATIVE", "", ""),
    ("S27", 0x132F2, "cloth with fringe", "", "DETERMINATIVE", "", ""),
    ("S28", 0x132F3, "cloth with fringed edge", "Dba", "TRILITERAL", "", ""),
    ("S29", 0x132F4, "folded cloth", "s", "UNILITERAL", "", ""),
    ("S30", 0x132F5, "combination of folded cloth and arm", "", "DETERMINATIVE", "", ""),
    ("S31", 0x132F6, "combination of folded cloth with stroke", "", "DETERMINATIVE", "", ""),
    ("S32", 0x132F7, "cloth with fringe on top", "", "DETERMINATIVE", "", ""),
    ("S33", 0x132F8, "sandal", "", "DETERMINATIVE", "", ""),
    ("S34", 0x132F9, "ankh (life)", "anx", "TRILITERAL", "life; to live", ""),
    ("S35", 0x132FA, "fan", "", "DETERMINATIVE", "", ""),
    ("S35A", 0x132FB, "fan (variant)", "", "DETERMINATIVE", "", ""),
    ("S36", 0x132FC, "sunshade", "", "DETERMINATIVE", "", ""),
    ("S37", 0x132FD, "fan on stand", "", "DETERMINATIVE", "", ""),
    ("S38", 0x132FE, "shepherds crook (HqA)", "", "DETERMINATIVE", "", ""),
    ("S39", 0x132FF, "shepherds crook with flat end", "", "DETERMINATIVE", "", ""),
    ("S40", 0x13300, "was sceptre", "", "DETERMINATIVE", "", ""),
    ("S41", 0x13301, "sceptre with feather", "", "DETERMINATIVE", "", ""),
    ("S42", 0x13302, "was sceptre", "wAs", "TRILITERAL", "dominion", ""),
    ("S43", 0x13303, "walking stick", "", "DETERMINATIVE", "", ""),
    ("S44", 0x13304, "walking stick with handkerchief", "", "DETERMINATIVE", "", ""),
    ("S45", 0x13305, "flagellum (nekhekh)", "", "DETERMINATIVE", "", ""),
    ("S46", 0x13306, "covering", "", "DETERMINATIVE", "", ""),
]
# fmt: on
