"""Category T — Warfare, Hunting, Butchery (44 signs)."""

# fmt: off
# Each entry: (code, hex, description, phonetic, type, logographic, det_class)
SIGNS: list[tuple[str, int, str, str, str, str, str]] = [
    ("T1", 0x13307, "mace with flat head", "", "DETERMINATIVE", "", ""),
    ("T2", 0x13308, "mace with round head", "", "DETERMINATIVE", "", ""),
    ("T3", 0x13309, "mace with pointed head", "", "DETERMINATIVE", "", ""),
    ("T3A", 0x1330A, "mace with pointed head (variant)", "", "DETERMINATIVE", "", ""),
    ("T4", 0x1330B, "mace with disk head", "", "DETERMINATIVE", "", ""),
    ("T5", 0x1330C, "combination of T3 and D54", "", "DETERMINATIVE", "", ""),
    ("T6", 0x1330D, "combination of T3 and D36", "", "DETERMINATIVE", "", ""),
    ("T7", 0x1330E, "axe", "", "DETERMINATIVE", "", ""),
    ("T7A", 0x1330F, "axe (variant)", "", "DETERMINATIVE", "", ""),
    ("T8", 0x13310, "dagger", "", "DETERMINATIVE", "", ""),
    ("T8A", 0x13311, "dagger (variant)", "", "DETERMINATIVE", "", ""),
    ("T9", 0x13312, "bow", "", "DETERMINATIVE", "", ""),
    ("T9A", 0x13313, "bow (variant)", "", "DETERMINATIVE", "", ""),
    ("T10", 0x13314, "composite bow", "", "DETERMINATIVE", "", ""),
    ("T11", 0x13315, "arrow", "", "DETERMINATIVE", "", ""),
    ("T11A", 0x13316, "arrow (variant)", "", "DETERMINATIVE", "", ""),
    ("T12", 0x13317, "bow string", "", "DETERMINATIVE", "", ""),
    ("T13", 0x13318, "joined sticks", "", "DETERMINATIVE", "", ""),
    ("T14", 0x13319, "throwstick", "qmA", "TRILITERAL", "", ""),
    ("T15", 0x1331A, "throwstick in motion", "", "DETERMINATIVE", "", ""),
    ("T16", 0x1331B, "scimitar", "", "DETERMINATIVE", "", ""),
    ("T16A", 0x1331C, "scimitar (variant)", "", "DETERMINATIVE", "", ""),
    ("T17", 0x1331D, "chariot", "", "DETERMINATIVE", "", ""),
    ("T18", 0x1331E, "crook with ties", "", "DETERMINATIVE", "", ""),
    ("T19", 0x1331F, "harpoon head with line", "", "DETERMINATIVE", "", ""),
    ("T20", 0x13320, "harpoon head", "nmt", "TRILITERAL", "", ""),
    ("T21", 0x13321, "harpoon", "Hq", "BILITERAL", "", ""),
    ("T22", 0x13322, "arrowhead", "Ss", "BILITERAL", "", ""),
    ("T23", 0x13323, "arrowhead variant", "", "DETERMINATIVE", "", ""),
    ("T24", 0x13324, "fishing net", "", "DETERMINATIVE", "", ""),
    ("T25", 0x13325, "net on pole", "", "DETERMINATIVE", "", ""),
    ("T26", 0x13326, "bird trap", "", "DETERMINATIVE", "", ""),
    ("T27", 0x13327, "bird trap variant", "", "DETERMINATIVE", "", ""),
    ("T28", 0x13328, "butcher's block", "sfx", "TRILITERAL", "", ""),
    ("T29", 0x13329, "combination of butcher block and knife", "", "DETERMINATIVE", "", ""),
    ("T30", 0x1332A, "knife", "nm", "BILITERAL", "", ""),
    ("T31", 0x1332B, "knife sharpener", "", "DETERMINATIVE", "", ""),
    ("T32", 0x1332C, "combination of knife and oar", "", "DETERMINATIVE", "", ""),
    ("T32A", 0x1332D, "combination of knife and oar (variant)", "", "DETERMINATIVE", "", ""),
    ("T33", 0x1332E, "knife blade", "", "DETERMINATIVE", "", ""),
    ("T33A", 0x1332F, "knife blade (variant)", "", "DETERMINATIVE", "", ""),
    ("T34", 0x13330, "butchers knife", "", "DETERMINATIVE", "", ""),
    ("T35", 0x13331, "combination of slaughter signs", "", "DETERMINATIVE", "", ""),
    ("T36", 0x13332, "shield", "", "DETERMINATIVE", "", ""),
]
# fmt: on
