"""Category U — Agriculture, Crafts, Professions (47 signs)."""

# fmt: off
# Each entry: (code, hex, description, phonetic, type, logographic, det_class)
SIGNS: list[tuple[str, int, str, str, str, str, str]] = [
    ("U1", 0x13333, "sickle", "mA", "BILITERAL", "", ""),
    ("U2", 0x13334, "sickle with plant", "", "DETERMINATIVE", "", ""),
    ("U3", 0x13335, "combination of sickle and bread", "", "DETERMINATIVE", "", ""),
    ("U4", 0x13336, "combination of sickle and forearm", "", "DETERMINATIVE", "", ""),
    ("U5", 0x13337, "combination of sickle signs", "", "DETERMINATIVE", "", ""),
    ("U6", 0x13338, "hoe", "", "DETERMINATIVE", "", ""),
    ("U6A", 0x13339, "hoe (variant)", "", "DETERMINATIVE", "", ""),
    ("U6B", 0x1333A, "hoe (variant)", "", "DETERMINATIVE", "", ""),
    ("U7", 0x1333B, "hoe variant", "mr", "BILITERAL", "", ""),
    ("U8", 0x1333C, "hoe with rope", "", "DETERMINATIVE", "", ""),
    ("U9", 0x1333D, "grain measure", "", "DETERMINATIVE", "", ""),
    ("U10", 0x1333E, "grain scoop", "", "DETERMINATIVE", "", ""),
    ("U11", 0x1333F, "combination of sickle and water", "", "DETERMINATIVE", "", ""),
    ("U12", 0x13340, "combination of grain and bread", "", "DETERMINATIVE", "", ""),
    ("U13", 0x13341, "plough", "", "DETERMINATIVE", "", ""),
    ("U14", 0x13342, "plough with rope", "", "DETERMINATIVE", "", ""),
    ("U15", 0x13343, "sledge", "tm", "BILITERAL", "", ""),
    ("U16", 0x13344, "sledge with jackal head", "", "DETERMINATIVE", "", ""),
    ("U17", 0x13345, "pick", "", "DETERMINATIVE", "", ""),
    ("U18", 0x13346, "pick variant", "", "DETERMINATIVE", "", ""),
    ("U19", 0x13347, "adze with wood", "", "DETERMINATIVE", "", ""),
    ("U20", 0x13348, "adze", "", "DETERMINATIVE", "", ""),
    ("U21", 0x13349, "adze on block of wood", "", "DETERMINATIVE", "", ""),
    ("U22", 0x1334A, "chisel", "", "DETERMINATIVE", "", ""),
    ("U23", 0x1334B, "chisel variant", "", "DETERMINATIVE", "", ""),
    ("U23A", 0x1334C, "chisel variant (variant)", "", "DETERMINATIVE", "", ""),
    ("U24", 0x1334D, "stone-workers tool", "", "DETERMINATIVE", "", ""),
    ("U25", 0x1334E, "drill for stone", "", "DETERMINATIVE", "", ""),
    ("U26", 0x1334F, "drill for beads", "", "DETERMINATIVE", "", ""),
    ("U27", 0x13350, "combination of drill signs", "", "DETERMINATIVE", "", ""),
    ("U28", 0x13351, "fire-drill", "DA", "BILITERAL", "", ""),
    ("U29", 0x13352, "fire-drill with smoke", "", "DETERMINATIVE", "", ""),
    ("U29A", 0x13353, "fire-drill with smoke (variant)", "", "DETERMINATIVE", "", ""),
    ("U30", 0x13354, "potters kiln", "", "DETERMINATIVE", "", ""),
    ("U31", 0x13355, "potters kiln with smoke", "", "DETERMINATIVE", "", ""),
    ("U32", 0x13356, "mortar and pestle", "", "DETERMINATIVE", "", ""),
    ("U32A", 0x13357, "mortar and pestle (variant)", "", "DETERMINATIVE", "", ""),
    ("U33", 0x13358, "pestle", "ti", "BILITERAL", "", ""),
    ("U34", 0x13359, "spindle", "", "DETERMINATIVE", "", ""),
    ("U35", 0x1335A, "combination of pestle and bread", "nmt", "TRILITERAL", "", ""),
    ("U36", 0x1335B, "fuller club", "", "DETERMINATIVE", "", ""),
    ("U37", 0x1335C, "razor", "", "DETERMINATIVE", "", ""),
    ("U38", 0x1335D, "balance", "", "DETERMINATIVE", "", ""),
    ("U39", 0x1335E, "balance with plumb", "", "DETERMINATIVE", "", ""),
    ("U40", 0x1335F, "balance variant", "", "DETERMINATIVE", "", ""),
    ("U41", 0x13360, "plumb bob", "", "DETERMINATIVE", "", ""),
    ("U42", 0x13361, "pitchfork", "", "DETERMINATIVE", "", ""),
]
# fmt: on
