"""Category V — Rope, Fibre, Baskets, Bags (77 signs)."""

# fmt: off
# Each entry: (code, hex, description, phonetic, type, logographic, det_class)
SIGNS: list[tuple[str, int, str, str, str, str, str]] = [
    ("V1", 0x13362, "coil of rope", "", "DETERMINATIVE", "", ""),
    ("V1A", 0x13363, "coil of rope (variant)", "", "DETERMINATIVE", "", ""),
    ("V1B", 0x13364, "coil of rope (variant)", "", "DETERMINATIVE", "", ""),
    ("V1C", 0x13365, "coil of rope (variant)", "", "DETERMINATIVE", "", ""),
    ("V1D", 0x13366, "coil of rope (variant)", "", "DETERMINATIVE", "", ""),
    ("V1E", 0x13367, "coil of rope (variant)", "", "DETERMINATIVE", "", ""),
    ("V1F", 0x13368, "coil of rope (variant)", "", "DETERMINATIVE", "", ""),
    ("V1G", 0x13369, "coil of rope (variant)", "", "DETERMINATIVE", "", ""),
    ("V1H", 0x1336A, "coil of rope (variant)", "", "DETERMINATIVE", "", ""),
    ("V1I", 0x1336B, "coil of rope (variant)", "", "DETERMINATIVE", "", ""),
    ("V2", 0x1336C, "combination of rope and stroke", "", "DETERMINATIVE", "", ""),
    ("V2A", 0x1336D, "combination of rope and stroke (variant)", "", "DETERMINATIVE", "", ""),
    ("V3", 0x1336E, "combination of rope and bread", "", "DETERMINATIVE", "", ""),
    ("V4", 0x1336F, "lasso", "wA", "BILITERAL", "", ""),
    ("V5", 0x13370, "combination of lasso and stroke", "", "DETERMINATIVE", "", ""),
    ("V6", 0x13371, "cord on stick", "Ss", "BILITERAL", "", ""),
    ("V7", 0x13372, "looped cord", "snT", "TRILITERAL", "", ""),
    ("V7A", 0x13373, "looped cord (variant)", "", "DETERMINATIVE", "", ""),
    ("V7B", 0x13374, "looped cord (variant)", "", "DETERMINATIVE", "", ""),
    ("V8", 0x13375, "combination of looped cord and stroke", "", "DETERMINATIVE", "", ""),
    ("V9", 0x13376, "cartouche (royal ring)", "", "DETERMINATIVE", "", ""),
    ("V10", 0x13377, "cartouche with crossbar", "", "DETERMINATIVE", "", ""),
    ("V11", 0x13378, "ring with bead", "", "DETERMINATIVE", "", ""),
    ("V11A", 0x13379, "ring with bead (variant)", "", "DETERMINATIVE", "", ""),
    ("V11B", 0x1337A, "ring with bead (variant)", "", "DETERMINATIVE", "", ""),
    ("V11C", 0x1337B, "ring with bead (variant)", "", "DETERMINATIVE", "", ""),
    ("V12", 0x1337C, "rope with ties", "", "DETERMINATIVE", "", ""),
    ("V12A", 0x1337D, "rope with ties (variant)", "", "DETERMINATIVE", "", ""),
    ("V12B", 0x1337E, "rope with ties (variant)", "", "DETERMINATIVE", "", ""),
    ("V13", 0x1337F, "tethering rope", "T", "UNILITERAL", "", ""),
    ("V14", 0x13380, "combination of rope and legs", "", "DETERMINATIVE", "", ""),
    ("V15", 0x13381, "combination of rope and bread loaf", "", "DETERMINATIVE", "", ""),
    ("V16", 0x13382, "hobble for cattle", "sA", "BILITERAL", "", ""),
    ("V17", 0x13383, "shelter of reeds", "", "DETERMINATIVE", "", ""),
    ("V18", 0x13384, "shelter of reeds variant", "", "DETERMINATIVE", "", ""),
    ("V19", 0x13385, "hobble with leading rope", "", "DETERMINATIVE", "", ""),
    ("V20", 0x13386, "cattle hobble", "", "DETERMINATIVE", "", ""),
    ("V20A", 0x13387, "cattle hobble (variant)", "", "DETERMINATIVE", "", ""),
    ("V20B", 0x13388, "cattle hobble (variant)", "", "DETERMINATIVE", "", ""),
    ("V20C", 0x13389, "cattle hobble (variant)", "", "DETERMINATIVE", "", ""),
    ("V20D", 0x1338A, "cattle hobble (variant)", "", "DETERMINATIVE", "", ""),
    ("V20E", 0x1338B, "cattle hobble (variant)", "", "DETERMINATIVE", "", ""),
    ("V20F", 0x1338C, "cattle hobble (variant)", "", "DETERMINATIVE", "", ""),
    ("V20G", 0x1338D, "cattle hobble (variant)", "", "DETERMINATIVE", "", ""),
    ("V20H", 0x1338E, "cattle hobble (variant)", "", "DETERMINATIVE", "", ""),
    ("V20I", 0x1338F, "cattle hobble (variant)", "", "DETERMINATIVE", "", ""),
    ("V20J", 0x13390, "cattle hobble (variant)", "", "DETERMINATIVE", "", ""),
    ("V20K", 0x13391, "cattle hobble (variant)", "", "DETERMINATIVE", "", ""),
    ("V20L", 0x13392, "cattle hobble (variant)", "", "DETERMINATIVE", "", ""),
    ("V21", 0x13393, "fetter", "", "DETERMINATIVE", "", ""),
    ("V22", 0x13394, "whip", "mn", "BILITERAL", "", ""),
    ("V23", 0x13395, "whip variant", "", "DETERMINATIVE", "", ""),
    ("V23A", 0x13396, "whip variant (variant)", "", "DETERMINATIVE", "", ""),
    ("V24", 0x13397, "string with bow", "wD", "BILITERAL", "", ""),
    ("V25", 0x13398, "cord with seal", "wAD", "TRILITERAL", "", ""),
    ("V26", 0x13399, "stand with vessel", "", "DETERMINATIVE", "", ""),
    ("V27", 0x1339A, "combination of stand signs", "", "DETERMINATIVE", "", ""),
    ("V28", 0x1339B, "wick of twisted flax", "H", "UNILITERAL", "", ""),
    ("V28A", 0x1339C, "wick of twisted flax (variant)", "", "DETERMINATIVE", "", ""),
    ("V29", 0x1339D, "swab", "", "DETERMINATIVE", "", ""),
    ("V29A", 0x1339E, "swab (variant)", "", "DETERMINATIVE", "", ""),
    ("V30", 0x1339F, "basket", "nb", "BILITERAL", "", ""),
    ("V30A", 0x133A0, "basket (variant)", "", "DETERMINATIVE", "", ""),
    ("V31", 0x133A1, "basket with handle", "k", "UNILITERAL", "", ""),
    ("V31A", 0x133A2, "basket with handle (variant)", "", "DETERMINATIVE", "", ""),
    ("V32", 0x133A3, "combination of basket and bread", "", "DETERMINATIVE", "", ""),
    ("V33", 0x133A4, "bag tied at top", "", "DETERMINATIVE", "", ""),
    ("V33A", 0x133A5, "bag tied at top (variant)", "", "DETERMINATIVE", "", ""),
    ("V34", 0x133A6, "bag with handle", "", "DETERMINATIVE", "", ""),
    ("V35", 0x133A7, "bag with legs", "", "DETERMINATIVE", "", ""),
    ("V36", 0x133A8, "receptacle", "", "DETERMINATIVE", "", ""),
    ("V37", 0x133A9, "bandage roll", "", "DETERMINATIVE", "", ""),
    ("V37A", 0x133AA, "bandage roll (variant)", "", "DETERMINATIVE", "", ""),
    ("V38", 0x133AB, "bandage", "", "DETERMINATIVE", "", ""),
    ("V39", 0x133AC, "measuring cord with knots", "", "DETERMINATIVE", "", ""),
    ("V40", 0x133AD, "hobble variant", "", "DETERMINATIVE", "", ""),
    ("V40A", 0x133AE, "hobble variant (variant)", "", "DETERMINATIVE", "", ""),
]
# fmt: on
