"""Category Z — Strokes and Geometric Figures (41 signs)."""

# fmt: off
# Each entry: (code, hex, description, phonetic, type, logographic, det_class)
SIGNS: list[tuple[str, int, str, str, str, str, str]] = [
    ("Z1", 0x133E4, "single stroke", "|", "NUMBER", "1; ideogram indicator", ""),
    ("Z2", 0x133E5, "three strokes (plural)", "", "DETERMINATIVE", "", ""),
    ("Z2A", 0x133E6, "three strokes (plural) (variant)", "", "DETERMINATIVE", "", ""),
    ("Z2B", 0x133E7, "three strokes (plural) (variant)", "", "DETERMINATIVE", "", ""),
    ("Z2C", 0x133E8, "three strokes (plural) (variant)", "", "DETERMINATIVE", "", ""),
    ("Z2D", 0x133E9, "three strokes (plural) (variant)", "", "DETERMINATIVE", "", ""),
    ("Z3", 0x133EA, "three strokes vertical", "", "DETERMINATIVE", "", ""),
    ("Z3A", 0x133EB, "three strokes vertical (variant)", "", "DETERMINATIVE", "", ""),
    ("Z3B", 0x133EC, "three strokes vertical (variant)", "", "DETERMINATIVE", "", ""),
    ("Z4", 0x133ED, "two diagonal strokes (dual)", "", "DETERMINATIVE", "", ""),
    ("Z4A", 0x133EE, "two diagonal strokes (dual) (variant)", "", "DETERMINATIVE", "", ""),
    ("Z5", 0x133EF, "diagonal stroke", "", "DETERMINATIVE", "", ""),
    ("Z5A", 0x133F0, "diagonal stroke (variant)", "", "DETERMINATIVE", "", ""),
    ("Z6", 0x133F1, "substitute for offensive sign", "", "DETERMINATIVE", "", ""),
    ("Z7", 0x133F2, "coil (cursive w)", "W", "ABBREVIATION", "", ""),
    ("Z8", 0x133F3, "oval", "", "DETERMINATIVE", "", ""),
    ("Z9", 0x133F4, "crossed diagonal lines", "", "DETERMINATIVE", "", ""),
    ("Z10", 0x133F5, "crossed sticks", "", "DETERMINATIVE", "", ""),
    ("Z11", 0x133F6, "two crossed planks", "imi", "TRILITERAL", "", ""),
    ("Z12", 0x133F7, "hieratic sign", "", "DETERMINATIVE", "", ""),
    ("Z13", 0x133F8, "hieratic sign variant", "", "DETERMINATIVE", "", ""),
    ("Z14", 0x133F9, "hieratic joined sign", "", "DETERMINATIVE", "", ""),
    ("Z15", 0x133FA, "combination stroke sign", "", "DETERMINATIVE", "", ""),
    ("Z15A", 0x133FB, "combination stroke sign (variant)", "", "DETERMINATIVE", "", ""),
    ("Z15B", 0x133FC, "combination stroke sign (variant)", "", "DETERMINATIVE", "", ""),
    ("Z15C", 0x133FD, "combination stroke sign (variant)", "", "DETERMINATIVE", "", ""),
    ("Z15D", 0x133FE, "combination stroke sign (variant)", "", "DETERMINATIVE", "", ""),
    ("Z15E", 0x133FF, "combination stroke sign (variant)", "", "DETERMINATIVE", "", ""),
    ("Z15F", 0x13400, "combination stroke sign (variant)", "", "DETERMINATIVE", "", ""),
    ("Z15G", 0x13401, "combination stroke sign (variant)", "", "DETERMINATIVE", "", ""),
    ("Z15H", 0x13402, "combination stroke sign (variant)", "", "DETERMINATIVE", "", ""),
    ("Z15I", 0x13403, "combination stroke sign (variant)", "", "DETERMINATIVE", "", ""),
    ("Z16", 0x13404, "combination stroke sign variant", "", "DETERMINATIVE", "", ""),
    ("Z16A", 0x13405, "combination stroke sign variant (variant)", "", "DETERMINATIVE", "", ""),
    ("Z16B", 0x13406, "combination stroke sign variant (variant)", "", "DETERMINATIVE", "", ""),
    ("Z16C", 0x13407, "combination stroke sign variant (variant)", "", "DETERMINATIVE", "", ""),
    ("Z16D", 0x13408, "combination stroke sign variant (variant)", "", "DETERMINATIVE", "", ""),
    ("Z16E", 0x13409, "combination stroke sign variant (variant)", "", "DETERMINATIVE", "", ""),
    ("Z16F", 0x1340A, "combination stroke sign variant (variant)", "", "DETERMINATIVE", "", ""),
    ("Z16G", 0x1340B, "combination stroke sign variant (variant)", "", "DETERMINATIVE", "", ""),
    ("Z16H", 0x1340C, "combination stroke sign variant (variant)", "", "DETERMINATIVE", "", ""),
]
# fmt: on
