#!/usr/bin/env python3
"""Generate gardiner_data package from Unicode database + curated descriptions.

Run:  python scripts/build_gardiner_data.py

Reads every character in U+13000-U+1342E, parses Gardiner codes from the
Unicode character names, applies curated descriptions/phonetics/types,
and writes one Python data file per Gardiner category into
app/core/gardiner_data/.

Sources:
- Unicode 15.0 Egyptian Hieroglyphs block (U+13000-U+1342F)
- Gardiner, A.H. (1957) Egyptian Grammar, 3rd ed., Sign List
- Allen, J.P. (2014) Middle Egyptian, 3rd ed.
- Wikipedia "List of Egyptian hieroglyphs"
"""

from __future__ import annotations

import re
import unicodedata
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent / "app" / "core" / "gardiner_data"

# ── Category metadata ──
CATEGORY_META: dict[str, tuple[str, str]] = {
    "A": ("Man and his Activities", "a_man"),
    "B": ("Woman and her Activities", "b_woman"),
    "C": ("Anthropomorphic Deities", "c_deities"),
    "D": ("Parts of the Human Body", "d_body"),
    "E": ("Mammals", "e_mammals"),
    "F": ("Parts of Mammals", "f_parts_mammals"),
    "G": ("Birds", "g_birds"),
    "H": ("Parts of Birds", "h_parts_birds"),
    "I": ("Amphibians and Reptiles", "i_reptiles"),
    "K": ("Fish and Parts of Fish", "k_fish"),
    "L": ("Invertebrates and Lesser Animals", "l_invertebrates"),
    "M": ("Trees and Plants", "m_plants"),
    "N": ("Sky, Earth, Water", "n_sky_earth"),
    "O": ("Buildings, Parts of Buildings", "o_buildings"),
    "P": ("Ships and Parts of Ships", "p_ships"),
    "Q": ("Domestic and Funerary Furniture", "q_furniture"),
    "R": ("Temple Furniture and Sacred Emblems", "r_temple"),
    "S": ("Crowns, Dress, Staves", "s_crowns"),
    "T": ("Warfare, Hunting, Butchery", "t_warfare"),
    "U": ("Agriculture, Crafts, Professions", "u_agriculture"),
    "V": ("Rope, Fibre, Baskets, Bags", "v_rope"),
    "W": ("Vessels of Stone and Earthenware", "w_vessels"),
    "X": ("Loaves and Cakes", "x_loaves"),
    "Y": ("Writings, Games, Music", "y_writings"),
    "Z": ("Strokes and Geometric Figures", "z_strokes"),
    "Aa": ("Unclassified", "aa_unclassified"),
}

# ── Sign descriptions ──
# Every sign gets a description: base signs are manually curated from
# Gardiner's sign list; sub-variants auto-derive from parent.
DESC: dict[str, str] = {
    # ═══ A: Man and his Activities ═══
    "A1": "seated man",
    "A2": "man with hand to mouth",
    "A3": "man sitting on heel",
    "A4": "seated man with hands raised",
    "A5": "man hiding behind wall",
    "A6": "man under vase from which water flows",
    "A7": "fatigued man",
    "A8": "man performing hnw-rite",
    "A9": "man steadying basket on head",
    "A10": "seated man holding oar",
    "A11": "seated man holding scepter and staff",
    "A12": "soldier with bow and quiver",
    "A13": "man with arms tied behind back",
    "A14": "falling man with blood streaming from head",
    "A15": "man falling",
    "A16": "man bowing down",
    "A17": "child sitting with hand to mouth",
    "A18": "child wearing red crown",
    "A19": "bent man leaning on staff",
    "A20": "man leaning on forked staff",
    "A21": "man holding staff with handkerchief",
    "A22": "statue of man with staff and scepter",
    "A23": "king with staff and mace",
    "A24": "man striking with both hands",
    "A25": "man striking, left arm behind back",
    "A26": "man with one arm pointing forward",
    "A27": "hastening man",
    "A28": "man with both hands raised",
    "A29": "man upside down",
    "A30": "man with hands raised in front",
    "A31": "man with hands raised behind",
    "A32": "man dancing with arms to back",
    "A33": "man with stick and bundle on shoulder",
    "A34": "man pounding in mortar",
    "A35": "man building wall",
    "A36": "man kneading into vessel",
    "A37": "man in vessel",
    "A38": "man holding necks of two animals",
    "A39": "man on two giraffes",
    "A40": "seated god",
    "A41": "king with uraeus",
    "A42": "king with uraeus and flagellum",
    "A43": "king wearing white crown",
    "A44": "king wearing white crown with flagellum",
    "A45": "king wearing red crown",
    "A46": "king wearing red crown with flagellum",
    "A47": "shepherd seated wrapped in mantle",
    "A48": "beardless man sitting with knife",
    "A49": "seated Syrian holding stick",
    "A50": "noble on chair",
    "A51": "noble on chair with flagellum",
    "A52": "noble squatting with flagellum",
    "A53": "standing mummy",
    "A54": "lying mummy",
    "A55": "mummy on bed",
    "A56": "seated man holding stick",
    "A57": "man holding loaf on mat",
    "A58": "man applying hoe to ground",
    "A59": "man threatening with stick",
    "A60": "man sowing seeds",
    "A61": "man looking over shoulder",
    "A62": "Asiatic",
    "A63": "king on throne holding staff",
    "A64": "man sitting on heels holding cup",
    "A65": "man in tunic with mace and staff",
    "A66": "man holding sistrum",
    "A67": "dwarf",
    "A68": "man holding up knife",
    "A69": "seated man with raised right arm",
    "A70": "seated man with raised arms",
    # ═══ B: Woman and her Activities ═══
    "B1": "seated woman",
    "B2": "pregnant woman",
    "B3": "woman giving birth",
    "B4": "combination of B3 and three skins",
    "B5": "woman suckling child",
    "B6": "woman seated on chair with child on lap",
    "B7": "queen wearing diadem and carrying flower",
    "B8": "woman holding lotus flower",
    "B9": "woman holding sistrum",
    # ═══ C: Anthropomorphic Deities ═══
    "C1": "god with sun-disk and uraeus",
    "C2": "god with falcon head, sun-disk and ankh",
    "C3": "god with ibis head",
    "C4": "god with ram head",
    "C5": "god with ram head and ankh",
    "C6": "god with jackal head",
    "C7": "god with Seth-animal head",
    "C8": "ithyphallic god with two plumes",
    "C9": "goddess with horned sun-disk",
    "C10": "goddess with feather on head",
    "C11": "god with arms supporting sky",
    "C12": "god with two plumes and scepter",
    "C13": "god with two plumes and scepter reversed",
    "C14": "god with two plumes and scimitar",
    "C15": "god with two plumes and scimitar reversed",
    "C16": "god with red crown and ankh",
    "C17": "god with falcon head and two plumes",
    "C18": "squatting god with plumes",
    "C19": "mummy-shaped god",
    "C20": "mummy-shaped god in shrine",
    "C21": "figure of Bes",
    "C22": "god with falcon head and moon-disk",
    "C23": "goddess with feline head and sun-disk",
    "C24": "god with red crown and scepter",
    # ═══ D: Parts of the Human Body ═══
    "D1": "head in profile",
    "D2": "face",
    "D3": "hair",
    "D4": "eye",
    "D5": "eye with paint",
    "D6": "eye with painted upper lid",
    "D7": "eye with painted lower lid",
    "D8": "eye enclosed in sandy tract",
    "D9": "eye with flowing tears",
    "D10": "Eye of Horus",
    "D11": "left part of Eye of Horus",
    "D12": "pupil of Eye of Horus",
    "D13": "eyebrow",
    "D14": "right part of Eye of Horus",
    "D15": "diagonal of Eye of Horus",
    "D16": "vertical mark of Eye of Horus",
    "D17": "diagonal and vertical of Eye of Horus",
    "D18": "ear",
    "D19": "nose, eye and cheek",
    "D20": "nose, eye and cheek (cursive)",
    "D21": "mouth",
    "D22": "mouth with two strokes",
    "D23": "mouth with three strokes",
    "D24": "upper lip with teeth",
    "D25": "two lips",
    "D26": "liquid issuing from lips",
    "D27": "small breast",
    "D28": "two arms upraised (ka)",
    "D29": "combination of D28 and R12",
    "D30": "two arms with tail",
    "D31": "arms embracing club with seal",
    "D32": "arms embracing",
    "D33": "arms rowing",
    "D34": "arms holding shield and axe",
    "D35": "arms in gesture of negation",
    "D36": "forearm",
    "D37": "forearm with bread",
    "D38": "forearm with rounded loaf",
    "D39": "forearm with offering bowl",
    "D40": "forearm with stick",
    "D41": "forearm with palm down",
    "D42": "forearm with hand from above",
    "D43": "forearm striking",
    "D44": "forearm with flail",
    "D45": "forearm with wand",
    "D46": "hand",
    "D47": "hand with palm up",
    "D48": "hand without thumb",
    "D49": "fist",
    "D50": "one finger pointing",
    "D51": "one finger vertical",
    "D52": "phallus",
    "D53": "phallus with emission",
    "D54": "legs walking",
    "D55": "legs walking backwards",
    "D56": "leg",
    "D57": "leg with flesh",
    "D58": "foot",
    "D59": "foot with toes",
    "D60": "water flowing between legs",
    "D61": "toes",
    "D62": "two toes",
    "D63": "two toes variant",
    "D64": "hand with forearm",
    "D65": "foot reversed",
    "D66": "combination of leg signs",
    "D67": "three dots",
    # ═══ E: Mammals ═══
    "E1": "bull",
    "E2": "bull charging",
    "E3": "calf",
    "E4": "sacred cow",
    "E5": "cow suckling calf",
    "E6": "horse",
    "E7": "donkey",
    "E8": "kid (young goat)",
    "E9": "newborn baboon",
    "E10": "ram",
    "E11": "ram lying down",
    "E12": "pig",
    "E13": "cat",
    "E14": "dog",
    "E15": "lying dog",
    "E16": "lying dog with elongated tail",
    "E17": "jackal",
    "E18": "seated wolf",
    "E19": "canine on shrine",
    "E20": "Set animal",
    "E21": "lying Set animal",
    "E22": "recumbent lion",
    "E23": "lying lion",
    "E24": "panther",
    "E25": "hippopotamus",
    "E26": "elephant",
    "E27": "giraffe",
    "E28": "oryx",
    "E29": "gazelle",
    "E30": "ibex",
    "E31": "goat with collar",
    "E32": "baboon",
    "E33": "monkey",
    "E34": "hare",
    # ═══ F: Parts of Mammals ═══
    "F1": "ox head",
    "F2": "charging ox head",
    "F3": "hippopotamus head",
    "F4": "forepart of lion",
    "F5": "forepart of hartebeest",
    "F6": "forepart of hartebeest reversed",
    "F7": "ram head",
    "F8": "forepart of ram",
    "F9": "leopard head",
    "F10": "head of Seth animal",
    "F11": "head of Seth animal on standard",
    "F12": "head and neck of canine",
    "F13": "horns",
    "F14": "horns with palm branch",
    "F15": "horns with mace",
    "F16": "horn",
    "F17": "horn with palm branch and sun",
    "F18": "tusk",
    "F19": "jawbone with teeth",
    "F20": "tongue",
    "F21": "ear of bovine",
    "F22": "hindquarter of lion",
    "F23": "foreleg of ox",
    "F24": "foreleg of ox reversed",
    "F25": "leg of ox",
    "F26": "goat skin",
    "F27": "skin with tail",
    "F28": "skin with tail and arrow",
    "F29": "cattle skin pierced by arrow",
    "F30": "water-skin",
    "F31": "three fox skins",
    "F32": "animal belly with tail",
    "F33": "tail",
    "F34": "heart",
    "F35": "heart with windpipe",
    "F36": "lungs with windpipe",
    "F37": "backbone and ribs with spinal cord",
    "F38": "backbone and ribs",
    "F39": "backbone with spinal cord",
    "F40": "backbone with ribs",
    "F41": "vertebral column",
    "F42": "rib",
    "F43": "ribs",
    "F44": "leg bone with meat",
    "F45": "uterus",
    "F46": "intestine",
    "F47": "intestine piece",
    "F48": "intestine piece outlined",
    "F49": "intestine coiled",
    "F50": "combination intestine and leg",
    "F51": "piece of flesh",
    "F52": "excrement",
    "F53": "combination of F51 signs",
    # ═══ G: Birds ═══
    "G1": "Egyptian vulture",
    "G2": "two Egyptian vultures",
    "G3": "combination of G1 and stroke",
    "G4": "buzzard",
    "G5": "falcon",
    "G6": "falcon with flagellum",
    "G7": "falcon on standard",
    "G8": "falcon on standard in boat",
    "G9": "falcon with sun on head",
    "G10": "falcon on basket",
    "G11": "image of falcon on stand",
    "G12": "combination of G11 and stroke",
    "G13": "image of falcon with plumes",
    "G14": "vulture",
    "G15": "combination of vulture and flagellum",
    "G16": "vulture and cobra on baskets",
    "G17": "owl",
    "G18": "two owls",
    "G19": "combination of owl and arm",
    "G20": "combination of owl and forearm",
    "G21": "guinea fowl",
    "G22": "hoopoe",
    "G23": "lapwing with twisted wings",
    "G24": "lapwing",
    "G25": "crested ibis",
    "G26": "sacred ibis on standard",
    "G27": "flamingo",
    "G28": "black ibis",
    "G29": "jabiru",
    "G30": "three jabirus",
    "G31": "heron on perch",
    "G32": "heron",
    "G33": "egret",
    "G34": "ostrich",
    "G35": "cormorant",
    "G36": "swallow",
    "G37": "sparrow",
    "G38": "white-fronted goose",
    "G39": "pintail duck",
    "G40": "pintail duck flying",
    "G41": "pintail alighting",
    "G42": "fattened duck",
    "G43": "quail chick",
    "G44": "two quail chicks",
    "G45": "combination of quail and stroke",
    "G46": "combination of quail and forearm",
    "G47": "duckling",
    "G48": "three ducklings in nest",
    "G49": "three ducklings in pool",
    "G50": "two plovers",
    "G51": "bird pecking at fish",
    "G52": "goose picking up grain",
    "G53": "human-headed bird (ba)",
    "G54": "plucked bird",
    # ═══ H: Parts of Birds ═══
    "H1": "head of pintail duck",
    "H2": "head of crested bird",
    "H3": "head of spoonbill",
    "H4": "head of vulture",
    "H5": "wing",
    "H6": "feather",
    "H7": "claw",
    "H8": "egg",
    # ═══ I: Amphibians and Reptiles ═══
    "I1": "gecko",
    "I2": "turtle",
    "I3": "crocodile",
    "I4": "baby crocodile",
    "I5": "crocodile with curved tail",
    "I6": "crocodile scales",
    "I7": "frog",
    "I8": "tadpole",
    "I9": "horned viper",
    "I10": "cobra",
    "I11": "two cobras",
    "I12": "erect cobra on basket",
    "I13": "erect cobra",
    "I14": "snake",
    "I15": "snake with horns",
    # ═══ K: Fish ═══
    "K1": "Tilapia fish",
    "K2": "Barbel fish",
    "K3": "mullet",
    "K4": "Oxyrhynchus fish",
    "K5": "Petrocephalus fish",
    "K6": "fish scale",
    "K7": "puffer fish",
    # ═══ L: Invertebrates and Lesser Animals ═══
    "L1": "scarab beetle",
    "L2": "bee",
    "L3": "fly",
    "L4": "locust",
    "L5": "centipede",
    "L6": "shell",
    "L7": "scorpion",
    "L8": "combination scorpion and reed",
    # ═══ M: Trees and Plants ═══
    "M1": "tree",
    "M2": "plant",
    "M3": "branch",
    "M4": "palm branch",
    "M5": "combination of palm branch and stroke",
    "M6": "combination of palm branch and mouth",
    "M7": "combination of palm branch and stool",
    "M8": "pool with lotus flowers",
    "M9": "lotus flower",
    "M10": "lotus bud with straight stem",
    "M11": "lotus bud with winding stem",
    "M12": "lotus plant",
    "M13": "papyrus stem",
    "M14": "papyrus clump with shoots",
    "M15": "clump of papyrus with buds",
    "M16": "clump of papyrus",
    "M17": "reed",
    "M18": "combination of two reeds",
    "M19": "combination of reed and mouth",
    "M20": "combination of reed and bread loaf",
    "M21": "reeds with legs",
    "M22": "rush plant",
    "M23": "sedge plant (Upper Egypt)",
    "M24": "combination of sedge and mouth",
    "M25": "combination of sedge and bread",
    "M26": "flowering sedge",
    "M27": "combination of sedge and mouth reversed",
    "M28": "combination of sedge signs",
    "M29": "seed pod",
    "M30": "root",
    "M31": "rhizome",
    "M32": "rhizome piece",
    "M33": "grain",
    "M34": "ear of emmer wheat",
    "M35": "heap of grain",
    "M36": "bundle of flax",
    "M37": "bundle of flax stalks",
    "M38": "wide bundle of flax",
    "M39": "basket of fruit",
    "M40": "bundle of reeds",
    "M41": "piece of wood",
    "M42": "flower",
    "M43": "vine on trellis",
    "M44": "thorn",
    # ═══ N: Sky, Earth, Water ═══
    "N1": "sky",
    "N2": "sky with sceptre",
    "N3": "sky with wavy line",
    "N4": "sky with rain",
    "N5": "sun",
    "N6": "sun with uraeus",
    "N7": "combination of sun and stroke",
    "N8": "sunshine",
    "N9": "moon with lower section",
    "N10": "moon disk",
    "N11": "crescent moon",
    "N12": "crescent and star",
    "N13": "combination of crescent and star",
    "N14": "star",
    "N15": "star in circle",
    "N16": "flat alluvial land",
    "N17": "land with grain",
    "N18": "sandy tract",
    "N19": "two sandy tracts",
    "N20": "tongue of land",
    "N21": "short tongue of land",
    "N22": "broad tongue of land",
    "N23": "irrigation canal scheme (short)",
    "N24": "irrigation canal scheme",
    "N25": "three hills (desert, foreign land)",
    "N26": "mountain",
    "N27": "sun rising over mountain",
    "N28": "rays of sun over hill",
    "N29": "slope of hill",
    "N30": "mound with plants",
    "N31": "road with shrubs",
    "N32": "lump of clay",
    "N33": "grain of sand",
    "N34": "ingot of metal",
    "N35": "water ripple",
    "N36": "canal",
    "N37": "garden pool",
    "N38": "pool with water",
    "N39": "pool with water variant",
    "N40": "pool with legs",
    "N41": "well with water",
    "N42": "well full of water",
    # ═══ O: Buildings and Parts of Buildings ═══
    "O1": "house",
    "O2": "combination of house and mace",
    "O3": "combination of house and tongue of land",
    "O4": "reed shelter",
    "O5": "winding wall from upper corner",
    "O6": "enclosure",
    "O7": "combination of enclosure and signs",
    "O8": "combination of enclosure and well",
    "O9": "combination of enclosure and bread",
    "O10": "combination of enclosure and falcon",
    "O11": "palace",
    "O12": "combination of palace and forearm",
    "O13": "battlemented enclosure with niches",
    "O14": "part of battlemented enclosure",
    "O15": "enclosure with mace attacking man",
    "O16": "gateway with serpent",
    "O17": "open gateway with serpent",
    "O18": "shrine with fence",
    "O19": "shrine with two plumes",
    "O20": "shrine",
    "O21": "facade of shrine",
    "O22": "booth with pole",
    "O23": "double platform",
    "O24": "pyramid",
    "O25": "obelisk",
    "O26": "stela",
    "O27": "hall of columns",
    "O28": "column",
    "O29": "wooden column (peg)",
    "O30": "support",
    "O31": "door",
    "O32": "gateway",
    "O33": "facade of palace",
    "O34": "door bolt",
    "O35": "combination of bolt and legs",
    "O36": "wall",
    "O37": "falling wall",
    "O38": "corner of wall",
    "O39": "stone block",
    "O40": "stairway",
    "O41": "double stairway",
    "O42": "fence",
    "O43": "low wall",
    "O44": "emblem of Min on stand",
    "O45": "domed building",
    "O46": "domed building on platform",
    "O47": "shrine on sledge",
    "O48": "enclosed mound",
    "O49": "village with crossroads",
    "O50": "threshing floor with grain",
    "O51": "pile of grain",
    # ═══ P: Ships and Parts of Ships ═══
    "P1": "boat",
    "P2": "boat with net",
    "P3": "sacred bark",
    "P4": "boat with sails",
    "P5": "sail",
    "P6": "mast",
    "P7": "combination of mast and knife",
    "P8": "oar",
    "P9": "combination of oar and stroke",
    "P10": "steering oar",
    "P11": "mooring post",
    # ═══ Q: Domestic and Funerary Furniture ═══
    "Q1": "seat (throne)",
    "Q2": "portable seat",
    "Q3": "reed stool",
    "Q4": "headrest",
    "Q5": "chest",
    "Q6": "coffin",
    "Q7": "brazier with flame",
    # ═══ R: Temple Furniture and Sacred Emblems ═══
    "R1": "high table with offerings",
    "R2": "table with slices of bread",
    "R3": "low table with offerings",
    "R4": "offering loaf on mat",
    "R5": "censer with flame",
    "R6": "table with bread and vase",
    "R7": "bowl with smoke",
    "R8": "cloth wound on pole (nTr flag)",
    "R9": "combination of cloth on pole and bag",
    "R10": "combination of cloth on pole and mat",
    "R11": "djed pillar",
    "R12": "standard with feather and streamer",
    "R13": "falcon on standard with feather",
    "R14": "feather on standard with streamer",
    "R15": "standard with feather and streamer variant",
    "R16": "sceptre with feathers on standard",
    "R17": "wig on pole",
    "R18": "combination of wig on pole and cloth",
    "R19": "sceptre with Was head on standard",
    "R20": "flower on stand",
    "R21": "flower with buds on stand",
    "R22": "two serpents on standard",
    "R23": "serpent and disk on two standards",
    "R24": "two bows tied together",
    "R25": "two feathers on pylon",
    # ═══ S: Crowns, Dress, Staves ═══
    "S1": "white crown of Upper Egypt",
    "S2": "combination of white crown and stroke",
    "S3": "red crown of Lower Egypt",
    "S4": "combination of red crown and stroke",
    "S5": "double crown (pschent)",
    "S6": "combination of double crown and plant",
    "S7": "blue crown (khepresh)",
    "S8": "atef crown",
    "S9": "two plumes",
    "S10": "headband with uraeus",
    "S11": "broad collar",
    "S12": "collar of beads",
    "S13": "combination of collar and ankh",
    "S14": "combination of S12 and S34",
    "S15": "pectoral",
    "S16": "pectoral variant",
    "S17": "pectoral with bead collar",
    "S18": "menat necklace collar",
    "S19": "seal on necklace",
    "S20": "seal with cylinder",
    "S21": "ring",
    "S22": "shoulder knot",
    "S23": "knotted cloth (dmD)",
    "S24": "knot of Isis (tyet)",
    "S25": "garment with fringe",
    "S26": "apron with streamers",
    "S27": "cloth with fringe",
    "S28": "cloth with fringed edge",
    "S29": "folded cloth",
    "S30": "combination of folded cloth and arm",
    "S31": "combination of folded cloth with stroke",
    "S32": "cloth with fringe on top",
    "S33": "sandal",
    "S34": "ankh (life)",
    "S35": "fan",
    "S36": "sunshade",
    "S37": "fan on stand",
    "S38": "shepherds crook (HqA)",
    "S39": "shepherds crook with flat end",
    "S40": "was sceptre",
    "S41": "sceptre with feather",
    "S42": "was sceptre",
    "S43": "walking stick",
    "S44": "walking stick with handkerchief",
    "S45": "flagellum (nekhekh)",
    "S46": "covering",
    # ═══ T: Warfare, Hunting, Butchery ═══
    "T1": "mace with flat head",
    "T2": "mace with round head",
    "T3": "mace with pointed head",
    "T4": "mace with disk head",
    "T5": "combination of T3 and D54",
    "T6": "combination of T3 and D36",
    "T7": "axe",
    "T8": "dagger",
    "T9": "bow",
    "T10": "composite bow",
    "T11": "arrow",
    "T12": "bow string",
    "T13": "joined sticks",
    "T14": "throwstick",
    "T15": "throwstick in motion",
    "T16": "scimitar",
    "T17": "chariot",
    "T18": "crook with ties",
    "T19": "harpoon head with line",
    "T20": "harpoon head",
    "T21": "harpoon",
    "T22": "arrowhead",
    "T23": "arrowhead variant",
    "T24": "fishing net",
    "T25": "net on pole",
    "T26": "bird trap",
    "T27": "bird trap variant",
    "T28": "butcher's block",
    "T29": "combination of butcher block and knife",
    "T30": "knife",
    "T31": "knife sharpener",
    "T32": "combination of knife and oar",
    "T33": "knife blade",
    "T34": "butchers knife",
    "T35": "combination of slaughter signs",
    "T36": "shield",
    # ═══ U: Agriculture, Crafts, Professions ═══
    "U1": "sickle",
    "U2": "sickle with plant",
    "U3": "combination of sickle and bread",
    "U4": "combination of sickle and forearm",
    "U5": "combination of sickle signs",
    "U6": "hoe",
    "U7": "hoe variant",
    "U8": "hoe with rope",
    "U9": "grain measure",
    "U10": "grain scoop",
    "U11": "combination of sickle and water",
    "U12": "combination of grain and bread",
    "U13": "plough",
    "U14": "plough with rope",
    "U15": "sledge",
    "U16": "sledge with jackal head",
    "U17": "pick",
    "U18": "pick variant",
    "U19": "adze with wood",
    "U20": "adze",
    "U21": "adze on block of wood",
    "U22": "chisel",
    "U23": "chisel variant",
    "U24": "stone-workers tool",
    "U25": "drill for stone",
    "U26": "drill for beads",
    "U27": "combination of drill signs",
    "U28": "fire-drill",
    "U29": "fire-drill with smoke",
    "U30": "potters kiln",
    "U31": "potters kiln with smoke",
    "U32": "mortar and pestle",
    "U33": "pestle",
    "U34": "spindle",
    "U35": "combination of pestle and bread",
    "U36": "fuller club",
    "U37": "razor",
    "U38": "balance",
    "U39": "balance with plumb",
    "U40": "balance variant",
    "U41": "plumb bob",
    "U42": "pitchfork",
    # ═══ V: Rope, Fibre, Baskets, Bags ═══
    "V1": "coil of rope",
    "V2": "combination of rope and stroke",
    "V3": "combination of rope and bread",
    "V4": "lasso",
    "V5": "combination of lasso and stroke",
    "V6": "cord on stick",
    "V7": "looped cord",
    "V8": "combination of looped cord and stroke",
    "V9": "cartouche (royal ring)",
    "V10": "cartouche with crossbar",
    "V11": "ring with bead",
    "V12": "rope with ties",
    "V13": "tethering rope",
    "V14": "combination of rope and legs",
    "V15": "combination of rope and bread loaf",
    "V16": "hobble for cattle",
    "V17": "shelter of reeds",
    "V18": "shelter of reeds variant",
    "V19": "hobble with leading rope",
    "V20": "cattle hobble",
    "V21": "fetter",
    "V22": "whip",
    "V23": "whip variant",
    "V24": "string with bow",
    "V25": "cord with seal",
    "V26": "stand with vessel",
    "V27": "combination of stand signs",
    "V28": "wick of twisted flax",
    "V29": "swab",
    "V30": "basket",
    "V31": "basket with handle",
    "V32": "combination of basket and bread",
    "V33": "bag tied at top",
    "V34": "bag with handle",
    "V35": "bag with legs",
    "V36": "receptacle",
    "V37": "bandage roll",
    "V38": "bandage",
    "V39": "measuring cord with knots",
    "V40": "hobble variant",
    # ═══ W: Vessels of Stone and Earthenware ═══
    "W1": "oil jar with ties",
    "W2": "oil jar without ties",
    "W3": "alabaster basin",
    "W4": "combination of basin and bread",
    "W5": "combination of basin and stroke",
    "W6": "metal vessel",
    "W7": "granite bowl",
    "W8": "granite bowl variant",
    "W9": "stone jug with handle",
    "W10": "cup",
    "W11": "jar stand",
    "W12": "jar stand with bread",
    "W13": "jar stand variant",
    "W14": "tall water jar",
    "W15": "water jar with legs",
    "W16": "water jar with rack",
    "W17": "water jar combination",
    "W18": "water jar with handles",
    "W19": "milk jug with handle",
    "W20": "milk jug variant",
    "W21": "wine jug with stopper",
    "W22": "beer jug",
    "W23": "jug with handle",
    "W24": "pot",
    "W25": "pot with legs",
    # ═══ X: Loaves and Cakes ═══
    "X1": "loaf of bread",
    "X2": "bread roll",
    "X3": "loaf on mat",
    "X4": "combination of bread signs",
    "X5": "combination of bread and bowl",
    "X6": "round loaf",
    "X7": "half loaf",
    "X8": "conical loaf on offering stand",
    # ═══ Y: Writings, Games, Music ═══
    "Y1": "papyrus roll",
    "Y2": "papyrus roll sealed",
    "Y3": "scribe's kit (palette and holder)",
    "Y4": "reed pen with palette",
    "Y5": "game board (senet)",
    "Y6": "game piece",
    "Y7": "harp",
    "Y8": "sistrum",
    # ═══ Z: Strokes and Geometric Figures ═══
    "Z1": "single stroke",
    "Z2": "three strokes (plural)",
    "Z3": "three strokes vertical",
    "Z4": "two diagonal strokes (dual)",
    "Z5": "diagonal stroke",
    "Z6": "substitute for offensive sign",
    "Z7": "coil (cursive w)",
    "Z8": "oval",
    "Z9": "crossed diagonal lines",
    "Z10": "crossed sticks",
    "Z11": "two crossed planks",
    "Z12": "hieratic sign",
    "Z13": "hieratic sign variant",
    "Z14": "hieratic joined sign",
    "Z15": "combination stroke sign",
    "Z16": "combination stroke sign variant",
    # ═══ Aa: Unclassified ═══
    "Aa1": "placenta or sieve",
    "Aa2": "pustule or gland",
    "Aa3": "unknown sign",
    "Aa4": "unknown sign with tongue",
    "Aa5": "part of steering gear",
    "Aa6": "sign with hook",
    "Aa7": "coiled sign",
    "Aa8": "irrigation channel curve",
    "Aa9": "unknown oval sign",
    "Aa10": "unknown sign with notch",
    "Aa11": "platform",
    "Aa12": "platform variant",
    "Aa13": "stand",
    "Aa14": "unknown sign with base",
    "Aa15": "unknown sign (wDa)",
    "Aa16": "unknown sign variant",
    "Aa17": "open land",
    "Aa18": "unknown sign with angle",
    "Aa19": "unknown sign with curve",
    "Aa20": "unknown pointed sign",
    "Aa21": "unknown sign",
    "Aa22": "unknown sign variant",
    "Aa23": "unknown sign with cross",
    "Aa24": "unknown curved sign",
    "Aa25": "unknown sign with notch",
    "Aa26": "unknown sign",
    "Aa27": "unknown sign (nD)",
    "Aa28": "unknown sign (qd)",
    "Aa29": "unknown sign with angles",
    "Aa30": "unknown sign with base variant",
    "Aa31": "unknown sign with knobbed end",
    "Aa32": "unknown sign with projection",
}

# ── Phonetic data ──
# code → (phonetic_value, type_code)
# Type codes: U=UNILITERAL  B=BILITERAL  T=TRILITERAL  L=LOGOGRAM  D=DETERMINATIVE  N=NUMBER  A=ABBREVIATION
PHONETICS: dict[str, tuple[str, str]] = {
    # ── Uniliterals (Egyptian "alphabet") ──
    "G1": ("A", "U"),
    "M17": ("i", "U"),
    "M18": ("y", "U"),
    "D36": ("a", "U"),
    "G43": ("w", "U"),
    "D58": ("b", "U"),
    "Q3": ("p", "U"),
    "I9": ("f", "U"),
    "G17": ("m", "U"),
    "N35": ("n", "U"),
    "D21": ("r", "U"),
    "O4": ("h", "U"),
    "V28": ("H", "U"),
    "Aa1": ("x", "U"),
    "F32": ("X", "U"),
    "S29": ("s", "U"),
    "O34": ("s", "U"),
    "N37": ("S", "U"),
    "N29": ("q", "U"),
    "V31": ("k", "U"),
    "W11": ("g", "U"),
    "X1": ("t", "U"),
    "V13": ("T", "U"),
    "D46": ("d", "U"),
    "I10": ("D", "U"),
    "Z7": ("W", "A"),
    # ── Biliterals ──
    "D4": ("ir", "B"),
    "D1": ("tp", "B"),
    "D2": ("Hr", "B"),
    "D28": ("kA", "B"),
    "D33": ("Xn", "B"),
    "D34": ("aS", "B"),
    "D35": ("n", "B"),
    "D37": ("di", "B"),
    "D39": ("mH", "B"),
    "D41": ("ni", "B"),
    "D42": ("mi", "B"),
    "D52": ("mt", "B"),
    "D53": ("mw", "B"),
    "D56": ("rd", "B"),
    "D62": ("mt", "B"),
    "E1": ("kA", "L"),
    "E9": ("sAb", "T"),
    "E17": ("mAi", "T"),
    "E23": ("rwD", "T"),
    "E34": ("SA", "B"),
    "F4": ("kA", "B"),
    "F9": ("nSm", "T"),
    "F12": ("wsr", "T"),
    "F13": ("wp", "B"),
    "F16": ("db", "B"),
    "F18": ("ns", "B"),
    "F21": ("sDm", "T"),
    "F22": ("Hw", "B"),
    "F23": ("xnt", "T"),
    "F26": ("Hn", "B"),
    "F29": ("sti", "T"),
    "F30": ("sD", "B"),
    "F31": ("ms", "B"),
    "F34": ("ib", "B"),
    "F35": ("nfr", "T"),
    "F40": ("Aw", "B"),
    "G4": ("tyw", "T"),
    "G5": ("Hr", "L"),
    "G10": ("tA", "B"),
    "G14": ("mwt", "T"),
    "G21": ("nH", "B"),
    "G24": ("rxyt", "L"),
    "G25": ("Ax", "B"),
    "G26": ("bA", "B"),
    "G29": ("bA", "B"),
    "G35": ("aq", "B"),
    "G36": ("wr", "B"),
    "G37": ("nDs", "T"),
    "G39": ("sA", "B"),
    "G40": ("pA", "B"),
    "G50": ("pAq", "T"),
    "H6": ("mAat", "T"),
    "I5": ("Hfn", "T"),
    "L1": ("xpr", "T"),
    "M1": ("xt", "B"),
    "M3": ("Ht", "B"),
    "M4": ("rnp", "T"),
    "M8": ("SA", "B"),
    "M12": ("xA", "B"),
    "M16": ("HA", "B"),
    "M20": ("sw", "B"),
    "M23": ("sw", "B"),
    "M26": ("Sma", "T"),
    "M29": ("nDm", "T"),
    "M40": ("is", "B"),
    "M41": ("Hsa", "T"),
    "M42": ("sn", "B"),
    "M44": ("sp", "B"),
    "N1": ("pt", "B"),
    "N5": ("ra", "L"),
    "N14": ("sbA", "T"),
    "N16": ("tA", "L"),
    "N17": ("tA", "L"),
    "N18": ("iw", "B"),
    "N19": ("iw", "B"),
    "N24": ("spAt", "T"),
    "N25": ("xAst", "T"),
    "N26": ("Dw", "B"),
    "N29": ("q", "U"),
    "N30": ("Dba", "T"),
    "N31": ("wAt", "T"),
    "N36": ("mr", "B"),
    "N41": ("Hm", "B"),
    "O1": ("pr", "B"),
    "O11": ("aH", "B"),
    "O28": ("iwn", "T"),
    "O29": ("aA", "B"),
    "O31": ("Htp", "T"),
    "O49": ("niwt", "L"),
    "O50": ("Ssp", "T"),
    "O51": ("niwt", "L"),
    "P1": ("dp", "B"),
    "P6": ("mxnt", "T"),
    "P8": ("xAw", "T"),
    "Q1": ("st", "B"),
    "Q7": ("snTr", "T"),
    "R4": ("Htp", "T"),
    "R8": ("nTr", "T"),
    "S24": ("TAw", "T"),
    "S28": ("Dba", "T"),
    "S34": ("anx", "T"),
    "S42": ("wAs", "T"),
    "T14": ("qmA", "T"),
    "T20": ("nmt", "T"),
    "T21": ("Hq", "B"),
    "T22": ("Ss", "B"),
    "T28": ("sfx", "T"),
    "T30": ("nm", "B"),
    "U1": ("mA", "B"),
    "U7": ("mr", "B"),
    "U15": ("tm", "B"),
    "U28": ("DA", "B"),
    "U33": ("ti", "B"),
    "U35": ("nmt", "T"),
    "V4": ("wA", "B"),
    "V6": ("Ss", "B"),
    "V7": ("snT", "T"),
    "V16": ("sA", "B"),
    "V22": ("mn", "B"),
    "V24": ("wD", "B"),
    "V25": ("wAD", "T"),
    "V30": ("nb", "B"),
    "W14": ("Hz", "B"),
    "W15": ("iab", "T"),
    "W18": ("kAb", "T"),
    "W19": ("mi", "B"),
    "W22": ("ab", "B"),
    "W24": ("nw", "B"),
    "W25": ("ini", "T"),
    "X6": ("pAt", "T"),
    "X8": ("di", "B"),
    "Y1": ("mDAt", "T"),
    "Y2": ("mnhd", "T"),
    "Y3": ("sS", "B"),
    "Y5": ("mn", "B"),
    "Z1": ("|", "N"),
    "Z11": ("imi", "T"),
    # ── Additional phonetics ──
    "A17": ("ms", "B"),
    "A19": ("jk", "B"),
    "A27": ("jn", "B"),
    "A55": ("Hs", "B"),
    "D9": ("rmi", "T"),
    "D10": ("wDAt", "T"),
    "D19": ("fnD", "T"),
    "D24": ("spt", "T"),
    "D26": ("ns", "B"),
    "D27": ("mnD", "T"),
    "D32": ("Hnk", "T"),
    "D40": ("Hwi", "T"),
    "D45": ("Dsr", "T"),
    "D50": ("Dba", "T"),
    "D54": ("", "D"),
    "D60": ("wab", "T"),
    "G7": ("", "D"),
    "N2": ("", "D"),
    "Aa15": ("wDa", "T"),
    "Aa27": ("nD", "B"),
    "Aa28": ("qd", "B"),
    "R11": ("Dd", "B"),
    "P13": ("xrw", "T"),
}

# ── Logographic values ──
LOGOGRAPHIC: dict[str, str] = {
    "E1": "bull",
    "E17": "lion",
    "F4": "bull",
    "F12": "mighty",
    "F13": "open",
    "F21": "to hear",
    "F31": "birth",
    "F34": "heart",
    "F35": "good, beautiful",
    "F40": "length",
    "G5": "Horus",
    "G14": "mother",
    "G24": "common people",
    "G25": "spirit, glory",
    "G26": "ba-soul",
    "G36": "great",
    "H6": "Maat, truth",
    "L1": "Khepri; to become",
    "M1": "tree, wood",
    "M4": "year",
    "M23": "King of Upper Egypt",
    "N5": "Ra; sun; day",
    "N14": "star",
    "N16": "land, earth",
    "N24": "nome, district",
    "N25": "foreign land",
    "N26": "mountain",
    "N29": "high",
    "N31": "road",
    "O1": "house",
    "O11": "palace",
    "O49": "city, town",
    "Q1": "throne; place",
    "Q7": "incense",
    "R4": "offering; peace",
    "R8": "god",
    "S34": "life; to live",
    "S42": "dominion",
    "X6": "cake",
    "X8": "to give",
    "Y1": "writing, abstract",
    "Y3": "scribe; writing",
    "Y5": "senet",
    "Z1": "1; ideogram indicator",
    "D4": "eye; to do, make",
    "D19": "nose",
    "D28": "ka (spirit)",
    "D56": "leg, foot",
}

# ── Determinative classes ──
DET_CLASS: dict[str, str] = {
    "D54": "motion, walking",
    "G7": "god, divine",
    "N2": "sky, heaven",
    "A55": "death",
}

# ── Alternate transliterations ──
ALT_TRANSLIT: dict[str, list[str]] = {
    "M18": ["ii", "y"],
    "O34": ["z"],
    "Z7": ["w"],
}

# ── Signs to SKIP (Nome signs — specialized geographic markers) ──
SKIP_PREFIXES = ("NL", "NU")

# ═══════════════════════════════════════════════════════════
# Type map for the data files
# ═══════════════════════════════════════════════════════════
TYPE_MAP = {
    "U": "UNILITERAL",
    "B": "BILITERAL",
    "T": "TRILITERAL",
    "L": "LOGOGRAM",
    "D": "DETERMINATIVE",
    "N": "NUMBER",
    "A": "ABBREVIATION",
}


def parse_gardiner_code(name: str) -> str | None:
    """Parse Gardiner code from Unicode character name.

    'EGYPTIAN HIEROGLYPH A001' → 'A1'
    'EGYPTIAN HIEROGLYPH A005A' → 'A5A'
    'EGYPTIAN HIEROGLYPH AA032' → 'Aa32'
    """
    m = re.match(r"EGYPTIAN HIEROGLYPH ([A-Z]+)(\d+)([A-Z]*)", name)
    if not m:
        return None
    prefix, num_str, suffix = m.groups()
    # Normalize prefix: "AA" → "Aa", "NL" → "NL", "NU" → "NU"
    if prefix == "AA":
        prefix = "Aa"
    return f"{prefix}{int(num_str)}{suffix}"


def get_category(code: str) -> str:
    """Extract Gardiner category from code: 'A5A' → 'A', 'Aa15' → 'Aa'."""
    if code.startswith("Aa"):
        return "Aa"
    if code.startswith("NL"):
        return "NL"
    if code.startswith("NU"):
        return "NU"
    return code[0]


def get_parent_code(code: str) -> str | None:
    """Get parent code for sub-variant: 'A5A' → 'A5', 'D50B' → 'D50'.

    Returns None for base signs like 'A5' or 'D50'.
    """
    m = re.match(r"([A-Za-z]+\d+)([A-Z])$", code)
    if m:
        return m.group(1)
    return None


def generate():
    """Generate the gardiner_data package."""
    print("Scanning Unicode Egyptian Hieroglyphs block (U+13000–U+1342E)...")

    # Collect all signs from Unicode database
    signs_by_category: dict[str, list[dict]] = {}
    total = 0

    for cp in range(0x13000, 0x1342F):
        char = chr(cp)
        name = unicodedata.name(char, "")
        if not name:
            continue

        code = parse_gardiner_code(name)
        if not code:
            continue

        cat = get_category(code)
        if cat in SKIP_PREFIXES:
            continue

        # Get description
        desc = DESC.get(code)
        if not desc:
            parent = get_parent_code(code)
            if parent and parent in DESC:
                desc = f"{DESC[parent]} (variant)"
            else:
                cat_name = CATEGORY_META.get(cat, ("", ""))[0]
                desc = f"{cat_name} sign" if cat_name else f"hieroglyph {code}"

        # Get phonetic data
        phon_val = ""
        type_code = "D"  # default: determinative
        if code in PHONETICS:
            phon_val, type_code = PHONETICS[code]

        # Get logographic value
        logo = LOGOGRAPHIC.get(code, "")

        # Get determinative class
        det = DET_CLASS.get(code, "")

        sign = {
            "code": code,
            "hex": cp,
            "desc": desc,
            "phon": phon_val,
            "type": type_code,
            "logo": logo,
            "det": det,
        }

        signs_by_category.setdefault(cat, []).append(sign)
        total += 1

    print(f"  Found {total} signs across {len(signs_by_category)} categories")

    # Create output directory
    BASE_DIR.mkdir(parents=True, exist_ok=True)
    print(f"  Output: {BASE_DIR}")

    # Generate per-category data files
    module_imports = []

    for cat_code in sorted(signs_by_category.keys(), key=lambda c: (len(c), c)):
        meta = CATEGORY_META.get(cat_code)
        if not meta:
            print(f"  SKIP unknown category: {cat_code}")
            continue

        cat_name, file_stem = meta
        signs = signs_by_category[cat_code]

        lines = [
            f'"""Category {cat_code} \u2014 {cat_name} ({len(signs)} signs)."""',
            "",
            "# fmt: off",
            "# Each entry: (code, hex, description, phonetic, type, logographic, det_class)",
            "SIGNS: list[tuple[str, int, str, str, str, str, str]] = [",
        ]

        for s in signs:
            code = s["code"]
            hex_val = s["hex"]
            desc = s["desc"].replace('"', '\\"')
            phon = s["phon"]
            typ = TYPE_MAP[s["type"]]
            logo = s["logo"].replace('"', '\\"')
            det = s["det"].replace('"', '\\"')
            lines.append(
                f'    ("{code}", 0x{hex_val:05X}, "{desc}", "{phon}", "{typ}", "{logo}", "{det}"),'
            )

        lines.append("]")
        lines.append("# fmt: on")
        lines.append("")

        filepath = BASE_DIR / f"{file_stem}.py"
        filepath.write_text("\n".join(lines), encoding="utf-8")
        print(f"  {filepath.name}: {len(signs)} signs")
        module_imports.append((file_stem, cat_code))

    # Generate __init__.py
    init_lines = [
        '"""Gardiner Sign List \u2014 complete reference data.',
        "",
        "Aggregates all per-category sign data into a single flat list.",
        "Each sign is a tuple:",
        "    (code, hex, description, phonetic, type, logographic, det_class)",
        '"""',
        "",
        "from __future__ import annotations",
        "",
    ]

    for stem, cat in module_imports:
        init_lines.append(
            f"from app.core.gardiner_data.{stem} import SIGNS as _{cat.upper()}_SIGNS"
        )

    init_lines.append("")
    init_lines.append(
        "ALL_SIGNS: list[tuple[str, int, str, str, str, str, str]] = []"
    )
    for _, cat in module_imports:
        init_lines.append(f"ALL_SIGNS.extend(_{cat.upper()}_SIGNS)")

    init_lines.append("")
    init_lines.append(
        "SIGN_INDEX: dict[str, tuple[str, int, str, str, str, str, str]] = {"
    )
    init_lines.append("    s[0]: s for s in ALL_SIGNS")
    init_lines.append("}")
    init_lines.append("")

    init_path = BASE_DIR / "__init__.py"
    init_path.write_text("\n".join(init_lines), encoding="utf-8")
    print(f"\n  __init__.py: imports {len(module_imports)} modules, "
          f"exports ALL_SIGNS ({total} signs) and SIGN_INDEX")
    print("\nDone!")


if __name__ == "__main__":
    generate()
