"""Inspect the hieroglyph classifier model.json format."""
import json

with open("models/hieroglyph/classifier/model.json", encoding="utf-8") as f:
    d = json.load(f)

print("Top keys:", list(d.keys()))
print("Format:", d.get("format"))
print("Generated by:", d.get("generatedBy"))

mt = d.get("modelTopology", {})
print("Topology keys:", list(mt.keys()))
print("Topology class:", mt.get("class_name"))

if "model_config" in mt:
    mc = mt["model_config"]
    print("model_config class:", mc.get("class_name"))
    cfg = mc.get("config", {})
    layers = cfg.get("layers", [])
    print("Layers:", len(layers))
    if layers:
        l0 = layers[0]
        print("First layer:", l0["class_name"], l0["config"].get("name"))
        l0_text = json.dumps(l0)
        print("  Has batch_shape?", '"batch_shape"' in l0_text)
        print("  Has batch_input_shape?", '"batch_input_shape"' in l0_text)
elif "node" in mt:
    print("Graph model: nodes =", len(mt.get("node", [])))

# Check for Keras 3 artifacts
text = json.dumps(d)
print()
print("=== Keras 3 artifact scan ===")
print("DTypePolicy:", text.count("DTypePolicy"))
has_bs = '"batch_shape"' in text
has_bis = '"batch_input_shape"' in text
print("batch_shape present:", has_bs)
print("batch_input_shape present:", has_bis)
print("silu:", text.count('"silu"'))
print("__keras_tensor__:", text.count("__keras_tensor__"))
print("inbound_nodes with args/kwargs:", text.count('"args"'))

# Check weightsManifest
wm = d.get("weightsManifest", [])
if wm:
    print()
    print("=== Weights ===")
    total = 0
    for group in wm:
        paths = group.get("paths", [])
        weights = group.get("weights", [])
        for p in paths:
            print(f"  Shard: {p}")
        total += len(weights)
    print(f"  Total weight entries: {total}")
