"""Comprehensive Gardiner Sign List — transliteration mapping (1000+ signs).

Facade module: imports raw sign data from gardiner_data/ package (26 category
files generated by scripts/build_gardiner_data.py), builds GardinerSign objects,
and exposes the same public API used by write.py, dictionary.py, and
transliteration.py.

Sources:
- Unicode 15.0 Egyptian Hieroglyphs block (U+13000–U+1342E)
- Gardiner, A.H. (1957) Egyptian Grammar, 3rd ed., Sign List pp.438–548
- Allen, J.P. (2014) Middle Egyptian, 3rd ed., pp.423–478
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from enum import Enum

from app.core.gardiner_data import ALL_SIGNS, SIGN_INDEX


class SignType(Enum):
    UNILITERAL = "uniliteral"
    BILITERAL = "biliteral"
    TRILITERAL = "triliteral"
    LOGOGRAM = "logogram"
    DETERMINATIVE = "determinative"
    ABBREVIATION = "abbreviation"
    NUMBER = "number"


_TYPE_MAP: dict[str, SignType] = {t.value.upper(): t for t in SignType}


@dataclass
class GardinerSign:
    """Complete data for a single Gardiner sign."""
    code: str
    transliteration: str
    sign_type: SignType
    description: str
    category: str
    phonetic_value: str
    logographic_value: str = ""
    determinative_class: str = ""
    unicode_char: str = ""
    alt_transliterations: list[str] | None = None


def _get_category(code: str) -> str:
    """Extract category letter(s) from code: 'A5A'→'A', 'Aa15'→'Aa'."""
    if code.startswith("Aa"):
        return "Aa"
    m = re.match(r"([A-Z])", code)
    return m.group(1) if m else code[0]


# ═══════════════════════════════════════════════════════════
# Build GARDINER_TRANSLITERATION from gardiner_data
# ═══════════════════════════════════════════════════════════

_ALT_TRANSLIT: dict[str, list[str]] = {
    "M18": ["ii", "y"],
    "O34": ["z"],
    "Z7": ["w"],
}

# Extra logographic / determinative overlays for curated signs
_LOGO_OVERLAYS: dict[str, str] = {
    "D4": "eye; to do, make",
    "D19": "nose",
    "D28": "ka (spirit)",
    "D56": "leg, foot",
    "E1": "bull",
    "E17": "lion",
    "F4": "bull",
    "F12": "mighty",
    "F13": "open",
    "F21": "to hear",
    "F31": "birth",
    "F34": "heart",
    "F35": "good, beautiful",
    "F40": "length",
    "G5": "Horus",
    "G14": "mother",
    "G24": "common people",
    "G25": "spirit, glory",
    "G26": "ba-soul",
    "G36": "great",
    "H6": "Maat, truth",
    "L1": "Khepri; to become",
    "M1": "tree, wood",
    "M4": "year",
    "M23": "King of Upper Egypt",
    "N5": "Ra; sun; day",
    "N14": "star",
    "N16": "land, earth",
    "N24": "nome, district",
    "N25": "foreign land",
    "N26": "mountain",
    "N29": "high",
    "N31": "road",
    "O1": "house",
    "O11": "palace",
    "O49": "city, town",
    "Q1": "throne; place",
    "Q7": "incense",
    "R4": "offering; peace",
    "R8": "god",
    "S34": "life; to live",
    "S42": "dominion",
    "V30": "lord; every",
    "X6": "cake",
    "X8": "to give",
    "Y3": "scribe; writing",
    "Y5": "senet",
    "Z1": "1; ideogram indicator",
    "D10": "Eye of Horus; well-being",
    "D1": "head",
    "D2": "face; upon",
}

_DET_OVERLAYS: dict[str, str] = {
    "D54": "motion, walking",
    "G7": "god, divine",
    "N2": "sky, heaven",
    "A55": "death",
    "Y1": "writing, abstract",
}


def _build_all_signs() -> dict[str, GardinerSign]:
    """Build GardinerSign objects from raw tuples in gardiner_data.

    Primary uniliterals are inserted first so that _build_reverse_map()
    in write.py encounters them before other signs that share the same
    phonetic value (e.g. S29 's' before O34 's').
    """
    # Primary uniliterals — these must appear first in iteration order
    _PRIMARY_UNILITERALS = [
        "G1", "M17", "M18", "D36", "G43", "D58", "Q3", "I9", "G17",
        "N35", "D21", "O4", "V28", "Aa1", "F32", "S29", "N37", "N29",
        "V31", "W11", "X1", "V13", "D46", "I10", "O34", "Z7",
    ]
    primary_set = set(_PRIMARY_UNILITERALS)

    def _make_sign(row: tuple) -> GardinerSign:
        code, hex_val, desc, phon, type_str, logo, det = row
        cat = _get_category(code)
        sign_type = _TYPE_MAP.get(type_str, SignType.DETERMINATIVE)
        return GardinerSign(
            code=code,
            transliteration=phon,
            sign_type=sign_type,
            description=desc,
            category=cat,
            phonetic_value=phon,
            logographic_value=logo or _LOGO_OVERLAYS.get(code, ""),
            determinative_class=det or _DET_OVERLAYS.get(code, ""),
            unicode_char=chr(hex_val),
            alt_transliterations=_ALT_TRANSLIT.get(code),
        )

    result: dict[str, GardinerSign] = {}

    # Pass 1: insert primary uniliterals first (iteration-order priority)
    for code in _PRIMARY_UNILITERALS:
        if code in SIGN_INDEX:
            result[code] = _make_sign(SIGN_INDEX[code])

    # Pass 2: insert all remaining signs
    for row in ALL_SIGNS:
        code = row[0]
        if code not in primary_set:
            result[code] = _make_sign(row)

    return result


GARDINER_TRANSLITERATION: dict[str, GardinerSign] = _build_all_signs()


# ═══════════════════════════════════════════════════════════
# Public helper API (backward-compatible)
# ═══════════════════════════════════════════════════════════

def get_transliteration(gardiner_code: str) -> str:
    """Get the transliteration for a Gardiner code."""
    sign = GARDINER_TRANSLITERATION.get(gardiner_code)
    if sign is None:
        return f"[{gardiner_code}]"
    if sign.phonetic_value:
        return sign.phonetic_value
    if sign.transliteration:
        return sign.transliteration
    return f"[{gardiner_code}]"


def get_sign_type(gardiner_code: str) -> SignType:
    """Get the type of a Gardiner sign."""
    sign = GARDINER_TRANSLITERATION.get(gardiner_code)
    if sign is None:
        return SignType.LOGOGRAM
    return sign.sign_type


def is_determinative(gardiner_code: str) -> bool:
    """Check if a Gardiner sign is primarily used as a determinative."""
    sign = GARDINER_TRANSLITERATION.get(gardiner_code)
    if sign is None:
        return False
    return sign.sign_type == SignType.DETERMINATIVE or bool(sign.determinative_class)


def get_determinative_class(gardiner_code: str) -> str:
    """Get the semantic class for a determinative sign."""
    sign = GARDINER_TRANSLITERATION.get(gardiner_code)
    if sign is None:
        return ""
    return sign.determinative_class


# ── Determinative categories (common semantic classifiers) ──

DETERMINATIVE_CATEGORIES: dict[str, list[str]] = {
    "man/person": ["A1", "A2", "A3", "A40", "A50", "A55", "B1"],
    "god/divine": ["G7", "R8", "C1", "C2"],
    "motion/walking": ["D54"],
    "death/enemy": ["A55", "Z6"],
    "negation": ["D35"],
    "abstract": ["Y1", "Y2"],
    "writing": ["Y1", "Y3"],
    "sky/above": ["N1", "N2"],
    "land/earth": ["N16", "N17", "N25"],
    "water": ["N35", "N36"],
    "city/place": ["O49", "O51"],
    "house/building": ["O1"],
    "eye/sight": ["D4", "D10"],
    "mouth/speech": ["D21"],
}

SIGN_TO_DET_CATEGORIES: dict[str, list[str]] = {}
for _cat, _signs in DETERMINATIVE_CATEGORIES.items():
    for _s in _signs:
        SIGN_TO_DET_CATEGORIES.setdefault(_s, []).append(_cat)
